"""
------------------------------------------------------------------------------
<auto-generated>
    This code was auto-generated by main/tools/jsonparser.
    Do not change this file.
</auto-generated>
------------------------------------------------------------------------------
"""
import json
import sys
import re
from six import string_types
from .OrganizationEntitlement import OrganizationEntitlement
from .RequestStatus import RequestStatus

# Unused import over optimization prevention
str(repr(RequestStatus))
str(repr(OrganizationEntitlement))


if sys.version_info > (3,):
    long = int
    unicode = str

class OrgListEntitlementResponse(object):
    """List of all organizations which have entitlement information. Only acce
    ssible by NGC admin portal"""
    def __init__(self, propDict=None):
        fromDict = propDict is not None and isinstance(propDict, dict)
        self.entitlements = (
            None if not fromDict or propDict.get(
                "entitlements"
            ) is None
            else [ OrganizationEntitlement(i)
            for i in propDict["entitlements"] ])
        self.requestStatus = (
            None if not fromDict or propDict.get(
                "requestStatus"
            ) is None
            else propDict["requestStatus"])

    @property
    def entitlements(self):
        """ """
        return self._entitlements

    @entitlements.setter
    def entitlements(self, value):
        if value is not None and not isinstance(value, list):
            value = list(value)
        if (value is None) or isinstance(value, list):
            self._entitlements = value
        else:
            raise TypeError(
                'Property "entitlements" of type "list<OrganizationEntitlemen'
                't>" set to wrong type'
            )

    @property
    def requestStatus(self):
        """ """
        return self._requestStatus

    @requestStatus.setter
    def requestStatus(self, value):
        if value is not None and not isinstance(value, RequestStatus):
            value = RequestStatus(value)
        if (value is None) or isinstance(value, RequestStatus):
            self._requestStatus = value
        else:
            raise TypeError(
                'Property "requestStatus" of type "list<RequestStatus>" set t'
                'o wrong type'
            )

    def toDict(self):
        result = {}
        if self._entitlements:
            result["entitlements"] = [
                i.toDict() for i in self._entitlements 
            ] if self._entitlements else []
        if self._requestStatus:
            result["requestStatus"] = \
                self._requestStatus.toDict() if self._requestStatus is not None else None
        return result

    def toJSON(self, pretty=False):
        if pretty:
            return json.dumps(self.toDict(), sort_keys=True, indent=4)
        else:
            return json.dumps(self.toDict(), sort_keys=True)

    def isValid(self):
        if (self._entitlements is not None):
            for obj in self._entitlements:
                if (obj is not None): obj.isValid()
        if (self._requestStatus is not None): self._requestStatus.isValid()
        return True
    

