_CXX2CTYPES = {
    "double": "ctypes.c_double",
    "int64_t": "ctypes.c_int64",
    "uint64_t": "ctypes.c_uint64",
    "float": "ctypes.c_float",
    "int32_t": "ctypes.c_int32",
    "uint32_t": "ctypes.c_uint32",
    "int16_t": "ctypes.c_int16",
    "uint16_t": "ctypes.c_uint16",
    "int8_t": "ctypes.c_int8",
    "uint8_t": "ctypes.c_uint8",
    "int": "ctypes.c_int",
    "bool": "ctypes.c_bool",
    "char": "ctypes.c_char",
    "short": "ctypes.c_short",
    "long": "ctypes.c_long",
    "long long": "ctypes.c_longlong",
    "std::string_view": "ctypes.c_char",
    "unsigned": "ctypes.c_uint",
}
