# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Blackcat Informatics® Inc.
"""Define shared configuration section keys used by mergers."""

from typing import Final

FILE_DISCOVERY_ROOTS_KEY = "roots"
FILE_DISCOVERY_EXCLUDES_KEY = "excludes"
FILE_DISCOVERY_EXPLICIT_KEY = "explicit_files"
FILE_DISCOVERY_LIMIT_KEY = "limit_to"
OUTPUT_TOOL_FILTERS_KEY = "tool_filters"
OUTPUT_MIN_SEVERITY_KEY = "pr_summary_min_severity"
OUTPUT_REPORT_OUT_KEY = "report_out"
OUTPUT_SARIF_OUT_KEY = "sarif_out"
OUTPUT_PR_SUMMARY_OUT_KEY = "pr_summary_out"
EXECUTION_ONLY_KEY = "only"
EXECUTION_LANGUAGES_KEY = "languages"
EXECUTION_ENABLE_KEY = "enable"
LICENSE_ALLOW_ALTERNATE_KEY = "allow_alternate_spdx"
LICENSE_EXCEPTIONS_KEY = "exceptions"
QUALITY_CHECKS_KEY = "checks"
QUALITY_SKIP_GLOBS_KEY = "skip_globs"
QUALITY_SCHEMA_TARGETS_KEY = "schema_targets"
QUALITY_PROTECTED_BRANCHES_KEY = "protected_branches"
CLEAN_PATTERNS_KEY = "patterns"
CLEAN_TREES_KEY = "trees"
UPDATE_SKIP_PATTERNS_KEY = "skip_patterns"
UPDATE_ENABLED_MANAGERS_KEY = "enabled_managers"
DEDUPE_PREFER_KEY = "dedupe_prefer"
GENERIC_VALUE_TYPES_ENABLED_KEY = "enabled"
GENERIC_VALUE_TYPES_RULES_KEY = "rules"
GENERIC_VALUE_TYPES_IMPLICATIONS_KEY = "implications"

__all__ = [
    "CLEAN_PATTERNS_KEY",
    "CLEAN_TREES_KEY",
    "DEDUPE_PREFER_KEY",
    "EXECUTION_ENABLE_KEY",
    "EXECUTION_LANGUAGES_KEY",
    "EXECUTION_ONLY_KEY",
    "FILE_DISCOVERY_EXCLUDES_KEY",
    "FILE_DISCOVERY_EXPLICIT_KEY",
    "FILE_DISCOVERY_LIMIT_KEY",
    "FILE_DISCOVERY_ROOTS_KEY",
    "GENERIC_VALUE_TYPES_ENABLED_KEY",
    "GENERIC_VALUE_TYPES_IMPLICATIONS_KEY",
    "GENERIC_VALUE_TYPES_RULES_KEY",
    "LICENSE_ALLOW_ALTERNATE_KEY",
    "LICENSE_EXCEPTIONS_KEY",
    "OUTPUT_MIN_SEVERITY_KEY",
    "OUTPUT_PR_SUMMARY_OUT_KEY",
    "OUTPUT_REPORT_OUT_KEY",
    "OUTPUT_SARIF_OUT_KEY",
    "OUTPUT_TOOL_FILTERS_KEY",
    "QUALITY_CHECKS_KEY",
    "QUALITY_PROTECTED_BRANCHES_KEY",
    "QUALITY_SCHEMA_TARGETS_KEY",
    "QUALITY_SKIP_GLOBS_KEY",
    "UPDATE_ENABLED_MANAGERS_KEY",
    "UPDATE_SKIP_PATTERNS_KEY",
]

SECTION_CONSTANT_NAMES: Final[tuple[str, ...]] = tuple(__all__)
