"""Vectorized technical indicator engine for qantify."""

from .indicators import (
    atr,
    bollinger_bands,
    cumulative_return,
    difference,
    donchian_channels,
    ema,
    hma,
    ichimoku,
    keltner_channels,
    lag,
    macd,
    obv,
    percent_rank,
    pvo,
    rolling_beta,
    rolling_correlation,
    rolling_volatility,
    rsi,
    sma,
    stochastic,
    true_range,
    vwma,
    wma,
    zscore,
)
from .pipeline import (
    FeaturePipeline,
    IndicatorTransform,
    LambdaTransform,
    RollingMeanTransform,
    SignalTransform,
    apply_hooks,
    register_signal_hook,
)
from .store import (
    StoredFeatures,
    FeatureKey,
    ParquetFeatureStore,
    RedisFeatureStore,
    FeastFeatureStoreAdapter,
    FeatureStoreManager,
)
from .indicators import (
    # Basic Technical Indicators
    ema,
    sma,
    wma,
    hma,
    vwma,
    rsi,
    macd,
    bollinger_bands,
    atr,
    true_range,
    rolling_volatility,
    keltner_channels,
    donchian_channels,
    stochastic,
    stochastic_rsi,
    ichimoku,
    zscore,
    percent_rank,
    cumulative_return,
    obv,
    pvo,
    rolling_beta,
    rolling_correlation,
    lag,
    difference,
    supertrend,
    heikin_ashi,
    adx,
    cci,
    mfi,
    pivot_points,

    # Advanced Technical Indicators
    williams_r,
    ultimate_oscillator,
    chaikin_money_flow,
    aroon,
    aroon_oscillator,
    elder_ray,
    force_index,
    ease_of_movement,
    volume_price_trend,
    negative_volume_index,
    positive_volume_index,
    accumulation_distribution,
    chaikin_oscillator,

    # Momentum & Oscillators
    chande_momentum_oscillator,
    psychological_line,
    vertical_horizontal_filter,
    trend_intensity_index,
    bull_bear_power,
    trix,
    vidya,
    alma,
    frama,
    gma,
    jma,
    lsma,
    mcginley_dynamic,

    # Price Calculations
    median_price,
    typical_price,
    weighted_close_price,
    price_channel,
    regression_channel,
    standard_error_channel,

        # Pattern Recognition
        andrews_pitchfork,
        gann_angles,
        fibonacci_retracements,
        fibonacci_extensions,
        harmonic_patterns,
        wolfe_waves,
        gartley_patterns,
        head_shoulders_patterns,
        double_top_bottom,
        wedge_patterns,
        triangle_patterns,
        flag_patterns,
        cup_handle_patterns,

        # Advanced Pattern Recognition Engine
        advanced_head_shoulders,
        complex_harmonic_patterns,
        advanced_wedge_patterns,
        advanced_triangle_patterns,
        rectangle_box_patterns,
        diamond_patterns,
        broadening_patterns,
        contracting_patterns,
        advanced_flag_patterns,
        pennant_patterns,
        inverse_head_shoulders,
        rounding_patterns,
        ascending_channel,
        descending_channel,

        # Machine Learning-Based Signal Generation
        clustering_market_regime_signals,
        autoencoder_anomaly_signals,
        lstm_price_prediction_signals,
        reinforcement_learning_signals,
        neural_network_regime_classifier,
        ensemble_ml_signals,
        feature_importance_signals,
        anomaly_detection_signals,
        time_series_forecast_signals,

        # Risk Management Signals
        value_at_risk_signals,
        drawdown_risk_signals,
        volatility_adjusted_signals,
        kelly_criterion_signals,
        conditional_value_at_risk_signals,
        risk_parity_signals,
        stress_testing_signals,
        liquidity_risk_signals,
        concentration_risk_signals,
        margin_risk_signals,

        # Multi-Timeframe Analysis
        resample_to_timeframe,
        align_multiple_timeframes,
        cross_timeframe_correlation_signals,
        hierarchical_signal_synthesis,
        multi_timeframe_momentum_signals,
        timeframe_synchronization_signals,
        multi_timeframe_pattern_recognition,
        hierarchical_signal_aggregation,
        multi_timeframe_volatility_signals,

    # Candlestick Patterns
    bullish_engulfing,
    bearish_engulfing,
    hammer,
    shooting_star,
    doji,
    morning_star,
    evening_star,
    three_white_soldiers,
    three_black_crows,
    piercing_pattern,
    dark_cloud_cover,

    # Advanced Volume Analysis
    volume_price_analysis,
    market_profile,
    volume_profile,
    order_flow,
    time_price_opportunity,
    market_facilitation_index,
    tick_volume,
    volume_oscillator,
    price_volume_trend,
    volume_relative_strength_index,
    volume_flow_indicator,
    volume_weighted_average_price,
    volume_weighted_moving_average,
    intraday_intensity,
    money_flow_multiplier,
    money_flow_index,
    commodity_channel_index,
    klinger_oscillator,
    schaff_trend_cycle,
    coppock_curve,
    rainbow_oscillator,
    dynamic_momentum_index,
    relative_vigor_index,
    stochastic_momentum_index,
    triple_ema_oscillator,
)
from .bot_templates import (
    BotResult,
    MeanReversionConfig,
    BreakoutConfig,
    run_mean_reversion_bot,
    run_breakout_bot,
)

__all__ = [
    # Basic Technical Indicators
    "ema",
    "sma",
    "wma",
    "hma",
    "vwma",
    "rsi",
    "macd",
    "bollinger_bands",
    "atr",
    "true_range",
    "rolling_volatility",
    "keltner_channels",
    "donchian_channels",
    "stochastic",
    "stochastic_rsi",
    "ichimoku",
    "zscore",
    "percent_rank",
    "cumulative_return",
    "obv",
    "pvo",
    "rolling_beta",
    "rolling_correlation",
    "lag",
    "difference",
    "supertrend",
    "heikin_ashi",
    "adx",
    "cci",
    "mfi",
    "pivot_points",

    # Advanced Technical Indicators
    "williams_r",
    "ultimate_oscillator",
    "chaikin_money_flow",
    "aroon",
    "aroon_oscillator",
    "elder_ray",
    "force_index",
    "ease_of_movement",
    "volume_price_trend",
    "negative_volume_index",
    "positive_volume_index",
    "accumulation_distribution",
    "chaikin_oscillator",

    # Momentum & Oscillators
    "chande_momentum_oscillator",
    "psychological_line",
    "vertical_horizontal_filter",
    "trend_intensity_index",
    "bull_bear_power",
    "trix",
    "vidya",
    "alma",
    "frama",
    "gma",
    "jma",
    "lsma",
    "mcginley_dynamic",

    # Price Calculations
    "median_price",
    "typical_price",
    "weighted_close_price",
    "price_channel",
    "regression_channel",
    "standard_error_channel",

        # Pattern Recognition
        "andrews_pitchfork",
        "gann_angles",
        "fibonacci_retracements",
        "fibonacci_extensions",
        "harmonic_patterns",
        "wolfe_waves",
        "gartley_patterns",
        "head_shoulders_patterns",
        "double_top_bottom",
        "wedge_patterns",
        "triangle_patterns",
        "flag_patterns",
        "cup_handle_patterns",

        # Advanced Pattern Recognition Engine
        "advanced_head_shoulders",
        "complex_harmonic_patterns",
        "advanced_wedge_patterns",
        "advanced_triangle_patterns",
        "rectangle_box_patterns",
        "diamond_patterns",
        "broadening_patterns",
        "contracting_patterns",
        "advanced_flag_patterns",
        "pennant_patterns",
        "inverse_head_shoulders",
        "rounding_patterns",
        "ascending_channel",
        "descending_channel",

        # Machine Learning-Based Signal Generation
        "clustering_market_regime_signals",
        "autoencoder_anomaly_signals",
        "lstm_price_prediction_signals",
        "reinforcement_learning_signals",
        "neural_network_regime_classifier",
        "ensemble_ml_signals",
        "feature_importance_signals",
        "anomaly_detection_signals",
        "time_series_forecast_signals",

        # Risk Management Signals
        "value_at_risk_signals",
        "drawdown_risk_signals",
        "volatility_adjusted_signals",
        "kelly_criterion_signals",
        "conditional_value_at_risk_signals",
        "risk_parity_signals",
        "stress_testing_signals",
        "liquidity_risk_signals",
        "concentration_risk_signals",
        "margin_risk_signals",

        # Multi-Timeframe Analysis
        "resample_to_timeframe",
        "align_multiple_timeframes",
        "cross_timeframe_correlation_signals",
        "hierarchical_signal_synthesis",
        "multi_timeframe_momentum_signals",
        "timeframe_synchronization_signals",
        "multi_timeframe_pattern_recognition",
        "hierarchical_signal_aggregation",
        "multi_timeframe_volatility_signals",

    # Candlestick Patterns
    "bullish_engulfing",
    "bearish_engulfing",
    "hammer",
    "shooting_star",
    "doji",
    "morning_star",
    "evening_star",
    "three_white_soldiers",
    "three_black_crows",
    "piercing_pattern",
    "dark_cloud_cover",

    # Advanced Volume Analysis
    "volume_price_analysis",
    "market_profile",
    "volume_profile",
    "order_flow",
    "time_price_opportunity",
    "market_facilitation_index",
    "tick_volume",
    "volume_oscillator",
    "price_volume_trend",
    "volume_relative_strength_index",
    "volume_flow_indicator",
    "volume_weighted_average_price",
    "volume_weighted_moving_average",
    "intraday_intensity",
    "money_flow_multiplier",
    "money_flow_index",
    "commodity_channel_index",
    "klinger_oscillator",
    "schaff_trend_cycle",
    "coppock_curve",
    "rainbow_oscillator",
    "dynamic_momentum_index",
    "relative_vigor_index",
    "stochastic_momentum_index",
    "triple_ema_oscillator",

    # Pipeline and Store
    "FeaturePipeline",
    "SignalTransform",
    "IndicatorTransform",
    "RollingMeanTransform",
    "LambdaTransform",
    "register_signal_hook",
    "apply_hooks",
    "StoredFeatures",
    "FeatureKey",
    "ParquetFeatureStore",
    "RedisFeatureStore",
    "FeastFeatureStoreAdapter",
    "FeatureStoreManager",

    # Bot Templates
    "BotResult",
    "MeanReversionConfig",
    "BreakoutConfig",
    "PairsTradingConfig",
    "ArbitrageConfig",
    "TrendFollowingConfig",
    "MLBasedConfig",
    "RiskParityConfig",
    "MultiTimeframeConfig",
    "run_mean_reversion_bot",
    "run_breakout_bot",
    "run_pairs_trading_bot",
    "run_arbitrage_bot",
    "run_trend_following_bot",
    "run_ml_based_bot",
    "run_risk_parity_bot",
    "run_multi_timeframe_bot",

    # Benchmarking and Performance Analysis
    "BenchmarkResult",
    "BenchmarkSuite",
    "PerformanceProfile",
    "BenchmarkConfig",
    "generate_price_series",
    "generate_ohlcv_data",
    "get_memory_usage",
    "get_cpu_usage",
    "profile_function_execution",
    "run_benchmark",
    "run_parallel_benchmark",
    "run_scalability_benchmark",
    "compare_implementations",
    "generate_benchmark_report",
    "default_benchmark_suite",
    "comprehensive_benchmark_suite",
    "ml_benchmark_suite",
    "risk_benchmark_suite",
    "pattern_recognition_benchmark_suite",
    "multi_timeframe_benchmark_suite",
]

from .bot_templates import (
    BotResult,
    MeanReversionConfig,
    BreakoutConfig,
    PairsTradingConfig,
    ArbitrageConfig,
    TrendFollowingConfig,
    MLBasedConfig,
    RiskParityConfig,
    MultiTimeframeConfig,
    run_mean_reversion_bot,
    run_breakout_bot,
    run_pairs_trading_bot,
    run_arbitrage_bot,
    run_trend_following_bot,
    run_ml_based_bot,
    run_risk_parity_bot,
    run_multi_timeframe_bot,
)

from .benchmarks import (
    BenchmarkResult,
    BenchmarkSuite,
    PerformanceProfile,
    BenchmarkConfig,
    generate_price_series,
    generate_ohlcv_data,
    get_memory_usage,
    get_cpu_usage,
    profile_function_execution,
    run_benchmark,
    run_parallel_benchmark,
    run_scalability_benchmark,
    compare_implementations,
    generate_benchmark_report,
    default_benchmark_suite,
    comprehensive_benchmark_suite,
    ml_benchmark_suite,
    risk_benchmark_suite,
    pattern_recognition_benchmark_suite,
    multi_timeframe_benchmark_suite,
)
