# coding: utf-8

"""
Fireblocks API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.6.2
Contact: support@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.iban_destination import IbanDestination


class TestIbanDestination(unittest.TestCase):
    """IbanDestination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IbanDestination:
        """Test IbanDestination
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `IbanDestination`
        """
        model = IbanDestination()
        if include_optional:
            return IbanDestination(
                type = 'IBAN',
                address = {"accountHolder":{"name":"Maria Gonzalez","city":"Madrid","country":"ES","subdivision":"MD","address":"Calle Gran Via 123, 2°B","postalCode":"28013"},"iban":"ES9121000418450200051332"}
            )
        else:
            return IbanDestination(
                type = 'IBAN',
                address = {"accountHolder":{"name":"Maria Gonzalez","city":"Madrid","country":"ES","subdivision":"MD","address":"Calle Gran Via 123, 2°B","postalCode":"28013"},"iban":"ES9121000418450200051332"},
        )
        """

    def testIbanDestination(self):
        """Test IbanDestination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
