# coding: utf-8

"""
Fireblocks API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.6.2
Contact: support@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.transfer_peer_type_enum import TransferPeerTypeEnum


class TestTransferPeerTypeEnum(unittest.TestCase):
    """TransferPeerTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransferPeerTypeEnum(self):
        """Test TransferPeerTypeEnum"""
        # inst = TransferPeerTypeEnum()


if __name__ == "__main__":
    unittest.main()
