# coding: utf-8

"""
Fireblocks API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.6.2
Contact: support@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.spei_basic_payment_info import SpeiBasicPaymentInfo


class TestSpeiBasicPaymentInfo(unittest.TestCase):
    """SpeiBasicPaymentInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpeiBasicPaymentInfo:
        """Test SpeiBasicPaymentInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SpeiBasicPaymentInfo`
        """
        model = SpeiBasicPaymentInfo()
        if include_optional:
            return SpeiBasicPaymentInfo(
                spei_clabe = '012180001234567890',
                spei_name = 'Juan Pérez'
            )
        else:
            return SpeiBasicPaymentInfo(
                spei_clabe = '012180001234567890',
        )
        """

    def testSpeiBasicPaymentInfo(self):
        """Test SpeiBasicPaymentInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
