# coding: utf-8

"""
Fireblocks API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.6.2
Contact: support@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.participant_relationship_type import ParticipantRelationshipType


class TestParticipantRelationshipType(unittest.TestCase):
    """ParticipantRelationshipType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParticipantRelationshipType(self):
        """Test ParticipantRelationshipType"""
        # inst = ParticipantRelationshipType()


if __name__ == "__main__":
    unittest.main()
