# coding: utf-8

"""
Fireblocks API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.6.2
Contact: support@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_create_tag(self) -> None:
        """Test case for create_tag

        Create a tag
        """
        pass

    def test_delete_tag(self) -> None:
        """Test case for delete_tag

        Delete a tag
        """
        pass

    def test_get_tag(self) -> None:
        """Test case for get_tag

        Get a tag
        """
        pass

    def test_get_tags(self) -> None:
        """Test case for get_tags

        Get list of tags
        """
        pass

    def test_update_tag(self) -> None:
        """Test case for update_tag

        Update a tag
        """
        pass


if __name__ == "__main__":
    unittest.main()
