# coding: utf-8

"""
Fireblocks API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.6.2
Contact: support@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.legacy_policy_rule_amount_aggregation import (
    LegacyPolicyRuleAmountAggregation,
)


class TestLegacyPolicyRuleAmountAggregation(unittest.TestCase):
    """LegacyPolicyRuleAmountAggregation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LegacyPolicyRuleAmountAggregation:
        """Test LegacyPolicyRuleAmountAggregation
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LegacyPolicyRuleAmountAggregation`
        """
        model = LegacyPolicyRuleAmountAggregation()
        if include_optional:
            return LegacyPolicyRuleAmountAggregation(
                operators = 'PER_SINGLE_MATCH',
                src_transfer_peers = 'PER_SINGLE_MATCH',
                dst_transfer_peers = 'PER_SINGLE_MATCH'
            )
        else:
            return LegacyPolicyRuleAmountAggregation(
        )
        """

    def testLegacyPolicyRuleAmountAggregation(self):
        """Test LegacyPolicyRuleAmountAggregation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
