# Generated by Django 5.2.4 on 2025-09-07 14:57

from django.db import migrations
from django.utils.text import slugify


def fix_field(field):
    if field.get('field_type') == 'likert':
        field['rubrics'] = field.pop('values', [])
        field['scores'] = list(reversed(range(1, len(field['rubrics']) + 1)))
    return field


def fix_likert_choices(apps, schema_editor):
    FormType = apps.get_model('dynforms', 'FormType')
    db_alias = schema_editor.connection.alias

    to_update = FormType.objects.using(db_alias).all()
    for form_type in to_update:
        for page in form_type.pages:
            page['fields'] = [fix_field(field) for field in page.get('fields', [])]
    FormType.objects.using(db_alias).bulk_update(to_update, ['pages'])


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0006_fix_likert_choices'),
    ]

    operations = [
        migrations.RunPython(fix_likert_choices, reverse_code=migrations.RunPython.noop),
    ]
