{
 "title": "Current Assets",
 "description": "Provides a real-time summary and detailed breakdown of all assets currently held in the DAO's treasury, including stablecoins, ETH, BTC, and other asset types. Useful for monitoring the DAO's current financial position, asset allocation, and recent changes. Data Links allow quick navigation to transaction details for each token.",
 "tags": [
  "assets",
  "current"
 ],
 "time": { "from": "now-3d", "to": "now" },
 "panels": [
  {
   "title": "Total Assets",
   "type": "stat",
   "description": "Displays the total value of all DAO treasury assets in USD, aggregated across all wallets, asset types, and buckets.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (bucket, token)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Stablecoins",
   "type": "stat",
   "description": "Displays the total USD value of all stablecoins (cash & cash equivalents) held in any of the DAO's treasury wallets.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"Cash & cash equivalents\"}<500_000_000) by (bucket, token)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total ETH",
   "type": "stat",
   "description": "Displays the total USD value of all ETH and ETH-like tokens held in any of the DAO's treasury wallets.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"ETH\"}<500_000_000) by (bucket, token)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total BTC",
   "type": "stat",
   "description": "Displays the total USD value of all BTC and BTC-like tokens held in any of the DAO's treasury wallets.",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"BTC\"}<500_000_000) by (bucket, token)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "table",
   "description": "Shows the timestamp of the most recent complete data snapshot for treasury assets.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "piechart",
   "description": "Pie chart visualizing the distribution of treasury assets by bucket (e.g., stablecoins, ETH, BTC, other assets).",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Asset Summary",
   "type": "table",
   "description": "Table summarizing the latest known USD value for each asset token and bucket, including all available tokens in any of the DAO's treasury wallets.",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (token, bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Asset Breakdown",
   "type": "table",
   "description": "Detailed breakdown of the latest known USD value for each asset token and bucket, including all available tokens in any of the DAO's treasury wallets.\n\nData Link: Click any token to view all transactions for that token in the Treasury Transactions dashboard.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (token, bucket)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}