# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Blackcat Informatics® Inc.

"""Section merger utilities for configuration handling."""

from .constants import (
    CLEAN_PATTERNS_KEY,
    CLEAN_TREES_KEY,
    DEDUPE_PREFER_KEY,
    EXECUTION_ENABLE_KEY,
    EXECUTION_LANGUAGES_KEY,
    EXECUTION_ONLY_KEY,
    FILE_DISCOVERY_EXCLUDES_KEY,
    FILE_DISCOVERY_EXPLICIT_KEY,
    FILE_DISCOVERY_LIMIT_KEY,
    FILE_DISCOVERY_ROOTS_KEY,
    LICENSE_ALLOW_ALTERNATE_KEY,
    LICENSE_EXCEPTIONS_KEY,
    OUTPUT_MIN_SEVERITY_KEY,
    OUTPUT_PR_SUMMARY_OUT_KEY,
    OUTPUT_REPORT_OUT_KEY,
    OUTPUT_SARIF_OUT_KEY,
    OUTPUT_TOOL_FILTERS_KEY,
    QUALITY_CHECKS_KEY,
    QUALITY_PROTECTED_BRANCHES_KEY,
    QUALITY_SCHEMA_TARGETS_KEY,
    QUALITY_SKIP_GLOBS_KEY,
    UPDATE_ENABLED_MANAGERS_KEY,
    UPDATE_SKIP_PATTERNS_KEY,
)
from .merge_utils import (
    FieldName,
    ModelT,
    ModelUpdateValue,
    PathResolver,
    SectionDiff,
    SectionName,
    _coerce_optional_bool,
    _coerce_optional_str_value,
    _ensure_optional_path,
    _model_replace,
    _SectionMerger,
)
from .mergers import build_section_mergers

__all__ = [
    "CLEAN_PATTERNS_KEY",
    "CLEAN_TREES_KEY",
    "DEDUPE_PREFER_KEY",
    "EXECUTION_ENABLE_KEY",
    "EXECUTION_LANGUAGES_KEY",
    "EXECUTION_ONLY_KEY",
    "FILE_DISCOVERY_EXCLUDES_KEY",
    "FILE_DISCOVERY_EXPLICIT_KEY",
    "FILE_DISCOVERY_LIMIT_KEY",
    "FILE_DISCOVERY_ROOTS_KEY",
    "LICENSE_ALLOW_ALTERNATE_KEY",
    "LICENSE_EXCEPTIONS_KEY",
    "OUTPUT_MIN_SEVERITY_KEY",
    "OUTPUT_PR_SUMMARY_OUT_KEY",
    "OUTPUT_REPORT_OUT_KEY",
    "OUTPUT_SARIF_OUT_KEY",
    "OUTPUT_TOOL_FILTERS_KEY",
    "QUALITY_CHECKS_KEY",
    "QUALITY_PROTECTED_BRANCHES_KEY",
    "QUALITY_SCHEMA_TARGETS_KEY",
    "QUALITY_SKIP_GLOBS_KEY",
    "UPDATE_ENABLED_MANAGERS_KEY",
    "UPDATE_SKIP_PATTERNS_KEY",
    "ModelUpdateValue",
    "PathResolver",
    "SectionDiff",
    "SectionName",
    "FieldName",
    "ModelT",
    "_SectionMerger",
    "_coerce_optional_bool",
    "_coerce_optional_str_value",
    "_ensure_optional_path",
    "_model_replace",
    "build_section_mergers",
]
