from typing import Union, Any

Value = Union[str, int, float, bool, None]

class Interpreter:
    @staticmethod
    def check_if_callable(value: Any) -> bool: ...
    @staticmethod
    def check_if_prop(value: Any) -> bool: ...
    def register_callable(self, name: str, value: CallableGenerator) -> None: ...
    def register_property(self, name: str, value: Prop) -> None: ...

    def run(self) -> bool: ...
    def stop(self) -> None: ...
    def reset(self) -> None: ...

class Compiler:
    @staticmethod
    def check_if_callable(value: Any) -> bool: ...
    @staticmethod
    def check_if_prop(value: Any) -> bool: ...
    def register_callable(self, name: str, value: CallableGenerator) -> None: ...
    def register_property(self, name: str, value: Prop) -> None: ...
    def compile(self, source: str) -> bool: ...
    def print_errors(self) -> None: ...
    def into_interpreter(self) -> Interpreter: ...

class Arg:
    def is_value(self) -> bool: ...
    def is_word(self) -> bool: ...
    def matches_word(self, s: str) -> bool: ...

class Callable:
    def call(self) -> bool: ...
    def terminate(self) -> None: ...

class CallableGenerator:
    def generate(self) -> Callable: ...
    def call(check_syntax: list[Arg]) -> None: ...

class Prop:
    def get(self) -> Value: ...
    def set(self, value: Value) -> None: ...
    def settable(self) -> bool: ...
