from .base import BaseSettings as BaseSettings
from _typeshed import Incomplete

class Settings:
    def configure(self, settings_module: str | None = None, settings_class: type[BaseSettings] | None = None) -> None: ...
    def get(self, name: str, default: object = None) -> object: ...
    def __getattr__(self, name: str) -> object: ...
    def to_dict(self) -> dict[str, object]: ...
    def reload(self) -> None: ...

class LazySettings:
    def __init__(self, settings: Settings | None = None) -> None: ...
    def __getattr__(self, name: str) -> object: ...
    def __setattr__(self, name: str, value: object) -> None: ...
    def configure(self, **kwargs: object) -> None: ...
    def get(self, name: str, default: object = None) -> object: ...
    def set(self, name: str, value: object) -> None: ...
    def update(self, **kwargs: object) -> None: ...
    def to_dict(self) -> dict[str, object]: ...
    def reload(self) -> None: ...

settings: Incomplete
