from .constants import DEFAULT_BUFFER_SIZE as DEFAULT_BUFFER_SIZE
from .exceptions import BufferOverflowError as BufferOverflowError
from _typeshed import Incomplete

class UnReader:
    sock: Incomplete
    max_buffer: Incomplete
    def __init__(self, sock, max_buffer: int = ...) -> None: ...
    def read(self, size: int | None = None) -> bytes: ...
    def readline(self, max_length: int | None = None) -> bytes: ...
    def unread(self, data: bytes | bytearray) -> None: ...
    def peek(self, size: int = 1) -> bytes: ...
