from typing import Any, Callable
from zephyr._types import ASGIApp as ASGIApp, Receive as Receive, Scope as Scope, Send as Send
from zephyr.security.user import User as User

def requires_auth(func: Callable[..., Any]) -> Callable[..., Any]: ...
def requires_permission(permission: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def requires_role(role: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def requires_mfa(func: Callable[..., Any]) -> Callable[..., Any]: ...
