"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cacheentry import CacheEntry, CacheEntryTypedDict
from langcache.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class SearchResponseTypedDict(TypedDict):
    r"""Response representing the result of a successful cache entries search operation"""

    data: List[CacheEntryTypedDict]
    r"""Array of cache entries matching the search criteria. This array is empty if no entries match the search criteria."""


class SearchResponse(BaseModel):
    r"""Response representing the result of a successful cache entries search operation"""

    data: List[CacheEntry]
    r"""Array of cache entries matching the search criteria. This array is empty if no entries match the search criteria."""
