# coding: utf-8

"""
    Kadoa API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Contact: support@kadoa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v4_workflows_workflow_id_jobs_job_id_get200_response import V4WorkflowsWorkflowIdJobsJobIdGet200Response

class TestV4WorkflowsWorkflowIdJobsJobIdGet200Response(unittest.TestCase):
    """V4WorkflowsWorkflowIdJobsJobIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V4WorkflowsWorkflowIdJobsJobIdGet200Response:
        """Test V4WorkflowsWorkflowIdJobsJobIdGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V4WorkflowsWorkflowIdJobsJobIdGet200Response`
        """
        model = V4WorkflowsWorkflowIdJobsJobIdGet200Response()
        if include_optional:
            return V4WorkflowsWorkflowIdJobsJobIdGet200Response(
                id = '',
                state = 'IN_PROGRESS',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                limit = 56,
                workflow_id = '',
                variables = None,
                protocol = openapi_client.models._v4_workflows__workflow_id__jobs__job_id__get_200_response_protocol._v4_workflows__workflowId__jobs__jobId__get_200_response_protocol(
                    decision = '', 
                    reasoning = '', )
            )
        else:
            return V4WorkflowsWorkflowIdJobsJobIdGet200Response(
        )
        """

    def testV4WorkflowsWorkflowIdJobsJobIdGet200Response(self):
        """Test V4WorkflowsWorkflowIdJobsJobIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
