---
Title: "Function Reference"  
include-before-body:
 text: |
  <script>document.title = "Function Reference";</script>
---

      
# Function reference {.doc .doc-index}

## Power Bpy

Python functions for building Power BI dashboards

| | |
| --- | --- |
| [add_ADLS_csv](add_ADLS_csv.qmd#powerbpy.add_ADLS_csv) |  |
| [add_background_image](add_background_image.qmd#powerbpy.add_background_image) |  |
| [add_button](add_button.qmd#powerbpy.add_button) | Add a text box to a page |
| [add_card](add_card.qmd#powerbpy.add_card) | Add a card to a page |
| [add_local_csv](add_local_csv.qmd#powerbpy.add_local_csv) |  |
| [add_shape_map](add_shape_map.qmd#powerbpy.add_shape_map) | Add a map to a page |
| [add_slicer](add_slicer.qmd#powerbpy.add_slicer) | Add a slicer to a page |
| [add_text_box](add_text_box.qmd#powerbpy.add_text_box) | Add a text box to a page |
| [add_tmdl](add_tmdl.qmd#powerbpy.add_tmdl) |  |
| [create_blank_dashboard](create_blank_dashboard.qmd#powerbpy.create_blank_dashboard) |  |
| [create_new_chart](create_new_chart.qmd#powerbpy.create_new_chart) |  |
| [create_new_page](create_new_page.qmd#powerbpy.create_new_page) |  |
| [create_tmdl](create_tmdl.qmd#powerbpy.create_tmdl) | An internally called function that creates a TMDL file from a pandas dataframe |
| [generate_bin_measures](generate_bin_measures.qmd#powerbpy.generate_bin_measures) |  |
| [update_diagramLayout](update_diagramLayout.qmd#powerbpy.update_diagramLayout) | This is an internal function to add a dataset to the diagramLayout file when a new dataset is added.  |
| [update_model_file](update_model_file.qmd#powerbpy.update_model_file) | This is an internal function to add a dataset to the model.tmdl file when a new dataset is added.  |
