from dataclasses import fields
import os
import sys
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
from utils_qt_mk.config import _PACKAGE_DIR, _STUBS_DIR, theme_dir
from utils_qt_mk.colours import ColourSelector, set_extended_default
from utils_qt_mk.custom_file_dialog import custom_dialog, CFDType
from utils_qt_mk.general import SignalBlocker, get_imports, get_functions, get_classes, stub_repr, qt_connect
from utils_qt_mk.theme import set_widget_theme, ThemeParameters, WidgetTheme


def write_stub() -> None: ...


class _ColourSetter(QWidget):
	def __init__(self) -> None: ...
	def _set_colour_label(self) -> None: ...
	def _setup_connections(self) -> None: ...
	def _setup_ui(self) -> None: ...
	def _slot_colour_selector(self) -> None: ...
	def _slot_update_selector(self) -> None: ...
	def _update_colour(self) -> None: ...
	def _update_spinboxes(self) -> None: ...
	def set_enabled(self, new_state: bool) -> None: ...
	@property
	def colour(self) -> QColor: ...
	@colour.setter
	def colour(self, new_colour: QColor) -> None: ...


class _ThemePreview(QWidget):
	def __init__(self) -> None: ...
	def _setup_ui(self) -> None: ...


class ThemeCreator(QDialog):
	def __init__(self) -> None: ...
	def __getattr__(self, name: str) -> Any: ...
	def _setup_connections(self) -> None: ...
	def _setup_ui(self) -> None: ...
	def _slot_delete_theme(self) -> None: ...
	def _slot_export_theme(self) -> None: ...
	def _slot_update_by_combobox(self, index: int) -> None: ...
	def _slot_update_by_custom_colours(self) -> None: ...
	def _slot_use_existing_theme(self) -> None: ...


class _TestApplication(QMainWindow):
	def __init__(self) -> None: ...
	def _setup_connections(self) -> None: ...
	def _setup_ui(self) -> None: ...
	@classmethod
	def _slot_tc_test(cls) -> None: ...
