# This module is meant to remove the possibility of circular imports in the
# toplevel stuff by implementing a 'Base' class for each type. Later on, this
# might also contain the base implementation of each type. If that is the case,
# this module will likely be converted to a cython module.

class BaseArray:...
class BaseBoolean:...
class BaseInt:...
class BaseNumber:...
class BaseString:...
class BaseUint:...
class BaseVector:...
