from as3lib._toplevel.Object import Object


class XMLList(Object):
   def __init__(self, value):...
   def attribute(self, attributeName):...
   def attributes(self):...
   def child(self, propertyName):...
   def children(self):...
   def comments(self):...
   def contains(self, value):...
   def copy(self):...
   def decendants(self, name):...
   def elements(self, name):...
   def hasComplexContext(self):...
   def hasOwnProperty(self, p):...
   def hasSimpleContext(self):...
   def length(self):...
   def normalize(self):...
   def parent(self):...
   def processingInstructions(self, name):...
   def propertyIsEnumerable(self, p):...
   def text(self):...
   def toString(self):...
   def toXMLString(self):...

   def valueOf(self):
      return self


class XML(Object):
   ignoreComments = True
   ignoreProcessingInstructions = True
   ignoreWhitespace = True
   prettyIndent = 2
   prettyPrinting = True

   def __init__(self, value):...
   def addNamespace(self, ns):...
   def appendChild(self, child):...
   def attribute(self, attributeName):...
   def attributes(self):...
   def child(self, propertyName):...
   def childIndex(self):...
   def children(self):...
   def comments(self):...
   def contains(self, value):...
   def copy(self):...
   @staticmethod
   def defaultSettings():
      # TODO: Make this return an Object once that is properly implemented
      return {
         'ignoreComments': True,
         'ignoreProcessingInstructions': True,
         'ignoreWhitespace': True,
         'prettyIndent': 2,
         'prettyPrinting': True
      }
   def decendants(self, name):...
   def elements(self, name):...
   def hasComplexContext(self):...
   def hasOwnProperty(self, p):...
   def hasSimpleContext(self):...
   def inScopeNamespace(self):...
   def inserChildAfter(self, child1, child2):...
   def insertChildBefore(self, child1, child2):...

   def length(self):
      return 1

   def localName(self):...
   def name(self):...
   def namespace(prefix):...
   def namespaceDeclarations(self):...
   def nodeKind(self):...
   def normalize(self):...
   def parent(self):...
   def prependChild(self):...
   def processingInstructions(self, name):...
   def propertyIsEnumerable(self, p):...
   def removeNamespace(self, ns):...
   def replace(self, propertyName, value):...
   def setChildren(self, value):...
   def setLocalName(self, name):...
   def setName(self, name):...
   def setNamespace(self, name):...
   def setSettings(self, *rest):...
   def settings(self):...
   def text(self):...
   def toString(self):...
   def toXMLString(self):...

   def valueOf(self):
      return self
