import os


action: str | None = os.environ.get("GITHUB_ACTION")
action_ref: str | None = os.environ.get("GITHUB_ACTION_REF")
action_repository: str | None = os.environ.get("GITHUB_ACTION_REPOSITORY")
actions: str | None = os.environ.get("GITHUB_ACTIONS")
actor: str | None = os.environ.get("GITHUB_ACTOR")
actor_id: str | None = os.environ.get("GITHUB_ACTOR_ID")
api_url: str | None = os.environ.get("GITHUB_API_URL")
base_ref: str | None = os.environ.get("GITHUB_BASE_REF")
env: str | None = os.environ.get("GITHUB_ENV")
event_name: str | None = os.environ.get("GITHUB_EVENT_NAME")
event_path: str | None = os.environ.get("GITHUB_EVENT_PATH")
graphql_url: str | None = os.environ.get("GITHUB_GRAPHQL_URL")
head_ref: str | None = os.environ.get("GITHUB_HEAD_REF")
job: str | None = os.environ.get("GITHUB_JOB")
output: str | None = os.environ.get("GITHUB_OUTPUT")
path: str | None = os.environ.get("GITHUB_PATH")
ref: str | None = os.environ.get("GITHUB_REF")
ref_name: str | None = os.environ.get("GITHUB_REF_NAME")
ref_protected: str | None = os.environ.get("GITHUB_REF_PROTECTED")
ref_type: str | None = os.environ.get("GITHUB_REF_TYPE")
repository: str | None = os.environ.get("GITHUB_REPOSITORY")
repository_id: str | None = os.environ.get("GITHUB_REPOSITORY_ID")
repository_owner: str | None = os.environ.get("GITHUB_REPOSITORY_OWNER")
repository_owner_id: str | None = os.environ.get("GITHUB_REPOSITORY_OWNER_ID")
retention_days: str | None = os.environ.get("GITHUB_RETENTION_DAYS")
run_attempt: str | None = os.environ.get("GITHUB_RUN_ATTEMPT")
run_id: str | None = os.environ.get("GITHUB_RUN_ID")
run_number: str | None = os.environ.get("GITHUB_RUN_NUMBER")
server_url: str | None = os.environ.get("GITHUB_SERVER_URL")
sha: str | None = os.environ.get("GITHUB_SHA")
step_summary: str | None = os.environ.get("GITHUB_STEP_SUMMARY")
triggering_actor: str | None = os.environ.get("GITHUB_TRIGGERING_ACTOR")
workflow: str | None = os.environ.get("GITHUB_WORKFLOW")
workflow_ref: str | None = os.environ.get("GITHUB_WORKFLOW_REF")
workflow_sha: str | None = os.environ.get("GITHUB_WORKFLOW_SHA")
workspace: str | None = os.environ.get("GITHUB_WORKSPACE")

runner_arch: str | None = os.environ.get("RUNNER_ARCH")
runner_debug: str | None = os.environ.get("RUNNER_DEBUG")
runner_environment: str | None = os.environ.get("RUNNER_ENVIRONMENT")
runner_name: str | None = os.environ.get("RUNNER_NAME")
runner_os: str | None = os.environ.get("RUNNER_OS")
runner_temp: str | None = os.environ.get("RUNNER_TEMP")
runner_tool_cache: str | None = os.environ.get("RUNNER_TOOL_CACHE")
