"""
------------------------------------------------------------------------------
<auto-generated>
    This code was auto-generated by main/tools/jsonparser.
    Do not change this file.
</auto-generated>
------------------------------------------------------------------------------
"""
import json
import sys
import re
from six import string_types
from .ResourceTypeEnum import ResourceTypeEnum
from .LabelValue import LabelValue

# Unused import over optimization prevention
str(repr(LabelValue))
str(repr(ResourceTypeEnum))


if sys.version_info > (3,):
    long = int
    unicode = str

class LabelSetResponse(object):
    """Request to create a new label group"""
    def __init__(self, propDict=None):
        fromDict = propDict is not None and isinstance(propDict, dict)
        self.display = (
            None if not fromDict or propDict.get(
                "display"
            ) is None
            else propDict["display"])
        self.isGlobal = (
            None if not fromDict or propDict.get(
                "isGlobal"
            ) is None
            else propDict["isGlobal"])
        self.isReadOnly = (
            None if not fromDict or propDict.get(
                "isReadOnly"
            ) is None
            else propDict["isReadOnly"])
        self.labels = (
            None if not fromDict or propDict.get(
                "labels"
            ) is None
            else [ LabelValue(i)
            for i in propDict["labels"] ])
        self.orgName = (
            None if not fromDict or propDict.get(
                "orgName"
            ) is None
            else propDict["orgName"])
        self.resourceType = (
            None if not fromDict or propDict.get(
                "resourceType"
            ) is None
            else propDict["resourceType"])
        self.teamName = (
            None if not fromDict or propDict.get(
                "teamName"
            ) is None
            else propDict["teamName"])
        self.value = (
            None if not fromDict or propDict.get(
                "value"
            ) is None
            else propDict["value"])

    @property
    def display(self):
        """str: Display name of the label set to show to end user"""
        return self._display

    @display.setter
    def display(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._display = value
        else:
            raise TypeError(
                'Property "display" of type "list<str>" set to wrong type'
            )

    @property
    def isGlobal(self):
        """bool: indicate if label set is managed by NVIDIA and available for 
        all users"""
        return self._isGlobal

    @isGlobal.setter
    def isGlobal(self, value):
        if value is not None and not isinstance(value, bool):
            value = bool(value)
        if (value is None) or isinstance(value, bool):
            self._isGlobal = value
        else:
            raise TypeError(
                'Property "isGlobal" of type "list<bool>" set to wrong type'
            )

    @property
    def isReadOnly(self):
        """bool: indicate if current user has read only permissions"""
        return self._isReadOnly

    @isReadOnly.setter
    def isReadOnly(self, value):
        if value is not None and not isinstance(value, bool):
            value = bool(value)
        if (value is None) or isinstance(value, bool):
            self._isReadOnly = value
        else:
            raise TypeError(
                'Property "isReadOnly" of type "list<bool>" set to wrong type'
            )

    @property
    def labels(self):
        """list: Labels"""
        return self._labels

    @labels.setter
    def labels(self, value):
        if value is not None and not isinstance(value, list):
            value = list(value)
        if (value is None) or isinstance(value, list):
            self._labels = value
        else:
            raise TypeError(
                'Property "labels" of type "list<LabelValue>" set to wrong ty'
                'pe'
            )

    @property
    def orgName(self):
        """str: Name of the org that the label set belongs to"""
        return self._orgName

    @orgName.setter
    def orgName(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._orgName = value
        else:
            raise TypeError(
                'Property "orgName" of type "list<str>" set to wrong type'
            )

    @property
    def resourceType(self):
        """ResourceTypeEnum: Type of resource ie job, container, model..."""
        return self._resourceType

    @resourceType.setter
    def resourceType(self, value):
        if (value is None) or isinstance(value, str) or isinstance(value, unicode):
            self._resourceType = value
        else:
            raise TypeError(
                'Property "resourceType" of type "list<ResourceTypeEnum>" set'
                ' to wrong type'
            )

    @property
    def teamName(self):
        """str: Name of the team that the label set belongs to"""
        return self._teamName

    @teamName.setter
    def teamName(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._teamName = value
        else:
            raise TypeError(
                'Property "teamName" of type "list<str>" set to wrong type'
            )

    @property
    def value(self):
        """str: Label set name"""
        return self._value

    @value.setter
    def value(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._value = value
        else:
            raise TypeError(
                'Property "value" of type "list<str>" set to wrong type'
            )

    def toDict(self):
        result = {}
        if self._display is not None:
            result["display"] = \
                self._display
        if self._isGlobal is not None:
            result["isGlobal"] = \
                self._isGlobal
        if self._isReadOnly is not None:
            result["isReadOnly"] = \
                self._isReadOnly
        if self._labels:
            result["labels"] = [
                i.toDict() for i in self._labels 
            ] if self._labels else []
        if self._orgName is not None:
            result["orgName"] = \
                self._orgName
        if self._resourceType is not None:
            result["resourceType"] = \
                self._resourceType
        if self._teamName is not None:
            result["teamName"] = \
                self._teamName
        if self._value is not None:
            result["value"] = \
                self._value
        return result

    def toJSON(self, pretty=False):
        if pretty:
            return json.dumps(self.toDict(), sort_keys=True, indent=4)
        else:
            return json.dumps(self.toDict(), sort_keys=True)

    def isValid(self):
        if self._value is None:
            raise ValueError(
                "LabelSetResponse.value doesnt match requirement:" 
                "required: True"
            )
        if (self._value is not None
            and
            len(self._value) > 64):
            raise ValueError(
                "LabelSetResponse.value: " + str(self._value) + 
                " doesnt match requirement: maxLength: 64")
        if (self._value is not None
            and
            not re.match(
                r"^[a-z][a-zA-Z0-9-.+_]+",
                 self._value)):
            raise ValueError(
                "LabelSetResponse.value: " + str(self._value) + 
                " doesnt match requirement: pattern: ^[a-z][a-zA-Z0-9-.+_]+")
        if self._display is None:
            raise ValueError(
                "LabelSetResponse.display doesnt match requirement:" 
                "required: True"
            )
        if (self._display is not None
            and
            len(self._display) > 64):
            raise ValueError(
                "LabelSetResponse.display: " + str(self._display) + 
                " doesnt match requirement: maxLength: 64")
        if (self._labels is not None):
            for obj in self._labels:
                if (obj is not None): obj.isValid()
        return True
    

