import typing
from contextlib import asynccontextmanager
from typing import ParamSpec

P = ParamSpec('P')
T = typing.TypeVar('T')

async def run_until_first_complete(*args: tuple[typing.Callable, dict]) -> None: ...
async def run_in_threadpool(func: typing.Callable[P, T], *args: P.args, **kwargs: P.kwargs) -> T: ...

class _StopIteration(Exception): ...

async def iterate_in_threadpool(iterator: typing.Iterable[T]) -> typing.AsyncIterator[T]: ...
@asynccontextmanager
async def contextmanager_in_threadpool(cm: typing.ContextManager[T]) -> typing.AsyncGenerator[T, None]: ...
