from typing import Final

# Felicita scale characteristics
DATA_SERVICE_UUID: Final = "ffe0"
DATA_CHARACTERISTIC_UUID: Final = "ffe1"

# Felicita command codes
CMD_WEIGHT_ONLY_MODE: Final = 0x31
CMD_WEIGHT_AND_TIMER_MODE: Final = 0x32
CMD_START_TIMER_BY_FLOW_MODE: Final = 0x33
CMD_START_TIMER_BY_FLOW_AUTOTARE_MODE: Final = 0x34
CMD_START_TIMER_BY_TARE_AUTOTARE_MODE: Final = 0x35
CMD_TOGGLE_BEEP: Final = 0x42
CMD_RESET_TIMER: Final = 0x43
CMD_SET_MAX_WEIGHT_2KG: Final = 0x4d
CMD_START_TIMER: Final = 0x52
CMD_STOP_TIMER: Final = 0x53
CMD_TARE: Final = 0x54
CMD_TOGGLE_UNIT: Final = 0x55
CMD_SET_MAX_WEIGHT_1KG: Final = 0x6d

MIN_BATTERY_LEVEL: Final = 137
MAX_BATTERY_LEVEL: Final = 161

SCALE_START_NAMES: Final = ["FELICITA"]