# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.v1_extranets_b2b_peering_consumer_customer_id_consumer_details_get200_response_ipsec_tunnel_config_inner import V1ExtranetsB2bPeeringConsumerCustomerIdConsumerDetailsGet200ResponseIpsecTunnelConfigInner
from graphiant_sdk.models.v1_extranets_b2b_peering_consumer_match_id_post_request_site_to_site_vpn import V1ExtranetsB2bPeeringConsumerMatchIdPostRequestSiteToSiteVpn
from typing import Optional, Set
from typing_extensions import Self

class V1GatewaysGuestConsumerMatchIdGet200Response(BaseModel):
    """
    V1GatewaysGuestConsumerMatchIdGet200Response
    """ # noqa: E501
    destination_prefixes: Optional[List[StrictStr]] = Field(default=None, alias="destinationPrefixes")
    ipsec_tunnel_config: Optional[List[V1ExtranetsB2bPeeringConsumerCustomerIdConsumerDetailsGet200ResponseIpsecTunnelConfigInner]] = Field(default=None, alias="ipsecTunnelConfig")
    site_to_site_vpn: Optional[V1ExtranetsB2bPeeringConsumerMatchIdPostRequestSiteToSiteVpn] = Field(default=None, alias="siteToSiteVpn")
    __properties: ClassVar[List[str]] = ["destinationPrefixes", "ipsecTunnelConfig", "siteToSiteVpn"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1GatewaysGuestConsumerMatchIdGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ipsec_tunnel_config (list)
        _items = []
        if self.ipsec_tunnel_config:
            for _item_ipsec_tunnel_config in self.ipsec_tunnel_config:
                if _item_ipsec_tunnel_config:
                    _items.append(_item_ipsec_tunnel_config.to_dict())
            _dict['ipsecTunnelConfig'] = _items
        # override the default output from pydantic by calling `to_dict()` of site_to_site_vpn
        if self.site_to_site_vpn:
            _dict['siteToSiteVpn'] = self.site_to_site_vpn.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1GatewaysGuestConsumerMatchIdGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "destinationPrefixes": obj.get("destinationPrefixes"),
            "ipsecTunnelConfig": [V1ExtranetsB2bPeeringConsumerCustomerIdConsumerDetailsGet200ResponseIpsecTunnelConfigInner.from_dict(_item) for _item in obj["ipsecTunnelConfig"]] if obj.get("ipsecTunnelConfig") is not None else None,
            "siteToSiteVpn": V1ExtranetsB2bPeeringConsumerMatchIdPostRequestSiteToSiteVpn.from_dict(obj["siteToSiteVpn"]) if obj.get("siteToSiteVpn") is not None else None
        })
        return _obj


