# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.objective_value_entry import ObjectiveValueEntry

class TestObjectiveValueEntry(unittest.TestCase):
    """ObjectiveValueEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObjectiveValueEntry:
        """Test ObjectiveValueEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObjectiveValueEntry`
        """
        model = ObjectiveValueEntry()
        if include_optional:
            return ObjectiveValueEntry(
                unit = '',
                value = 1.337,
                id = ''
            )
        else:
            return ObjectiveValueEntry(
                value = 1.337,
                id = '',
        )
        """

    def testObjectiveValueEntry(self):
        """Test ObjectiveValueEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
