# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.prf_p1_algorithm import PrfP1Algorithm

class TestPrfP1Algorithm(unittest.TestCase):
    """PrfP1Algorithm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrfP1Algorithm(self):
        """Test PrfP1Algorithm"""
        # inst = PrfP1Algorithm()

if __name__ == '__main__':
    unittest.main()
