# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@keysight.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyperf.models.objective_unit import ObjectiveUnit

class TestObjectiveUnit(unittest.TestCase):
    """ObjectiveUnit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectiveUnit(self):
        """Test ObjectiveUnit"""
        # inst = ObjectiveUnit()

if __name__ == '__main__':
    unittest.main()
