# coding: utf-8

"""
    Dalux Build API

    # Getting started To access data objects through a service, a customer specific API key is required. Contact <support@dalux.com> to activate the API for your company profile if you have not done so already. The key is tied to individual API identities found in settings under API identities.  # Calling a service The documentation only provides a part of the url specified for requests, e.g.  `GET /4.0/projects`  To complete the request, you must append the API base url. The base URL is optained by contacting <support@dalux.com>. to get all projects, you would call  `{BASE_URL}/4.0/projects`  Authorization is provided by adding your API key to a header parameter called ‘X-API-KEY’  Example with curl  `curl GET '{BASE_URL}/4.0/projects' --header 'X-API-KEY: {YOUR_API_KEY}'`  # Common object model  Dalux expose a number of API's. They share an overarching object architecture which is described in a [Common object model](https://app.swaggerhub.com/apis-docs/Dalux/GettingStarted/2.0)   # noqa: E501

    OpenAPI spec version: 4.12
    Contact: support@dalux.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CatalogueCompany(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'catalog_company_id': 'str',
        'name': 'str',
        'vat_number': 'str',
        'address': 'str',
        'website': 'str',
        'description': 'str',
        'zip_code': 'str',
        'city': 'str',
        'phone_number': 'str',
        'email': 'str'
    }

    attribute_map = {
        'catalog_company_id': 'catalogCompanyId',
        'name': 'name',
        'vat_number': 'vatNumber',
        'address': 'address',
        'website': 'website',
        'description': 'description',
        'zip_code': 'zipCode',
        'city': 'city',
        'phone_number': 'phoneNumber',
        'email': 'email'
    }

    def __init__(self, catalog_company_id=None, name=None, vat_number=None, address=None, website=None, description=None, zip_code=None, city=None, phone_number=None, email=None):  # noqa: E501
        """CatalogueCompany - a model defined in Swagger"""  # noqa: E501
        self._catalog_company_id = None
        self._name = None
        self._vat_number = None
        self._address = None
        self._website = None
        self._description = None
        self._zip_code = None
        self._city = None
        self._phone_number = None
        self._email = None
        self.discriminator = None
        if catalog_company_id is not None:
            self.catalog_company_id = catalog_company_id
        if name is not None:
            self.name = name
        if vat_number is not None:
            self.vat_number = vat_number
        if address is not None:
            self.address = address
        if website is not None:
            self.website = website
        if description is not None:
            self.description = description
        if zip_code is not None:
            self.zip_code = zip_code
        if city is not None:
            self.city = city
        if phone_number is not None:
            self.phone_number = phone_number
        if email is not None:
            self.email = email

    @property
    def catalog_company_id(self):
        """Gets the catalog_company_id of this CatalogueCompany.  # noqa: E501


        :return: The catalog_company_id of this CatalogueCompany.  # noqa: E501
        :rtype: str
        """
        return self._catalog_company_id

    @catalog_company_id.setter
    def catalog_company_id(self, catalog_company_id):
        """Sets the catalog_company_id of this CatalogueCompany.


        :param catalog_company_id: The catalog_company_id of this CatalogueCompany.  # noqa: E501
        :type: str
        """

        self._catalog_company_id = catalog_company_id

    @property
    def name(self):
        """Gets the name of this CatalogueCompany.  # noqa: E501


        :return: The name of this CatalogueCompany.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CatalogueCompany.


        :param name: The name of this CatalogueCompany.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def vat_number(self):
        """Gets the vat_number of this CatalogueCompany.  # noqa: E501


        :return: The vat_number of this CatalogueCompany.  # noqa: E501
        :rtype: str
        """
        return self._vat_number

    @vat_number.setter
    def vat_number(self, vat_number):
        """Sets the vat_number of this CatalogueCompany.


        :param vat_number: The vat_number of this CatalogueCompany.  # noqa: E501
        :type: str
        """

        self._vat_number = vat_number

    @property
    def address(self):
        """Gets the address of this CatalogueCompany.  # noqa: E501


        :return: The address of this CatalogueCompany.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this CatalogueCompany.


        :param address: The address of this CatalogueCompany.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def website(self):
        """Gets the website of this CatalogueCompany.  # noqa: E501


        :return: The website of this CatalogueCompany.  # noqa: E501
        :rtype: str
        """
        return self._website

    @website.setter
    def website(self, website):
        """Sets the website of this CatalogueCompany.


        :param website: The website of this CatalogueCompany.  # noqa: E501
        :type: str
        """

        self._website = website

    @property
    def description(self):
        """Gets the description of this CatalogueCompany.  # noqa: E501


        :return: The description of this CatalogueCompany.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CatalogueCompany.


        :param description: The description of this CatalogueCompany.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def zip_code(self):
        """Gets the zip_code of this CatalogueCompany.  # noqa: E501


        :return: The zip_code of this CatalogueCompany.  # noqa: E501
        :rtype: str
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code):
        """Sets the zip_code of this CatalogueCompany.


        :param zip_code: The zip_code of this CatalogueCompany.  # noqa: E501
        :type: str
        """

        self._zip_code = zip_code

    @property
    def city(self):
        """Gets the city of this CatalogueCompany.  # noqa: E501


        :return: The city of this CatalogueCompany.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this CatalogueCompany.


        :param city: The city of this CatalogueCompany.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def phone_number(self):
        """Gets the phone_number of this CatalogueCompany.  # noqa: E501


        :return: The phone_number of this CatalogueCompany.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this CatalogueCompany.


        :param phone_number: The phone_number of this CatalogueCompany.  # noqa: E501
        :type: str
        """

        self._phone_number = phone_number

    @property
    def email(self):
        """Gets the email of this CatalogueCompany.  # noqa: E501


        :return: The email of this CatalogueCompany.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this CatalogueCompany.


        :param email: The email of this CatalogueCompany.  # noqa: E501
        :type: str
        """

        self._email = email

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CatalogueCompany, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CatalogueCompany):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
