# Generated by Django 3.2.12 on 2022-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linker", "0002_set_default_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gwrlink", name="context", field=models.JSONField(default=dict)
        )
    ]
