def _add_inplace(indices_a, values_a, indices_b, values_b): ...
def _add_inplace_2d(rows_a, cols_a, vals_a, rows_b, cols_b, vals_b): ...
def _intersect_indices(result_indices, result_values, self_indices, self_values, other_indices, strict: bool = False) -> int: ...
def _intersect_indices_2d(result_rows, result_cols, result_values, self_rows, self_cols, self_values, other_rows, other_cols, strict: bool = False) -> int: ...
def _dotproduct_vm(result_indices, result_values, v_indices, v_values, m_rows, m_cols, m_vals) -> int: ...
def _changes(result_indices, result_values, self_indices, self_values, other_indices, other_values, update: bool = False, precision: float = 1e-6) -> int: ...
def _to_dense_vector(result_values, indices, values): ...
def _to_dense_matrix(result_values, rows, cols, values): ...
def _isin(result, indices, test_indices): ...
