BEGIN TRANSACTION;

-- Step 1: Deduplicate staging data
CREATE OR REPLACE TEMPORARY TABLE TMP_DEDUPED AS
SELECT
    TRANSACTION_ID,
    ANY_VALUE(CUSTOMER_NAME) AS CUSTOMER_NAME,
    ANY_VALUE(PRODUCT_CODE) AS PRODUCT_CODE,
    ANY_VALUE(QUANTITY) AS QUANTITY,
    ANY_VALUE(SALE_AMOUNT) AS SALE_AMOUNT,
    ANY_VALUE(SALE_DATE) AS SALE_DATE
FROM RAW.STG_SALES
GROUP BY TRANSACTION_ID;

-- Step 2: Transform and validate
CREATE OR REPLACE TEMPORARY TABLE TMP_TRANSFORMED AS
SELECT
    TRANSACTION_ID,
    INITCAP(TRIM(CUSTOMER_NAME)) AS CUSTOMER_NAME,   -- clean names
    UPPER(TRIM(PRODUCT_CODE)) AS PRODUCT_CODE,        -- normalize product code
    NVL(NULLIF(QUANTITY, 0), 1) AS QUANTITY,          -- replace 0 with 1
    SALE_AMOUNT,
    TRY_TO_DATE(SALE_DATE, 'MM/DD/YYYY') AS SALE_DATE -- safely convert to date
FROM TMP_DEDUPED
WHERE TRY_TO_DATE(SALE_DATE, 'MM/DD/YYYY') IS NOT NULL;

-- Step 3: Incremental load (insert new records only)
MERGE INTO ANALYTICS.SALES_FACT AS TARGET
USING TMP_TRANSFORMED AS SOURCE
ON TARGET.TRANSACTION_ID = SOURCE.TRANSACTION_ID
WHEN NOT MATCHED THEN
  INSERT (TRANSACTION_ID, CUSTOMER_NAME, PRODUCT_CODE, QUANTITY, SALE_AMOUNT, SALE_DATE)
  VALUES (SOURCE.TRANSACTION_ID, SOURCE.CUSTOMER_NAME, SOURCE.PRODUCT_CODE, SOURCE.QUANTITY, SOURCE.SALE_AMOUNT, SOURCE.SALE_DATE);

-- Step 4: Log ETL summary
INSERT INTO ANALYTICS.ETL_LOG (RUN_ID, RUN_TIMESTAMP, ROWS_INSERTED, STATUS, MESSAGE)
SELECT
    UUID_STRING(),
    CURRENT_TIMESTAMP(),
    (SELECT COUNT(*) FROM TMP_TRANSFORMED),
    'SUCCESS',
    'ETL completed successfully.';

-- Step 5: Clear staging table (optional)
TRUNCATE TABLE RAW.STG_SALES;

COMMIT;
