# Erosional exhumation (EE) models - "crust-only" = Fixed Moho depth
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-option1 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 2.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE1-crust-only-explicit
tc1d-cli --init-moho-depth 45.0 --ero-option1 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 2.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE1-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-option1 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE2-crust-only-explicit
tc1d-cli --init-moho-depth 45.0 --ero-option1 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE2-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 2 --ero-option1 5.0 --ero-option2 5.0 --ero-option3 5.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE3-crust-only-explicit
tc1d-cli --init-moho-depth 45.0 --ero-type 2 --ero-option1 5.0 --ero-option2 5.0 --ero-option3 5.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE3-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 2 --ero-option1 5.0 --ero-option2 45.0 --ero-option3 5.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE4-crust-only-explicit
tc1d-cli --init-moho-depth 45.0 --ero-type 2 --ero-option1 5.0 --ero-option2 45.0 --ero-option3 5.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE4-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-option1 20.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 2.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE5-crust-only-explicit
tc1d-cli --init-moho-depth 55.0 --ero-option1 20.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 2.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE5-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-option1 20.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE6-crust-only-explicit
tc1d-cli --init-moho-depth 55.0 --ero-option1 20.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE6-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 2 --ero-option1 10.0 --ero-option2 5.0 --ero-option3 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE7-crust-only-explicit
tc1d-cli --init-moho-depth 55.0 --ero-type 2 --ero-option1 10.0 --ero-option2 5.0 --ero-option3 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE7-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 2 --ero-option1 10.0 --ero-option2 45.0 --ero-option3 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE8-crust-only-explicit
tc1d-cli --init-moho-depth 55.0 --ero-type 2 --ero-option1 10.0 --ero-option2 45.0 --ero-option3 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE8-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 3 --ero-option1 10.0 --ero-option2 2.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE9-crust-only-explicit
tc1d-cli --init-moho-depth 45.0 --ero-type 3 --ero-option1 10.0 --ero-option2 2.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE9-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 3 --ero-option1 10.0 --ero-option2 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE10-crust-only-explicit
tc1d-cli --init-moho-depth 45.0 --ero-type 3 --ero-option1 10.0 --ero-option2 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE10-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 3 --ero-option1 10.0 --ero-option2 50.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE11-crust-only-explicit
tc1d-cli --init-moho-depth 45.0 --ero-type 3 --ero-option1 10.0 --ero-option2 50.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE11-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 3 --ero-option1 20.0 --ero-option2 2.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE12-crust-only-explicit
tc1d-cli --init-moho-depth 55.0 --ero-type 3 --ero-option1 20.0 --ero-option2 2.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE12-explicit

# Sedimentary burial (SB) models
tc1d-cli --init-moho-depth 35.0 --ero-type 2 --ero-option1 -9.0 --ero-option2 10.0 --ero-option3 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 2.0 --log-output --log-file tc1d_model_output_log.csv --model-id SBEE1-explicit
tc1d-cli --init-moho-depth 35.0 --ero-type 2 --ero-option1 -9.0 --ero-option2 10.0 --ero-option3 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id SBEE2-explicit
tc1d-cli --init-moho-depth 35.0 --ero-type 2 --ero-option1 -9.0 --ero-option2 20.0 --ero-option3 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 2.0 --log-output --log-file tc1d_model_output_log.csv --model-id SBEE3-explicit
tc1d-cli --init-moho-depth 35.0 --ero-type 2 --ero-option1 -9.0 --ero-option2 20.0 --ero-option3 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id SBEE4-explicit
tc1d-cli --init-moho-depth 35.0 --ero-type 2 --ero-option1 -9.0 --ero-option2 1.0 --ero-option3 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 2.0 --log-output --log-file tc1d_model_output_log.csv --model-id SBEE5-explicit
tc1d-cli --init-moho-depth 35.0 --ero-type 2 --ero-option1 -9.0 --ero-option2 1.0 --ero-option3 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id SBEE6-explicit

# Thrust faulting (TF) models
tc1d-cli --time 55.0 --init-moho-depth 50.0 --ero-type 7 --ero-option1 -5.0 --ero-option2 0.5 --ero-option3 30 --ero-option4 15.5 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.19444444 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id TF1-explicit-55 --plot-depth-history --plot-fault-depth-history --invert-tt-plot --past-age-increment 1.0 --write-past-ages
tc1d-cli --time 55.0 --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 7 --ero-option1 -5.0 --ero-option2 0.5 --ero-option3 30 --ero-option4 15.5 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.19444444 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id TF1-crust-only-explicit-55 --plot-depth-history --plot-fault-depth-history --invert-tt-plot --past-age-increment 1.0 --write-past-ages
tc1d-cli --time 55.0 --init-moho-depth 37.5 --ero-type 7 --ero-option1 -5.0 --ero-option2 -0.5 --ero-option3 30 --ero-option4 2.0 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.19444444 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id TF2-explicit-55 --plot-depth-history --plot-fault-depth-history --invert-tt-plot
tc1d-cli --time 55.0 --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 7 --ero-option1 -5.0 --ero-option2 -0.5 --ero-option3 30 --ero-option4 2.0 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.19444444 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id TF2-crust-only-explicit-55 --plot-depth-history --plot-fault-depth-history --invert-tt-plot
tc1d-cli --time 55.0 --init-moho-depth 50.0 --ero-type 7 --ero-option1 -5.0 --ero-option2 0.0 --ero-option3 30.0 --ero-option4 15.5 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.05555556 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id TF3-explicit-55 --plot-depth-history --plot-fault-depth-history --invert-tt-plot --past-age-increment 1.0 --write-past-ages
tc1d-cli --time 55.0 --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 7 --ero-option1 -5.0 --ero-option2 0.0 --ero-option3 30.0 --ero-option4 15.5 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.05555556 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id TF3-crust-only-explicit-55 --plot-depth-history --plot-fault-depth-history --invert-tt-plot --past-age-increment 1.0 --write-past-ages
tc1d-cli --time 55.0 --init-moho-depth 37.5 --ero-type 7 --ero-option1 -5.0 --ero-option2 0.0 --ero-option3 30.0 --ero-option4 2.0 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.05555556 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id TF4-explicit-55 --plot-depth-history --plot-fault-depth-history --invert-tt-plot --past-age-increment 1.0 --write-past-ages
tc1d-cli --time 55.0 --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 7 --ero-option1 -5.0 --ero-option2 0.0 --ero-option3 30.0 --ero-option4 2.0 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.05555556 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id TF4-crust-only-explicit-55 --plot-depth-history --plot-fault-depth-history --invert-tt-plot --past-age-increment 1.0 --write-past-ages

# Extensional faulting (EF) models
tc1d-cli --time 55.0 --init-moho-depth 50.0 --ero-type 7 --ero-option1 5.0 --ero-option2 0.5 --ero-option3 30 --ero-option4 14.5 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.19444444 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id EF1-explicit-55
tc1d-cli --time 55.0 --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 7 --ero-option1 5.0 --ero-option2 0.5 --ero-option3 30 --ero-option4 14.5 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.19444444 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id EF1-crust-only-explicit-55
tc1d-cli --time 55.0 --init-moho-depth 37.5 --ero-type 7 --ero-option1 5.0 --ero-option2 -0.5 --ero-option3 30 --ero-option4 3.0 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.19444444 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id EF2-explicit-55
tc1d-cli --time 55.0 --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 7 --ero-option1 5.0 --ero-option2 -0.5 --ero-option3 30 --ero-option4 3.0 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.19444444 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id EF2-crust-only-explicit-55
tc1d-cli --time 55.0 --init-moho-depth 50.0 --ero-type 7 --ero-option1 5.0 --ero-option2 1.0 --ero-option3 30.0 --ero-option4 14.5 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.05555556 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EF3-explicit-55
tc1d-cli --time 55.0 --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 7 --ero-option1 5.0 --ero-option2 1.0 --ero-option3 30.0 --ero-option4 14.5 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.05555556 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EF3-crust-only-explicit-55
tc1d-cli --time 55.0 --init-moho-depth 37.5 --ero-type 7 --ero-option1 5.0 --ero-option2 -1.0 --ero-option3 30.0 --ero-option4 3.0 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.05555556 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EF4-explicit-55
tc1d-cli --time 55.0 --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 7 --ero-option1 5.0 --ero-option2 -1.0 --ero-option3 30.0 --ero-option4 3.0 --ero-option5 0.0 --ero-option6 5.0 --ero-option7 0.05555556 --ero-option8 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EF4-crust-only-explicit-55

# Delamination (DL) models
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-option1 15.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --removal-fraction 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id DL1-crust-only-explicit
tc1d-cli --init-moho-depth 50.0 --ero-option1 15.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --removal-fraction 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id DL1-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 3 --ero-option1 15.0 --ero-option2 2.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --removal-fraction 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id DL2-crust-only-explicit
tc1d-cli --init-moho-depth 50.0 --ero-type 3 --ero-option1 15.0 --ero-option2 2.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --removal-fraction 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id DL2-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 3 --ero-option1 15.0 --ero-option2 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --removal-fraction 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id DL3-crust-only-explicit
tc1d-cli --init-moho-depth 50.0 --ero-type 3 --ero-option1 15.0 --ero-option2 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --removal-fraction 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id DL3-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 3 --ero-option1 15.0 --ero-option2 50.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --removal-fraction 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id DL4-crust-only-explicit
tc1d-cli --init-moho-depth 50.0 --ero-type 3 --ero-option1 15.0 --ero-option2 50.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --removal-fraction 1.0 --log-output --log-file tc1d_model_output_log.csv --model-id DL4-explicit

# 15-km EE models for comparison with DL models
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-option1 15.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE2-crust-only-15km-explicit
tc1d-cli --init-moho-depth 50.0 --ero-option1 15.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE2-15km-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 3 --ero-option1 15.0 --ero-option2 2.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE9-crust-only-15km-explicit
tc1d-cli --init-moho-depth 50.0 --ero-type 3 --ero-option1 15.0 --ero-option2 2.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE9-15km-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 3 --ero-option1 15.0 --ero-option2 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE10-crust-only-15km-explicit
tc1d-cli --init-moho-depth 50.0 --ero-type 3 --ero-option1 15.0 --ero-option2 10.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE10-15km-explicit
tc1d-cli --init-moho-depth 35.0 --fixed-moho --crustal-uplift --ero-type 3 --ero-option1 15.0 --ero-option2 50.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE11-crust-only-15km-explicit
tc1d-cli --init-moho-depth 50.0 --ero-type 3 --ero-option1 15.0 --ero-option2 50.0 --save-plots --no-display-plots --explicit --dt 500.0 --heat-prod-crust 1.0 --past-age-increment 1.0 --write-past-ages --log-output --log-file tc1d_model_output_log.csv --model-id EE11-15km-explicit
