from ccxt.base.types import Entry


class ImplicitAPI:
    # fapi Public API
    fapi_public_get_v1_ping = fapiPublicGetV1Ping = Entry('v1/ping', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_time = fapiPublicGetV1Time = Entry('v1/time', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_exchangeinfo = fapiPublicGetV1ExchangeInfo = Entry('v1/exchangeInfo', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_depth = fapiPublicGetV1Depth = Entry('v1/depth', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_trades = fapiPublicGetV1Trades = Entry('v1/trades', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_historicaltrades = fapiPublicGetV1HistoricalTrades = Entry('v1/historicalTrades', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_aggtrades = fapiPublicGetV1AggTrades = Entry('v1/aggTrades', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_klines = fapiPublicGetV1Klines = Entry('v1/klines', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_indexpriceklines = fapiPublicGetV1IndexPriceKlines = Entry('v1/indexPriceKlines', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_markpriceklines = fapiPublicGetV1MarkPriceKlines = Entry('v1/markPriceKlines', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_premiumindex = fapiPublicGetV1PremiumIndex = Entry('v1/premiumIndex', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_fundingrate = fapiPublicGetV1FundingRate = Entry('v1/fundingRate', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_fundinginfo = fapiPublicGetV1FundingInfo = Entry('v1/fundingInfo', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_ticker_24hr = fapiPublicGetV1Ticker24hr = Entry('v1/ticker/24hr', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_ticker_price = fapiPublicGetV1TickerPrice = Entry('v1/ticker/price', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_ticker_bookticker = fapiPublicGetV1TickerBookTicker = Entry('v1/ticker/bookTicker', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_adlquantile = fapiPublicGetV1AdlQuantile = Entry('v1/adlQuantile', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_get_v1_forceorders = fapiPublicGetV1ForceOrders = Entry('v1/forceOrders', ['fapi', 'public'], 'GET', {'cost': 1})
    fapi_public_post_v1_listenkey = fapiPublicPostV1ListenKey = Entry('v1/listenKey', ['fapi', 'public'], 'POST', {'cost': 1})
    fapi_public_put_v1_listenkey = fapiPublicPutV1ListenKey = Entry('v1/listenKey', ['fapi', 'public'], 'PUT', {'cost': 1})
    fapi_public_delete_v1_listenkey = fapiPublicDeleteV1ListenKey = Entry('v1/listenKey', ['fapi', 'public'], 'DELETE', {'cost': 1})

    # fapi Private API
    fapi_private_get_v1_positionside_dual = fapiPrivateGetV1PositionSideDual = Entry('v1/positionSide/dual', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v1_multiassetsmargin = fapiPrivateGetV1MultiAssetsMargin = Entry('v1/multiAssetsMargin', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v1_order = fapiPrivateGetV1Order = Entry('v1/order', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v1_openorder = fapiPrivateGetV1OpenOrder = Entry('v1/openOrder', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v1_openorders = fapiPrivateGetV1OpenOrders = Entry('v1/openOrders', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v1_allorders = fapiPrivateGetV1AllOrders = Entry('v1/allOrders', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v2_balance = fapiPrivateGetV2Balance = Entry('v2/balance', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v3_balance = fapiPrivateGetV3Balance = Entry('v3/balance', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v3_account = fapiPrivateGetV3Account = Entry('v3/account', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v4_account = fapiPrivateGetV4Account = Entry('v4/account', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v1_positionmargin_history = fapiPrivateGetV1PositionMarginHistory = Entry('v1/positionMargin/history', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v2_positionrisk = fapiPrivateGetV2PositionRisk = Entry('v2/positionRisk', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v3_positionrisk = fapiPrivateGetV3PositionRisk = Entry('v3/positionRisk', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v1_usertrades = fapiPrivateGetV1UserTrades = Entry('v1/userTrades', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v1_income = fapiPrivateGetV1Income = Entry('v1/income', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v1_leveragebracket = fapiPrivateGetV1LeverageBracket = Entry('v1/leverageBracket', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_get_v1_commissionrate = fapiPrivateGetV1CommissionRate = Entry('v1/commissionRate', ['fapi', 'private'], 'GET', {'cost': 1})
    fapi_private_post_v1_positionside_dual = fapiPrivatePostV1PositionSideDual = Entry('v1/positionSide/dual', ['fapi', 'private'], 'POST', {'cost': 1})
    fapi_private_post_v1_multiassetsmargin = fapiPrivatePostV1MultiAssetsMargin = Entry('v1/multiAssetsMargin', ['fapi', 'private'], 'POST', {'cost': 1})
    fapi_private_post_v1_order = fapiPrivatePostV1Order = Entry('v1/order', ['fapi', 'private'], 'POST', {'cost': 1})
    fapi_private_post_v1_order_test = fapiPrivatePostV1OrderTest = Entry('v1/order/test', ['fapi', 'private'], 'POST', {'cost': 1})
    fapi_private_post_v1_batchorders = fapiPrivatePostV1BatchOrders = Entry('v1/batchOrders', ['fapi', 'private'], 'POST', {'cost': 1})
    fapi_private_post_v1_asset_wallet_transfer = fapiPrivatePostV1AssetWalletTransfer = Entry('v1/asset/wallet/transfer', ['fapi', 'private'], 'POST', {'cost': 1})
    fapi_private_post_v1_countdowncancelall = fapiPrivatePostV1CountdownCancelAll = Entry('v1/countdownCancelAll', ['fapi', 'private'], 'POST', {'cost': 1})
    fapi_private_post_v1_leverage = fapiPrivatePostV1Leverage = Entry('v1/leverage', ['fapi', 'private'], 'POST', {'cost': 1})
    fapi_private_post_v1_margintype = fapiPrivatePostV1MarginType = Entry('v1/marginType', ['fapi', 'private'], 'POST', {'cost': 1})
    fapi_private_post_v1_positionmargin = fapiPrivatePostV1PositionMargin = Entry('v1/positionMargin', ['fapi', 'private'], 'POST', {'cost': 1})
    fapi_private_delete_v1_order = fapiPrivateDeleteV1Order = Entry('v1/order', ['fapi', 'private'], 'DELETE', {'cost': 1})
    fapi_private_delete_v1_allopenorders = fapiPrivateDeleteV1AllOpenOrders = Entry('v1/allOpenOrders', ['fapi', 'private'], 'DELETE', {'cost': 1})
    fapi_private_delete_v1_batchorders = fapiPrivateDeleteV1BatchOrders = Entry('v1/batchOrders', ['fapi', 'private'], 'DELETE', {'cost': 1})

    # sapi Public API
    sapi_public_get_v1_ping = sapiPublicGetV1Ping = Entry('v1/ping', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_time = sapiPublicGetV1Time = Entry('v1/time', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_exchangeinfo = sapiPublicGetV1ExchangeInfo = Entry('v1/exchangeInfo', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_depth = sapiPublicGetV1Depth = Entry('v1/depth', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_trades = sapiPublicGetV1Trades = Entry('v1/trades', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_historicaltrades = sapiPublicGetV1HistoricalTrades = Entry('v1/historicalTrades', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_aggtrades = sapiPublicGetV1AggTrades = Entry('v1/aggTrades', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_klines = sapiPublicGetV1Klines = Entry('v1/klines', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_ticker_24hr = sapiPublicGetV1Ticker24hr = Entry('v1/ticker/24hr', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_ticker_price = sapiPublicGetV1TickerPrice = Entry('v1/ticker/price', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_ticker_bookticker = sapiPublicGetV1TickerBookTicker = Entry('v1/ticker/bookTicker', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_get_v1_aster_withdraw_estimatefee = sapiPublicGetV1AsterWithdrawEstimateFee = Entry('v1/aster/withdraw/estimateFee', ['sapi', 'public'], 'GET', {'cost': 1})
    sapi_public_post_v1_getnonce = sapiPublicPostV1GetNonce = Entry('v1/getNonce', ['sapi', 'public'], 'POST', {'cost': 1})
    sapi_public_post_v1_createapikey = sapiPublicPostV1CreateApiKey = Entry('v1/createApiKey', ['sapi', 'public'], 'POST', {'cost': 1})
    sapi_public_post_v1_listenkey = sapiPublicPostV1ListenKey = Entry('v1/listenKey', ['sapi', 'public'], 'POST', {'cost': 1})
    sapi_public_put_v1_listenkey = sapiPublicPutV1ListenKey = Entry('v1/listenKey', ['sapi', 'public'], 'PUT', {'cost': 1})
    sapi_public_delete_v1_listenkey = sapiPublicDeleteV1ListenKey = Entry('v1/listenKey', ['sapi', 'public'], 'DELETE', {'cost': 1})

    # sapi Private API
    sapi_private_get_v1_commissionrate = sapiPrivateGetV1CommissionRate = Entry('v1/commissionRate', ['sapi', 'private'], 'GET', {'cost': 1})
    sapi_private_get_v1_order = sapiPrivateGetV1Order = Entry('v1/order', ['sapi', 'private'], 'GET', {'cost': 1})
    sapi_private_get_v1_openorders = sapiPrivateGetV1OpenOrders = Entry('v1/openOrders', ['sapi', 'private'], 'GET', {'cost': 1})
    sapi_private_get_v1_allorders = sapiPrivateGetV1AllOrders = Entry('v1/allOrders', ['sapi', 'private'], 'GET', {'cost': 1})
    sapi_private_get_v1_transactionhistory = sapiPrivateGetV1TransactionHistory = Entry('v1/transactionHistory', ['sapi', 'private'], 'GET', {'cost': 1})
    sapi_private_get_v1_account = sapiPrivateGetV1Account = Entry('v1/account', ['sapi', 'private'], 'GET', {'cost': 1})
    sapi_private_get_v1_usertrades = sapiPrivateGetV1UserTrades = Entry('v1/userTrades', ['sapi', 'private'], 'GET', {'cost': 1})
    sapi_private_post_v1_order = sapiPrivatePostV1Order = Entry('v1/order', ['sapi', 'private'], 'POST', {'cost': 1})
    sapi_private_post_v1_asset_wallet_transfer = sapiPrivatePostV1AssetWalletTransfer = Entry('v1/asset/wallet/transfer', ['sapi', 'private'], 'POST', {'cost': 1})
    sapi_private_post_v1_asset_sendtoaddress = sapiPrivatePostV1AssetSendToAddress = Entry('v1/asset/sendToAddress', ['sapi', 'private'], 'POST', {'cost': 1})
    sapi_private_post_v1_aster_user_withdraw = sapiPrivatePostV1AsterUserWithdraw = Entry('v1/aster/user-withdraw', ['sapi', 'private'], 'POST', {'cost': 1})
    sapi_private_delete_v1_order = sapiPrivateDeleteV1Order = Entry('v1/order', ['sapi', 'private'], 'DELETE', {'cost': 1})
    sapi_private_delete_v1_allopenorders = sapiPrivateDeleteV1AllOpenOrders = Entry('v1/allOpenOrders', ['sapi', 'private'], 'DELETE', {'cost': 1})
