from _typeshed import Incomplete
from enum import Enum

class ParserState(Enum):
    INITIALIZED = ...
    START_LINE = ...
    HEADERS = ...
    BODY = ...
    CHUNK_LENGTH = ...
    CHUNK_DATA = ...
    CHUNK_END = ...
    COMPLETE = ...
    ERROR = ...

HTTP_METHODS: Incomplete
DEFAULT_MAX_HEADER_SIZE: int
DEFAULT_MAX_BODY_SIZE: int
DEFAULT_BUFFER_SIZE: int
MAX_REQUEST_LINE_SIZE: int
HTTP_1_0: str
HTTP_1_1: str
CONTENT_LENGTH: str
TRANSFER_ENCODING: str
CONNECTION: str
CONTENT_TYPE: str
HOST: str
USER_AGENT: str
ACCEPT: str
ACCEPT_ENCODING: str
ACCEPT_LANGUAGE: str
COOKIE: str
SET_COOKIE: str
LOCATION: str
AUTHORIZATION: str
CONTENT_TYPE_JSON: str
CONTENT_TYPE_FORM: str
CONTENT_TYPE_MULTIPART: str
CONTENT_TYPE_TEXT: str
CONTENT_TYPE_HTML: str
CONTENT_TYPE_XML: str
CONTENT_TYPE_BINARY: str
CONNECTION_CLOSE: str
CONNECTION_KEEP_ALIVE: str
STATUS_PHRASES: Incomplete
STATUS_LINE_FORMAT: str
STATUS_LINE: Incomplete
DEFAULT_SERVER_HEADER: str
DEFAULT_DATE_FORMAT: str
DEFAULT_HIGH_WATER_MARK: int
DEFAULT_LOW_WATER_MARK: int
