from .config import KeycloakConfig as KeycloakConfig
from .exceptions import KeycloakAdminError as KeycloakAdminError, KeycloakAuthenticationError as KeycloakAuthenticationError, KeycloakConnectionError as KeycloakConnectionError, KeycloakUserNotFoundError as KeycloakUserNotFoundError
from .models import KeycloakClient as KeycloakClient, KeycloakGroup as KeycloakGroup, KeycloakRole as KeycloakRole, KeycloakUser as KeycloakUser
from _typeshed import Incomplete

class KeycloakAdmin:
    config: Incomplete
    http_client: Incomplete
    def __init__(self, config: KeycloakConfig) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> KeycloakAdmin: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def get_admin_token(self) -> str: ...
    async def create_user(self, user: KeycloakUser) -> str: ...
    async def get_user(self, user_id: str) -> KeycloakUser: ...
    async def get_user_by_username(self, username: str) -> KeycloakUser | None: ...
    async def update_user(self, user_id: str, user: KeycloakUser) -> None: ...
    async def delete_user(self, user_id: str) -> None: ...
    async def list_users(self, first: int = 0, max_results: int = 100, search: str | None = None) -> list[KeycloakUser]: ...
    async def reset_user_password(self, user_id: str, password: str, temporary: bool = False) -> None: ...
    async def get_realm_roles(self) -> list[KeycloakRole]: ...
    async def get_user_realm_roles(self, user_id: str) -> list[KeycloakRole]: ...
    async def assign_realm_roles(self, user_id: str, roles: list[KeycloakRole]) -> None: ...
    async def remove_realm_roles(self, user_id: str, roles: list[KeycloakRole]) -> None: ...
    async def get_groups(self) -> list[KeycloakGroup]: ...
    async def get_user_groups(self, user_id: str) -> list[KeycloakGroup]: ...
    async def add_user_to_group(self, user_id: str, group_id: str) -> None: ...
    async def remove_user_from_group(self, user_id: str, group_id: str) -> None: ...
    async def get_clients(self) -> list[KeycloakClient]: ...
    async def get_client_by_client_id(self, client_id: str) -> KeycloakClient | None: ...
