from .jwt import JWTManager as JWTManager
from .tokens import TokenManager as TokenManager
from .user import AnonymousUser as AnonymousUser, User as User
from _typeshed import Incomplete
from zephyr._types import ASGIApp as ASGIApp, Receive as Receive, Scope as Scope, Send as Send

class AuthenticationError(Exception): ...

class AuthenticationBackend:
    async def authenticate(self, token: str) -> User | None: ...
    async def get_user(self, user_id: str) -> User | None: ...

class JWTAuthenticationBackend(AuthenticationBackend):
    jwt_manager: Incomplete
    token_manager: Incomplete
    def __init__(self, jwt_manager: JWTManager, token_manager: TokenManager) -> None: ...
    async def authenticate(self, token: str) -> User | None: ...
    async def get_user(self, user_id: str) -> User | None: ...

class TokenAuthenticationBackend(AuthenticationBackend):
    token_validator: Incomplete
    def __init__(self, token_validator: callable[[str], bool]) -> None: ...
    async def authenticate(self, token: str) -> User | None: ...
    async def get_user(self, user_id: str) -> User | None: ...

class NoAuthenticationBackend(AuthenticationBackend):
    async def authenticate(self, token: str) -> User | None: ...
    async def get_user(self, user_id: str) -> User | None: ...
