from _typeshed import Incomplete

class PasswordError(Exception): ...
class PasswordHashError(PasswordError): ...
class PasswordVerificationError(PasswordError): ...

class PasswordHasher:
    context: Incomplete
    def __init__(self, schemes: list[str] = ['bcrypt'], deprecated: list[str] = []) -> None: ...
    async def hash_password(self, password: str) -> str: ...
    async def verify_password(self, password: str, password_hash: str) -> bool: ...
    async def needs_rehash(self, password_hash: str) -> bool: ...
    async def generate_salt(self, length: int = 32) -> str: ...
    def get_scheme_info(self, password_hash: str) -> dict[str, object]: ...
