from .jwt import JWTError as JWTError, JWTManager as JWTManager
from _typeshed import Incomplete

class TokenError(Exception): ...
class TokenBlacklistError(TokenError): ...
class TokenManagerError(TokenError): ...

class TokenBlacklist:
    backend: Incomplete
    def __init__(self, backend: str = 'memory') -> None: ...
    async def add(self, jti: str, exp: int) -> None: ...
    async def is_blacklisted(self, jti: str) -> bool: ...
    async def cleanup_expired(self) -> int: ...
    async def remove(self, jti: str) -> bool: ...
    async def clear(self) -> int: ...
    async def get_blacklist_size(self) -> int: ...

class TokenManager:
    jwt_manager: Incomplete
    blacklist: Incomplete
    def __init__(self, jwt_manager: JWTManager, blacklist: TokenBlacklist) -> None: ...
    async def revoke_token(self, token: str) -> None: ...
    async def revoke_all_user_tokens(self, user_id: str) -> int: ...
    async def is_revoked(self, token: str) -> bool: ...
    async def cleanup_expired_tokens(self) -> int: ...
