from _typeshed import Incomplete

class User:
    id: Incomplete
    username: Incomplete
    email: Incomplete
    is_active: Incomplete
    is_superuser: Incomplete
    roles: Incomplete
    permissions: Incomplete
    mfa_enabled: Incomplete
    def __init__(self, id: str, username: str, email: str, is_active: bool = True, is_superuser: bool = False, roles: list[str] | None = None, permissions: list[str] | None = None, mfa_enabled: bool = False) -> None: ...
    @property
    def is_authenticated(self) -> bool: ...
    @property
    def is_anonymous(self) -> bool: ...
    async def has_permission(self, permission: str) -> bool: ...
    async def has_role(self, role: str) -> bool: ...
    async def has_any_role(self, roles: list[str]) -> bool: ...
    async def has_all_roles(self, roles: list[str]) -> bool: ...
    async def has_any_permission(self, permissions: list[str]) -> bool: ...
    async def has_all_permissions(self, permissions: list[str]) -> bool: ...
    def to_dict(self) -> dict[str, object]: ...

class AnonymousUser:
    id: Incomplete
    username: Incomplete
    email: Incomplete
    is_active: bool
    is_superuser: bool
    roles: Incomplete
    permissions: Incomplete
    mfa_enabled: bool
    def __init__(self) -> None: ...
    @property
    def is_authenticated(self) -> bool: ...
    @property
    def is_anonymous(self) -> bool: ...
    async def has_permission(self, permission: str) -> bool: ...
    async def has_role(self, role: str) -> bool: ...
    async def has_any_role(self, roles: list[str]) -> bool: ...
    async def has_all_roles(self, roles: list[str]) -> bool: ...
    async def has_any_permission(self, permissions: list[str]) -> bool: ...
    async def has_all_permissions(self, permissions: list[str]) -> bool: ...
    def to_dict(self) -> dict[str, object]: ...
