from typing import Any
from typing import Literal
from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class ValueFormatSchema(BaseModel):
    useGrouping: bool | None = None
    minimumIntegerDigits: int | None = None
    minimumFractionDigits: int | None = None
    maximumFractionDigits: int | None = None
    minimumSignificantDigits: int | None = None
    maximumSignificantDigits: int | None = None
    asBoolean: bool | None = None
    asDate: bool | None = None
    asSlider: bool | None = None
    resolution: Any | None = None
    dateStyle: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    timeStyle: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    dayPeriod: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    hour12: bool | None = None
    iso8601: bool | None = None
    weekday: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    era: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    year: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    month: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    week: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    day: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    hour: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    minute: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    second: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    fractionalSecondDigits: int | None = None
    timeZoneName: Literal['numeric', '2-digit', 'full', 'long', 'medium', 'short', 'narrow'] | None = None
    momentJsFormat: str | None = None
    asNumber: bool | None = None
    asOnOff: bool | None = None
    asPressedReleased: bool | None = None
    asOpenClosed: bool | None = None
    asMomentary: bool | None = None
    multiline: bool | None = None