from enum import Enum


class MessageLogDtoOcppMessageType(str, Enum):
    AUTHORIZE = "Authorize"
    BOOTNOTIFICATION = "BootNotification"
    CANCELRESERVATION = "CancelReservation"
    CHANGEAVAILABILITY = "ChangeAvailability"
    CHANGECONFIGURATION = "ChangeConfiguration"
    CLEARCACHE = "ClearCache"
    CLEARCHARCHINGPROFILE = "ClearCharchingProfile"
    CLEAREDCHARGINGLIMIT = "ClearedChargingLimit"
    DATATRANSFER = "DataTransfer"
    DIAGNOSTICSSTATUSNOTIFICATION = "DiagnosticsStatusNotification"
    FIRMWARESTATUSNOTIFICATION = "FirmwareStatusNotification"
    GETCOMPOSITESCHEDULE = "GetCompositeSchedule"
    GETCONFIGURATION = "GetConfiguration"
    GETDIAGNOSTICS = "GetDiagnostics"
    GETLOCALLIST = "GetLocalList"
    HEARTBEAT = "Heartbeat"
    LOGSTATUSNOTIFICATION = "LogStatusNotification"
    METERVALUES = "MeterValues"
    NOTIFYCHARGINGLIMIT = "NotifyChargingLimit"
    NOTIFYCUSTOMERINFORMATION = "NotifyCustomerInformation"
    NOTIFYDISPLAYMESSAGES = "NotifyDisplayMessages"
    NOTIFYEVENT = "NotifyEvent"
    NOTIFYMONITORINGREPORT = "NotifyMonitoringReport"
    NOTIFYREPORT = "NotifyReport"
    PUBLISHFIRMWARESTATUSNOTIFICATION = "PublishFirmwareStatusNotification"
    REMOTESTARTTRANSACTION = "RemoteStartTransaction"
    REMOTESTOPTRANSACTION = "RemoteStopTransaction"
    REPORTCHARGINGPROFILES = "ReportChargingProfiles"
    RESERVATIONSTATUSUPDATE = "ReservationStatusUpdate"
    RESERVENOW = "ReserveNow"
    RESET = "Reset"
    SECURITYEVENTNOTIFICATION = "SecurityEventNotification"
    SENDLOCALLIST = "SendLocalList"
    SETCHARGINGPROFILE = "SetChargingProfile"
    SETVARIABLES = "SetVariables"
    STARTTRANSACTION = "StartTransaction"
    STATUSNOTIFICATION = "StatusNotification"
    STOPTRANSACTION = "StopTransaction"
    TRANSACTIONEVENT = "TransactionEvent"
    TRIGGERMESSAGE = "TriggerMessage"
    UNLOCKCONNECTOR = "UnlockConnector"
    UPDATEFIRMWARE = "UpdateFirmware"

    def __str__(self) -> str:
        return str(self.value)
