import abc
from ....net.connection import Connection as Connection
from ....net.unreader import UnReader as UnReader
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from typing import Protocol
from zephyr.core.zserver.protocol.http.constants import ParserState as ParserState

class ParserCallback(Protocol):
    def on_message_begin(self) -> None: ...
    def on_url(self, url: bytes) -> None: ...
    def on_header(self, name: str, value: str) -> None: ...
    def on_headers_complete(self) -> None: ...
    def on_body(self, data: bytes) -> None: ...
    def on_message_complete(self) -> None: ...
    def on_error(self, error: str) -> None: ...

class BaseParser(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def feed_data(self, data: bytes) -> None: ...
    @abstractmethod
    def reset(self) -> None: ...
    @abstractmethod
    def error(self) -> str | None: ...
    @abstractmethod
    def is_error(self) -> bool: ...
    @abstractmethod
    def is_complete(self) -> bool: ...

class BaseHTTPParser(ABC, metaclass=abc.ABCMeta):
    callback: Incomplete
    connection: Incomplete
    state: Incomplete
    unreader: Incomplete
    def __init__(self, callback: ParserCallback | None = None, connection: Connection | None = None) -> None: ...
    @abstractmethod
    def feed_data(self, data: bytes) -> None: ...
    @abstractmethod
    def reset(self) -> None: ...
    @property
    def error(self) -> str | None: ...
    @property
    def is_error(self) -> bool: ...
    @property
    def is_complete(self) -> bool: ...
