import asyncio
from zephyr._types import WWWScope as WWWScope

def get_remote_addr(transport: asyncio.Transport) -> tuple[str, int] | None: ...
def get_local_addr(transport: asyncio.Transport) -> tuple[str, int] | None: ...
def format_http_date(timestamp: float) -> str: ...
def parse_headers(header_lines: list[str]) -> dict[str, str]: ...
def get_content_type(headers: dict[str, str]) -> tuple[str, dict[str, str]]: ...
def is_chunked(headers: dict[str, str]) -> bool: ...
def is_connection_keep_alive(headers: dict[str, str], http_version: str) -> bool: ...
def get_hostname_and_port(host_header: str, is_secure: bool = False) -> tuple[str, int]: ...
def get_socket_options(backlog: int = 128) -> list[tuple[int, int, int]]: ...
def get_client_addr(scope: WWWScope) -> str: ...
def get_path_with_query_string(scope: WWWScope) -> str: ...
