from dataclasses import dataclass, field
from typing import Any, Callable, Sequence
from zephyr.app._compat import ModelField as ModelField
from zephyr.app.security.base import SecurityBase as SecurityBase

@dataclass
class SecurityRequirement:
    security_scheme: SecurityBase
    scopes: Sequence[str] | None = ...

@dataclass
class Dependant:
    path_params: list[ModelField] = field(default_factory=list)
    query_params: list[ModelField] = field(default_factory=list)
    header_params: list[ModelField] = field(default_factory=list)
    cookie_params: list[ModelField] = field(default_factory=list)
    body_params: list[ModelField] = field(default_factory=list)
    dependencies: list['Dependant'] = field(default_factory=list)
    security_requirements: list[SecurityRequirement] = field(default_factory=list)
    name: str | None = ...
    call: Callable[..., Any] | None = ...
    request_param_name: str | None = ...
    websocket_param_name: str | None = ...
    http_connection_param_name: str | None = ...
    response_param_name: str | None = ...
    background_tasks_param_name: str | None = ...
    security_scopes_param_name: str | None = ...
    security_scopes: list[str] | None = ...
    use_cache: bool = ...
    path: str | None = ...
    cache_key: tuple[Callable[..., Any] | None, tuple[str, ...]] = field(init=False)
    def __post_init__(self) -> None: ...
