from .exceptions import AccessControlError as AccessControlError, PolicyEvaluationError as PolicyEvaluationError, RBACError as RBACError
from .models import AccessContext as AccessContext, AccessDecision as AccessDecision, Effect as Effect, Policy as Policy, PolicyRule as PolicyRule, Role as Role
from _typeshed import Incomplete
from typing import Any

class PolicyEngine:
    policies: dict[str, Policy]
    conditions: dict[str, Any]
    def __init__(self) -> None: ...
    def add_policy(self, policy: Policy) -> None: ...
    def remove_policy(self, policy_name: str) -> bool: ...
    def get_policy(self, policy_name: str) -> Policy | None: ...
    def evaluate_policy(self, policy: Policy, context: AccessContext) -> list[PolicyRule]: ...

class RBACEngine:
    roles: dict[str, Role]
    permissions: dict[str, Any]
    user_roles: dict[str, set[str]]
    def __init__(self) -> None: ...
    def add_role(self, role: Role) -> None: ...
    def remove_role(self, role_name: str) -> bool: ...
    def get_role(self, role_name: str) -> Role | None: ...
    def assign_role(self, user_id: str, role_name: str) -> None: ...
    def revoke_role(self, user_id: str, role_name: str) -> None: ...
    def get_user_roles(self, user_id: str) -> set[str]: ...
    def has_role(self, user_id: str, role_name: str) -> bool: ...
    def has_permission(self, user_id: str, permission: str) -> bool: ...
    def get_user_permissions(self, user_id: str) -> set[str]: ...

class AccessControlEngine:
    policy_engine: Incomplete
    rbac_engine: Incomplete
    def __init__(self) -> None: ...
    def add_policy(self, policy: Policy) -> None: ...
    def add_role(self, role: Role) -> None: ...
    def assign_role(self, user_id: str, role_name: str) -> None: ...
    def revoke_role(self, user_id: str, role_name: str) -> None: ...
    def check_access(self, context: AccessContext) -> AccessDecision: ...
    def is_allowed(self, user_id: str, resource: str, action: str, **kwargs: Any) -> bool: ...
    def get_user_permissions(self, user_id: str) -> set[str]: ...
    def get_user_roles(self, user_id: str) -> set[str]: ...
