from _typeshed import Incomplete
from typing import Any

class RBACError(Exception):
    message: Incomplete
    error_code: Incomplete
    resource: Incomplete
    action: Incomplete
    extra: Incomplete
    def __init__(self, message: str, error_code: str | None = None, resource: str | None = None, action: str | None = None, **kwargs: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class RoleNotFoundError(RBACError):
    def __init__(self, role_name: str, **kwargs: Any) -> None: ...

class PermissionNotFoundError(RBACError):
    def __init__(self, permission_name: str, **kwargs: Any) -> None: ...

class PolicyNotFoundError(RBACError):
    def __init__(self, policy_name: str, **kwargs: Any) -> None: ...

class AccessDeniedError(RBACError):
    def __init__(self, message: str = 'Access denied', resource: str | None = None, action: str | None = None, user_id: str | None = None, **kwargs: Any) -> None: ...

class InvalidPolicyError(RBACError):
    def __init__(self, message: str, policy_name: str | None = None, **kwargs: Any) -> None: ...

class InvalidRoleError(RBACError):
    def __init__(self, message: str, role_name: str | None = None, **kwargs: Any) -> None: ...

class InvalidPermissionError(RBACError):
    def __init__(self, message: str, permission_name: str | None = None, **kwargs: Any) -> None: ...

class PolicyEvaluationError(RBACError):
    def __init__(self, message: str, policy_name: str | None = None, condition: str | None = None, **kwargs: Any) -> None: ...

class AccessControlError(RBACError):
    def __init__(self, message: str, resource: str | None = None, action: str | None = None, **kwargs: Any) -> None: ...

class CircularDependencyError(RBACError):
    def __init__(self, message: str, dependency_chain: list[str] | None = None, **kwargs: Any) -> None: ...

class InvalidResourceError(RBACError):
    def __init__(self, message: str, resource_name: str | None = None, **kwargs: Any) -> None: ...

class InvalidActionError(RBACError):
    def __init__(self, message: str, action_name: str | None = None, **kwargs: Any) -> None: ...

class PolicyConflictError(RBACError):
    def __init__(self, message: str, conflicting_policies: list[str] | None = None, **kwargs: Any) -> None: ...

class RoleHierarchyError(RBACError):
    def __init__(self, message: str, parent_role: str | None = None, child_role: str | None = None, **kwargs: Any) -> None: ...

class PermissionAssignmentError(RBACError):
    def __init__(self, message: str, role_name: str | None = None, permission_name: str | None = None, **kwargs: Any) -> None: ...

class PolicyRuleError(RBACError):
    def __init__(self, message: str, rule_id: str | None = None, **kwargs: Any) -> None: ...

class ConditionEvaluationError(RBACError):
    def __init__(self, message: str, condition: str | None = None, **kwargs: Any) -> None: ...

class AccessDecisionError(RBACError):
    def __init__(self, message: str, decision: str | None = None, **kwargs: Any) -> None: ...

class RBACConfigurationError(RBACError):
    def __init__(self, message: str, config_key: str | None = None, **kwargs: Any) -> None: ...

class PolicyVersionError(RBACError):
    def __init__(self, message: str, policy_name: str | None = None, version: str | None = None, **kwargs: Any) -> None: ...

class RoleAssignmentError(RBACError):
    def __init__(self, message: str, user_id: str | None = None, role_name: str | None = None, **kwargs: Any) -> None: ...

class PermissionInheritanceError(RBACError):
    def __init__(self, message: str, parent_role: str | None = None, child_role: str | None = None, **kwargs: Any) -> None: ...

class PolicyCacheError(RBACError):
    def __init__(self, message: str, cache_key: str | None = None, **kwargs: Any) -> None: ...

class AccessAuditError(RBACError):
    def __init__(self, message: str, audit_id: str | None = None, **kwargs: Any) -> None: ...
