# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**  1) Login using `/api/v1/auth/login`   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: `Bearer <your token>`   5) Click \"Authorize\"   6) All requests are now authorized.  **Token valid for 2 hours. If expired:**   - Login again, click \"Authorize\", paste new token.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assurance_topology_inventory_post200_response import V2AssuranceTopologyInventoryPost200Response

class TestV2AssuranceTopologyInventoryPost200Response(unittest.TestCase):
    """V2AssuranceTopologyInventoryPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssuranceTopologyInventoryPost200Response:
        """Test V2AssuranceTopologyInventoryPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssuranceTopologyInventoryPost200Response`
        """
        model = V2AssuranceTopologyInventoryPost200Response()
        if include_optional:
            return V2AssuranceTopologyInventoryPost200Response(
                app_names = [
                    'example string'
                    ],
                client_sites = [
                    graphiant_sdk.models._v2_assurance_flow_summary_post_200_response_client_endpoint_site._v2_assurance_flow_summary_post_200_response_clientEndpoint_site(
                        region_id = 123, 
                        site_id = 1234567891011, 
                        site_name = 'example string', )
                    ],
                regions = [
                    graphiant_sdk.models._v2_assurance_topology_inventory_post_200_response_regions_inner._v2_assurance_topology_inventory_post_200_response_regions_inner(
                        region_id = 123, 
                        region_name = 'example string', )
                    ],
                server_sites = [
                    graphiant_sdk.models._v2_assurance_flow_summary_post_200_response_client_endpoint_site._v2_assurance_flow_summary_post_200_response_clientEndpoint_site(
                        region_id = 123, 
                        site_id = 1234567891011, 
                        site_name = 'example string', )
                    ],
                topology_change_ts = [
                    graphiant_sdk.models._v1_alarm_history_get_200_response_history_inner_time._v1_alarm_history_get_200_response_history_inner_time(
                        nanos = 123, 
                        seconds = 1234567891011, )
                    ]
            )
        else:
            return V2AssuranceTopologyInventoryPost200Response(
        )
        """

    def testV2AssuranceTopologyInventoryPost200Response(self):
        """Test V2AssuranceTopologyInventoryPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
