# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**  1) Login using `/api/v1/auth/login`   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: `Bearer <your token>`   5) Click \"Authorize\"   6) All requests are now authorized.  **Token valid for 2 hours. If expired:**   - Login again, click \"Authorize\", paste new token.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranets_b2b_id_customer_summary_get200_response_customers_inner import V1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner

class TestV1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner(unittest.TestCase):
    """V1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner:
        """Test V1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner`
        """
        model = V1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner()
        if include_optional:
            return V1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner(
                admin_email = 'example string',
                enterprise_id = 1234567891011,
                id = 1234567891011,
                name = 'example string',
                status = 'ENUM_VALUE',
                updated_at = graphiant_sdk.models._v1_alarm_history_get_200_response_history_inner_time._v1_alarm_history_get_200_response_history_inner_time(
                    nanos = 123, 
                    seconds = 1234567891011, )
            )
        else:
            return V1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner(
        )
        """

    def testV1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner(self):
        """Test V1ExtranetsB2bIdCustomerSummaryGet200ResponseCustomersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
