# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**  1) Login using `/api/v1/auth/login`   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: `Bearer <your token>`   5) Click \"Authorize\"   6) All requests are now authorized.  **Token valid for 2 hours. If expired:**   - Login again, click \"Authorize\", paste new token.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_device_routing_ospfv2_area_lsdb_get200_response_lsas_inner_summary_lsa import V1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa

class TestV1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa(unittest.TestCase):
    """V1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa:
        """Test V1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa`
        """
        model = V1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa()
        if include_optional:
            return V1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa(
                network_mask = 123,
                tos_metric = graphiant_sdk.models._v1_device_routing_ospfv2_area_lsdb_get_200_response_lsas_inner_asexternal_lsa_tos_metric._v1_device_routing_ospfv2_area_lsdb_get_200_response_lsas_inner_asexternalLsa_tosMetric(
                    tos = 123, )
            )
        else:
            return V1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa(
        )
        """

    def testV1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa(self):
        """Test V1DeviceRoutingOspfv2AreaLsdbGet200ResponseLsasInnerSummaryLsa"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
