# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**  1) Login using `/api/v1/auth/login`   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: `Bearer <your token>`   5) Click \"Authorize\"   6) All requests are now authorized.  **Token valid for 2 hours. If expired:**   - Login again, click \"Authorize\", paste new token.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_monitoring_segment_route_counts_post200_response_data_inner import V2MonitoringSegmentRouteCountsPost200ResponseDataInner

class TestV2MonitoringSegmentRouteCountsPost200ResponseDataInner(unittest.TestCase):
    """V2MonitoringSegmentRouteCountsPost200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2MonitoringSegmentRouteCountsPost200ResponseDataInner:
        """Test V2MonitoringSegmentRouteCountsPost200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2MonitoringSegmentRouteCountsPost200ResponseDataInner`
        """
        model = V2MonitoringSegmentRouteCountsPost200ResponseDataInner()
        if include_optional:
            return V2MonitoringSegmentRouteCountsPost200ResponseDataInner(
                device_id = 12345678910,
                ipv4_route_count = graphiant_sdk.models._v2_monitoring_bfd_post_200_response_data_inner_samples_inner._v2_monitoring_bfd_post_200_response_data_inner_samples_inner(
                    status = 'ENUM_VALUE', 
                    ts = graphiant_sdk.models._v1_alarm_history_get_200_response_history_inner_time._v1_alarm_history_get_200_response_history_inner_time(
                        nanos = 123, 
                        seconds = 1234567891011, ), 
                    value = 123.45, ),
                ipv6_route_count = graphiant_sdk.models._v2_monitoring_bfd_post_200_response_data_inner_samples_inner._v2_monitoring_bfd_post_200_response_data_inner_samples_inner(
                    status = 'ENUM_VALUE', 
                    ts = graphiant_sdk.models._v1_alarm_history_get_200_response_history_inner_time._v1_alarm_history_get_200_response_history_inner_time(
                        nanos = 123, 
                        seconds = 1234567891011, ), 
                    value = 123.45, ),
                segment_name = 'example string'
            )
        else:
            return V2MonitoringSegmentRouteCountsPost200ResponseDataInner(
        )
        """

    def testV2MonitoringSegmentRouteCountsPost200ResponseDataInner(self):
        """Test V2MonitoringSegmentRouteCountsPost200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
