# coding: utf-8

"""
    Graphiant APIs

    **To use the APIs:**  1) Login using `/api/v1/auth/login`   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: `Bearer <your token>`   5) Click \"Authorize\"   6) All requests are now authorized.  **Token valid for 2 hours. If expired:**   - Login again, click \"Authorize\", paste new token.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_bwtracker_region_edge_summary_post200_response_bwusage_summary_bwusage_top_sites_inner import V1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner

class TestV1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner(unittest.TestCase):
    """V1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner:
        """Test V1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner`
        """
        model = V1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner()
        if include_optional:
            return V1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner(
                site_id = 12345678910,
                site_name = 'example string',
                usage_kbps = 123.45
            )
        else:
            return V1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner(
        )
        """

    def testV1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner(self):
        """Test V1BwtrackerRegionEdgeSummaryPost200ResponseBwusageSummaryBwusageTopSitesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
