import pytest

from entitysdk.models import (
    AnalysisNotebookEnvironment,
    AnalysisNotebookExecution,
    AnalysisNotebookResult,
    AnalysisNotebookTemplate,
    CellMorphology,
    CellMorphologyProtocol,
    Contribution,
    ElectricalCellRecording,
    EModel,
    IonChannel,
    IonChannelModel,
    IonChannelModelingCampaign,
    IonChannelModelingConfig,
    IonChannelModelingConfigGeneration,
    IonChannelModelingExecution,
    IonChannelRecording,
    License,
    MEModel,
    MEModelCalibrationResult,
    MTypeClass,
    Organization,
    Person,
    Role,
    SingleNeuronSimulation,
    SingleNeuronSynaptome,
    SingleNeuronSynaptomeSimulation,
    SkeletonizationCampaign,
    SkeletonizationConfig,
    SkeletonizationConfigGeneration,
    SkeletonizationExecution,
    Species,
    Strain,
    ValidationResult,
)


@pytest.mark.parametrize(
    "entity_type",
    [
        AnalysisNotebookEnvironment,
        AnalysisNotebookExecution,
        AnalysisNotebookResult,
        AnalysisNotebookTemplate,
        CellMorphology,
        CellMorphologyProtocol,
        Contribution,
        IonChannel,
        IonChannelModel,
        IonChannelModelingCampaign,
        IonChannelModelingConfig,
        IonChannelModelingConfigGeneration,
        IonChannelModelingExecution,
        IonChannelRecording,
        License,
        MTypeClass,
        Person,
        Role,
        Species,
        Strain,
        Organization,
        EModel,
        MEModel,
        ElectricalCellRecording,
        ValidationResult,
        MEModelCalibrationResult,
        SingleNeuronSimulation,
        SingleNeuronSynaptomeSimulation,
        SingleNeuronSynaptome,
        SkeletonizationCampaign,
        SkeletonizationConfig,
        SkeletonizationConfigGeneration,
        SkeletonizationExecution,
    ],
)
def test_is_searchable(entity_type, client):
    res = client.search_entity(entity_type=entity_type, limit=1).one()
    assert res.id
