# This file is generated, do not edit
from typing import Type

from libevdev import device
from libevdev import event
from libevdev import const

Device: Type[device.Device]
InputAbsInfo: Type[device.InputAbsInfo]
InvalidFileError: Type[device.InvalidFileError]
EventsDroppedException: Type[device.EventsDroppedException]
InvalidArgumentException: Type[device.InvalidArgumentException]
InputEvent: Type[event.InputEvent]
EventType: Type[const.EventType]
EventCode: Type[const.EventCode]
InputProperty: Type[const.InputProperty]

def evbit(
    evtype: int | str, evcode: int | str | None = None
) -> const.EventCode | const.EventType | None: ...
def propbit(prop: int | str) -> const.InputProperty | None: ...

class _EV_SYN(const.EventType):
    @property
    def SYN_REPORT(self) -> const.EventCode: ...
    @property
    def SYN_CONFIG(self) -> const.EventCode: ...
    @property
    def SYN_MT_REPORT(self) -> const.EventCode: ...
    @property
    def SYN_DROPPED(self) -> const.EventCode: ...
    @property
    def SYN_MAX(self) -> const.EventCode: ...

class _EV_KEY(const.EventType):
    @property
    def KEY_RESERVED(self) -> const.EventCode: ...
    @property
    def KEY_ESC(self) -> const.EventCode: ...
    @property
    def KEY_1(self) -> const.EventCode: ...
    @property
    def KEY_2(self) -> const.EventCode: ...
    @property
    def KEY_3(self) -> const.EventCode: ...
    @property
    def KEY_4(self) -> const.EventCode: ...
    @property
    def KEY_5(self) -> const.EventCode: ...
    @property
    def KEY_6(self) -> const.EventCode: ...
    @property
    def KEY_7(self) -> const.EventCode: ...
    @property
    def KEY_8(self) -> const.EventCode: ...
    @property
    def KEY_9(self) -> const.EventCode: ...
    @property
    def KEY_0(self) -> const.EventCode: ...
    @property
    def KEY_MINUS(self) -> const.EventCode: ...
    @property
    def KEY_EQUAL(self) -> const.EventCode: ...
    @property
    def KEY_BACKSPACE(self) -> const.EventCode: ...
    @property
    def KEY_TAB(self) -> const.EventCode: ...
    @property
    def KEY_Q(self) -> const.EventCode: ...
    @property
    def KEY_W(self) -> const.EventCode: ...
    @property
    def KEY_E(self) -> const.EventCode: ...
    @property
    def KEY_R(self) -> const.EventCode: ...
    @property
    def KEY_T(self) -> const.EventCode: ...
    @property
    def KEY_Y(self) -> const.EventCode: ...
    @property
    def KEY_U(self) -> const.EventCode: ...
    @property
    def KEY_I(self) -> const.EventCode: ...
    @property
    def KEY_O(self) -> const.EventCode: ...
    @property
    def KEY_P(self) -> const.EventCode: ...
    @property
    def KEY_LEFTBRACE(self) -> const.EventCode: ...
    @property
    def KEY_RIGHTBRACE(self) -> const.EventCode: ...
    @property
    def KEY_ENTER(self) -> const.EventCode: ...
    @property
    def KEY_LEFTCTRL(self) -> const.EventCode: ...
    @property
    def KEY_A(self) -> const.EventCode: ...
    @property
    def KEY_S(self) -> const.EventCode: ...
    @property
    def KEY_D(self) -> const.EventCode: ...
    @property
    def KEY_F(self) -> const.EventCode: ...
    @property
    def KEY_G(self) -> const.EventCode: ...
    @property
    def KEY_H(self) -> const.EventCode: ...
    @property
    def KEY_J(self) -> const.EventCode: ...
    @property
    def KEY_K(self) -> const.EventCode: ...
    @property
    def KEY_L(self) -> const.EventCode: ...
    @property
    def KEY_SEMICOLON(self) -> const.EventCode: ...
    @property
    def KEY_APOSTROPHE(self) -> const.EventCode: ...
    @property
    def KEY_GRAVE(self) -> const.EventCode: ...
    @property
    def KEY_LEFTSHIFT(self) -> const.EventCode: ...
    @property
    def KEY_BACKSLASH(self) -> const.EventCode: ...
    @property
    def KEY_Z(self) -> const.EventCode: ...
    @property
    def KEY_X(self) -> const.EventCode: ...
    @property
    def KEY_C(self) -> const.EventCode: ...
    @property
    def KEY_V(self) -> const.EventCode: ...
    @property
    def KEY_B(self) -> const.EventCode: ...
    @property
    def KEY_N(self) -> const.EventCode: ...
    @property
    def KEY_M(self) -> const.EventCode: ...
    @property
    def KEY_COMMA(self) -> const.EventCode: ...
    @property
    def KEY_DOT(self) -> const.EventCode: ...
    @property
    def KEY_SLASH(self) -> const.EventCode: ...
    @property
    def KEY_RIGHTSHIFT(self) -> const.EventCode: ...
    @property
    def KEY_KPASTERISK(self) -> const.EventCode: ...
    @property
    def KEY_LEFTALT(self) -> const.EventCode: ...
    @property
    def KEY_SPACE(self) -> const.EventCode: ...
    @property
    def KEY_CAPSLOCK(self) -> const.EventCode: ...
    @property
    def KEY_F1(self) -> const.EventCode: ...
    @property
    def KEY_F2(self) -> const.EventCode: ...
    @property
    def KEY_F3(self) -> const.EventCode: ...
    @property
    def KEY_F4(self) -> const.EventCode: ...
    @property
    def KEY_F5(self) -> const.EventCode: ...
    @property
    def KEY_F6(self) -> const.EventCode: ...
    @property
    def KEY_F7(self) -> const.EventCode: ...
    @property
    def KEY_F8(self) -> const.EventCode: ...
    @property
    def KEY_F9(self) -> const.EventCode: ...
    @property
    def KEY_F10(self) -> const.EventCode: ...
    @property
    def KEY_NUMLOCK(self) -> const.EventCode: ...
    @property
    def KEY_SCROLLLOCK(self) -> const.EventCode: ...
    @property
    def KEY_KP7(self) -> const.EventCode: ...
    @property
    def KEY_KP8(self) -> const.EventCode: ...
    @property
    def KEY_KP9(self) -> const.EventCode: ...
    @property
    def KEY_KPMINUS(self) -> const.EventCode: ...
    @property
    def KEY_KP4(self) -> const.EventCode: ...
    @property
    def KEY_KP5(self) -> const.EventCode: ...
    @property
    def KEY_KP6(self) -> const.EventCode: ...
    @property
    def KEY_KPPLUS(self) -> const.EventCode: ...
    @property
    def KEY_KP1(self) -> const.EventCode: ...
    @property
    def KEY_KP2(self) -> const.EventCode: ...
    @property
    def KEY_KP3(self) -> const.EventCode: ...
    @property
    def KEY_KP0(self) -> const.EventCode: ...
    @property
    def KEY_KPDOT(self) -> const.EventCode: ...
    @property
    def KEY_ZENKAKUHANKAKU(self) -> const.EventCode: ...
    @property
    def KEY_102ND(self) -> const.EventCode: ...
    @property
    def KEY_F11(self) -> const.EventCode: ...
    @property
    def KEY_F12(self) -> const.EventCode: ...
    @property
    def KEY_RO(self) -> const.EventCode: ...
    @property
    def KEY_KATAKANA(self) -> const.EventCode: ...
    @property
    def KEY_HIRAGANA(self) -> const.EventCode: ...
    @property
    def KEY_HENKAN(self) -> const.EventCode: ...
    @property
    def KEY_KATAKANAHIRAGANA(self) -> const.EventCode: ...
    @property
    def KEY_MUHENKAN(self) -> const.EventCode: ...
    @property
    def KEY_KPJPCOMMA(self) -> const.EventCode: ...
    @property
    def KEY_KPENTER(self) -> const.EventCode: ...
    @property
    def KEY_RIGHTCTRL(self) -> const.EventCode: ...
    @property
    def KEY_KPSLASH(self) -> const.EventCode: ...
    @property
    def KEY_SYSRQ(self) -> const.EventCode: ...
    @property
    def KEY_RIGHTALT(self) -> const.EventCode: ...
    @property
    def KEY_LINEFEED(self) -> const.EventCode: ...
    @property
    def KEY_HOME(self) -> const.EventCode: ...
    @property
    def KEY_UP(self) -> const.EventCode: ...
    @property
    def KEY_PAGEUP(self) -> const.EventCode: ...
    @property
    def KEY_LEFT(self) -> const.EventCode: ...
    @property
    def KEY_RIGHT(self) -> const.EventCode: ...
    @property
    def KEY_END(self) -> const.EventCode: ...
    @property
    def KEY_DOWN(self) -> const.EventCode: ...
    @property
    def KEY_PAGEDOWN(self) -> const.EventCode: ...
    @property
    def KEY_INSERT(self) -> const.EventCode: ...
    @property
    def KEY_DELETE(self) -> const.EventCode: ...
    @property
    def KEY_MACRO(self) -> const.EventCode: ...
    @property
    def KEY_MUTE(self) -> const.EventCode: ...
    @property
    def KEY_VOLUMEDOWN(self) -> const.EventCode: ...
    @property
    def KEY_VOLUMEUP(self) -> const.EventCode: ...
    @property
    def KEY_POWER(self) -> const.EventCode: ...
    @property
    def KEY_KPEQUAL(self) -> const.EventCode: ...
    @property
    def KEY_KPPLUSMINUS(self) -> const.EventCode: ...
    @property
    def KEY_PAUSE(self) -> const.EventCode: ...
    @property
    def KEY_SCALE(self) -> const.EventCode: ...
    @property
    def KEY_KPCOMMA(self) -> const.EventCode: ...
    @property
    def KEY_HANGEUL(self) -> const.EventCode: ...
    @property
    def KEY_HANJA(self) -> const.EventCode: ...
    @property
    def KEY_YEN(self) -> const.EventCode: ...
    @property
    def KEY_LEFTMETA(self) -> const.EventCode: ...
    @property
    def KEY_RIGHTMETA(self) -> const.EventCode: ...
    @property
    def KEY_COMPOSE(self) -> const.EventCode: ...
    @property
    def KEY_STOP(self) -> const.EventCode: ...
    @property
    def KEY_AGAIN(self) -> const.EventCode: ...
    @property
    def KEY_PROPS(self) -> const.EventCode: ...
    @property
    def KEY_UNDO(self) -> const.EventCode: ...
    @property
    def KEY_FRONT(self) -> const.EventCode: ...
    @property
    def KEY_COPY(self) -> const.EventCode: ...
    @property
    def KEY_OPEN(self) -> const.EventCode: ...
    @property
    def KEY_PASTE(self) -> const.EventCode: ...
    @property
    def KEY_FIND(self) -> const.EventCode: ...
    @property
    def KEY_CUT(self) -> const.EventCode: ...
    @property
    def KEY_HELP(self) -> const.EventCode: ...
    @property
    def KEY_MENU(self) -> const.EventCode: ...
    @property
    def KEY_CALC(self) -> const.EventCode: ...
    @property
    def KEY_SETUP(self) -> const.EventCode: ...
    @property
    def KEY_SLEEP(self) -> const.EventCode: ...
    @property
    def KEY_WAKEUP(self) -> const.EventCode: ...
    @property
    def KEY_FILE(self) -> const.EventCode: ...
    @property
    def KEY_SENDFILE(self) -> const.EventCode: ...
    @property
    def KEY_DELETEFILE(self) -> const.EventCode: ...
    @property
    def KEY_XFER(self) -> const.EventCode: ...
    @property
    def KEY_PROG1(self) -> const.EventCode: ...
    @property
    def KEY_PROG2(self) -> const.EventCode: ...
    @property
    def KEY_WWW(self) -> const.EventCode: ...
    @property
    def KEY_MSDOS(self) -> const.EventCode: ...
    @property
    def KEY_COFFEE(self) -> const.EventCode: ...
    @property
    def KEY_ROTATE_DISPLAY(self) -> const.EventCode: ...
    @property
    def KEY_CYCLEWINDOWS(self) -> const.EventCode: ...
    @property
    def KEY_MAIL(self) -> const.EventCode: ...
    @property
    def KEY_BOOKMARKS(self) -> const.EventCode: ...
    @property
    def KEY_COMPUTER(self) -> const.EventCode: ...
    @property
    def KEY_BACK(self) -> const.EventCode: ...
    @property
    def KEY_FORWARD(self) -> const.EventCode: ...
    @property
    def KEY_CLOSECD(self) -> const.EventCode: ...
    @property
    def KEY_EJECTCD(self) -> const.EventCode: ...
    @property
    def KEY_EJECTCLOSECD(self) -> const.EventCode: ...
    @property
    def KEY_NEXTSONG(self) -> const.EventCode: ...
    @property
    def KEY_PLAYPAUSE(self) -> const.EventCode: ...
    @property
    def KEY_PREVIOUSSONG(self) -> const.EventCode: ...
    @property
    def KEY_STOPCD(self) -> const.EventCode: ...
    @property
    def KEY_RECORD(self) -> const.EventCode: ...
    @property
    def KEY_REWIND(self) -> const.EventCode: ...
    @property
    def KEY_PHONE(self) -> const.EventCode: ...
    @property
    def KEY_ISO(self) -> const.EventCode: ...
    @property
    def KEY_CONFIG(self) -> const.EventCode: ...
    @property
    def KEY_HOMEPAGE(self) -> const.EventCode: ...
    @property
    def KEY_REFRESH(self) -> const.EventCode: ...
    @property
    def KEY_EXIT(self) -> const.EventCode: ...
    @property
    def KEY_MOVE(self) -> const.EventCode: ...
    @property
    def KEY_EDIT(self) -> const.EventCode: ...
    @property
    def KEY_SCROLLUP(self) -> const.EventCode: ...
    @property
    def KEY_SCROLLDOWN(self) -> const.EventCode: ...
    @property
    def KEY_KPLEFTPAREN(self) -> const.EventCode: ...
    @property
    def KEY_KPRIGHTPAREN(self) -> const.EventCode: ...
    @property
    def KEY_NEW(self) -> const.EventCode: ...
    @property
    def KEY_REDO(self) -> const.EventCode: ...
    @property
    def KEY_F13(self) -> const.EventCode: ...
    @property
    def KEY_F14(self) -> const.EventCode: ...
    @property
    def KEY_F15(self) -> const.EventCode: ...
    @property
    def KEY_F16(self) -> const.EventCode: ...
    @property
    def KEY_F17(self) -> const.EventCode: ...
    @property
    def KEY_F18(self) -> const.EventCode: ...
    @property
    def KEY_F19(self) -> const.EventCode: ...
    @property
    def KEY_F20(self) -> const.EventCode: ...
    @property
    def KEY_F21(self) -> const.EventCode: ...
    @property
    def KEY_F22(self) -> const.EventCode: ...
    @property
    def KEY_F23(self) -> const.EventCode: ...
    @property
    def KEY_F24(self) -> const.EventCode: ...
    @property
    def KEY_PLAYCD(self) -> const.EventCode: ...
    @property
    def KEY_PAUSECD(self) -> const.EventCode: ...
    @property
    def KEY_PROG3(self) -> const.EventCode: ...
    @property
    def KEY_PROG4(self) -> const.EventCode: ...
    @property
    def KEY_ALL_APPLICATIONS(self) -> const.EventCode: ...
    @property
    def KEY_SUSPEND(self) -> const.EventCode: ...
    @property
    def KEY_CLOSE(self) -> const.EventCode: ...
    @property
    def KEY_PLAY(self) -> const.EventCode: ...
    @property
    def KEY_FASTFORWARD(self) -> const.EventCode: ...
    @property
    def KEY_BASSBOOST(self) -> const.EventCode: ...
    @property
    def KEY_PRINT(self) -> const.EventCode: ...
    @property
    def KEY_HP(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA(self) -> const.EventCode: ...
    @property
    def KEY_SOUND(self) -> const.EventCode: ...
    @property
    def KEY_QUESTION(self) -> const.EventCode: ...
    @property
    def KEY_EMAIL(self) -> const.EventCode: ...
    @property
    def KEY_CHAT(self) -> const.EventCode: ...
    @property
    def KEY_SEARCH(self) -> const.EventCode: ...
    @property
    def KEY_CONNECT(self) -> const.EventCode: ...
    @property
    def KEY_FINANCE(self) -> const.EventCode: ...
    @property
    def KEY_SPORT(self) -> const.EventCode: ...
    @property
    def KEY_SHOP(self) -> const.EventCode: ...
    @property
    def KEY_ALTERASE(self) -> const.EventCode: ...
    @property
    def KEY_CANCEL(self) -> const.EventCode: ...
    @property
    def KEY_BRIGHTNESSDOWN(self) -> const.EventCode: ...
    @property
    def KEY_BRIGHTNESSUP(self) -> const.EventCode: ...
    @property
    def KEY_MEDIA(self) -> const.EventCode: ...
    @property
    def KEY_SWITCHVIDEOMODE(self) -> const.EventCode: ...
    @property
    def KEY_KBDILLUMTOGGLE(self) -> const.EventCode: ...
    @property
    def KEY_KBDILLUMDOWN(self) -> const.EventCode: ...
    @property
    def KEY_KBDILLUMUP(self) -> const.EventCode: ...
    @property
    def KEY_SEND(self) -> const.EventCode: ...
    @property
    def KEY_REPLY(self) -> const.EventCode: ...
    @property
    def KEY_FORWARDMAIL(self) -> const.EventCode: ...
    @property
    def KEY_SAVE(self) -> const.EventCode: ...
    @property
    def KEY_DOCUMENTS(self) -> const.EventCode: ...
    @property
    def KEY_BATTERY(self) -> const.EventCode: ...
    @property
    def KEY_BLUETOOTH(self) -> const.EventCode: ...
    @property
    def KEY_WLAN(self) -> const.EventCode: ...
    @property
    def KEY_UWB(self) -> const.EventCode: ...
    @property
    def KEY_UNKNOWN(self) -> const.EventCode: ...
    @property
    def KEY_VIDEO_NEXT(self) -> const.EventCode: ...
    @property
    def KEY_VIDEO_PREV(self) -> const.EventCode: ...
    @property
    def KEY_BRIGHTNESS_CYCLE(self) -> const.EventCode: ...
    @property
    def KEY_BRIGHTNESS_AUTO(self) -> const.EventCode: ...
    @property
    def KEY_DISPLAY_OFF(self) -> const.EventCode: ...
    @property
    def KEY_WWAN(self) -> const.EventCode: ...
    @property
    def KEY_RFKILL(self) -> const.EventCode: ...
    @property
    def KEY_MICMUTE(self) -> const.EventCode: ...
    @property
    def BTN_0(self) -> const.EventCode: ...
    @property
    def BTN_1(self) -> const.EventCode: ...
    @property
    def BTN_2(self) -> const.EventCode: ...
    @property
    def BTN_3(self) -> const.EventCode: ...
    @property
    def BTN_4(self) -> const.EventCode: ...
    @property
    def BTN_5(self) -> const.EventCode: ...
    @property
    def BTN_6(self) -> const.EventCode: ...
    @property
    def BTN_7(self) -> const.EventCode: ...
    @property
    def BTN_8(self) -> const.EventCode: ...
    @property
    def BTN_9(self) -> const.EventCode: ...
    @property
    def BTN_LEFT(self) -> const.EventCode: ...
    @property
    def BTN_RIGHT(self) -> const.EventCode: ...
    @property
    def BTN_MIDDLE(self) -> const.EventCode: ...
    @property
    def BTN_SIDE(self) -> const.EventCode: ...
    @property
    def BTN_EXTRA(self) -> const.EventCode: ...
    @property
    def BTN_FORWARD(self) -> const.EventCode: ...
    @property
    def BTN_BACK(self) -> const.EventCode: ...
    @property
    def BTN_TASK(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER(self) -> const.EventCode: ...
    @property
    def BTN_THUMB(self) -> const.EventCode: ...
    @property
    def BTN_THUMB2(self) -> const.EventCode: ...
    @property
    def BTN_TOP(self) -> const.EventCode: ...
    @property
    def BTN_TOP2(self) -> const.EventCode: ...
    @property
    def BTN_PINKIE(self) -> const.EventCode: ...
    @property
    def BTN_BASE(self) -> const.EventCode: ...
    @property
    def BTN_BASE2(self) -> const.EventCode: ...
    @property
    def BTN_BASE3(self) -> const.EventCode: ...
    @property
    def BTN_BASE4(self) -> const.EventCode: ...
    @property
    def BTN_BASE5(self) -> const.EventCode: ...
    @property
    def BTN_BASE6(self) -> const.EventCode: ...
    @property
    def BTN_DEAD(self) -> const.EventCode: ...
    @property
    def BTN_SOUTH(self) -> const.EventCode: ...
    @property
    def BTN_EAST(self) -> const.EventCode: ...
    @property
    def BTN_C(self) -> const.EventCode: ...
    @property
    def BTN_NORTH(self) -> const.EventCode: ...
    @property
    def BTN_WEST(self) -> const.EventCode: ...
    @property
    def BTN_Z(self) -> const.EventCode: ...
    @property
    def BTN_TL(self) -> const.EventCode: ...
    @property
    def BTN_TR(self) -> const.EventCode: ...
    @property
    def BTN_TL2(self) -> const.EventCode: ...
    @property
    def BTN_TR2(self) -> const.EventCode: ...
    @property
    def BTN_SELECT(self) -> const.EventCode: ...
    @property
    def BTN_START(self) -> const.EventCode: ...
    @property
    def BTN_MODE(self) -> const.EventCode: ...
    @property
    def BTN_THUMBL(self) -> const.EventCode: ...
    @property
    def BTN_THUMBR(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_PEN(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_RUBBER(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_BRUSH(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_PENCIL(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_AIRBRUSH(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_FINGER(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_MOUSE(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_LENS(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_QUINTTAP(self) -> const.EventCode: ...
    @property
    def BTN_STYLUS3(self) -> const.EventCode: ...
    @property
    def BTN_TOUCH(self) -> const.EventCode: ...
    @property
    def BTN_STYLUS(self) -> const.EventCode: ...
    @property
    def BTN_STYLUS2(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_DOUBLETAP(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_TRIPLETAP(self) -> const.EventCode: ...
    @property
    def BTN_TOOL_QUADTAP(self) -> const.EventCode: ...
    @property
    def BTN_GEAR_DOWN(self) -> const.EventCode: ...
    @property
    def BTN_GEAR_UP(self) -> const.EventCode: ...
    @property
    def KEY_OK(self) -> const.EventCode: ...
    @property
    def KEY_SELECT(self) -> const.EventCode: ...
    @property
    def KEY_GOTO(self) -> const.EventCode: ...
    @property
    def KEY_CLEAR(self) -> const.EventCode: ...
    @property
    def KEY_POWER2(self) -> const.EventCode: ...
    @property
    def KEY_OPTION(self) -> const.EventCode: ...
    @property
    def KEY_INFO(self) -> const.EventCode: ...
    @property
    def KEY_TIME(self) -> const.EventCode: ...
    @property
    def KEY_VENDOR(self) -> const.EventCode: ...
    @property
    def KEY_ARCHIVE(self) -> const.EventCode: ...
    @property
    def KEY_PROGRAM(self) -> const.EventCode: ...
    @property
    def KEY_CHANNEL(self) -> const.EventCode: ...
    @property
    def KEY_FAVORITES(self) -> const.EventCode: ...
    @property
    def KEY_EPG(self) -> const.EventCode: ...
    @property
    def KEY_PVR(self) -> const.EventCode: ...
    @property
    def KEY_MHP(self) -> const.EventCode: ...
    @property
    def KEY_LANGUAGE(self) -> const.EventCode: ...
    @property
    def KEY_TITLE(self) -> const.EventCode: ...
    @property
    def KEY_SUBTITLE(self) -> const.EventCode: ...
    @property
    def KEY_ANGLE(self) -> const.EventCode: ...
    @property
    def KEY_FULL_SCREEN(self) -> const.EventCode: ...
    @property
    def KEY_MODE(self) -> const.EventCode: ...
    @property
    def KEY_KEYBOARD(self) -> const.EventCode: ...
    @property
    def KEY_ASPECT_RATIO(self) -> const.EventCode: ...
    @property
    def KEY_PC(self) -> const.EventCode: ...
    @property
    def KEY_TV(self) -> const.EventCode: ...
    @property
    def KEY_TV2(self) -> const.EventCode: ...
    @property
    def KEY_VCR(self) -> const.EventCode: ...
    @property
    def KEY_VCR2(self) -> const.EventCode: ...
    @property
    def KEY_SAT(self) -> const.EventCode: ...
    @property
    def KEY_SAT2(self) -> const.EventCode: ...
    @property
    def KEY_CD(self) -> const.EventCode: ...
    @property
    def KEY_TAPE(self) -> const.EventCode: ...
    @property
    def KEY_RADIO(self) -> const.EventCode: ...
    @property
    def KEY_TUNER(self) -> const.EventCode: ...
    @property
    def KEY_PLAYER(self) -> const.EventCode: ...
    @property
    def KEY_TEXT(self) -> const.EventCode: ...
    @property
    def KEY_DVD(self) -> const.EventCode: ...
    @property
    def KEY_AUX(self) -> const.EventCode: ...
    @property
    def KEY_MP3(self) -> const.EventCode: ...
    @property
    def KEY_AUDIO(self) -> const.EventCode: ...
    @property
    def KEY_VIDEO(self) -> const.EventCode: ...
    @property
    def KEY_DIRECTORY(self) -> const.EventCode: ...
    @property
    def KEY_LIST(self) -> const.EventCode: ...
    @property
    def KEY_MEMO(self) -> const.EventCode: ...
    @property
    def KEY_CALENDAR(self) -> const.EventCode: ...
    @property
    def KEY_RED(self) -> const.EventCode: ...
    @property
    def KEY_GREEN(self) -> const.EventCode: ...
    @property
    def KEY_YELLOW(self) -> const.EventCode: ...
    @property
    def KEY_BLUE(self) -> const.EventCode: ...
    @property
    def KEY_CHANNELUP(self) -> const.EventCode: ...
    @property
    def KEY_CHANNELDOWN(self) -> const.EventCode: ...
    @property
    def KEY_FIRST(self) -> const.EventCode: ...
    @property
    def KEY_LAST(self) -> const.EventCode: ...
    @property
    def KEY_AB(self) -> const.EventCode: ...
    @property
    def KEY_NEXT(self) -> const.EventCode: ...
    @property
    def KEY_RESTART(self) -> const.EventCode: ...
    @property
    def KEY_SLOW(self) -> const.EventCode: ...
    @property
    def KEY_SHUFFLE(self) -> const.EventCode: ...
    @property
    def KEY_BREAK(self) -> const.EventCode: ...
    @property
    def KEY_PREVIOUS(self) -> const.EventCode: ...
    @property
    def KEY_DIGITS(self) -> const.EventCode: ...
    @property
    def KEY_TEEN(self) -> const.EventCode: ...
    @property
    def KEY_TWEN(self) -> const.EventCode: ...
    @property
    def KEY_VIDEOPHONE(self) -> const.EventCode: ...
    @property
    def KEY_GAMES(self) -> const.EventCode: ...
    @property
    def KEY_ZOOMIN(self) -> const.EventCode: ...
    @property
    def KEY_ZOOMOUT(self) -> const.EventCode: ...
    @property
    def KEY_ZOOMRESET(self) -> const.EventCode: ...
    @property
    def KEY_WORDPROCESSOR(self) -> const.EventCode: ...
    @property
    def KEY_EDITOR(self) -> const.EventCode: ...
    @property
    def KEY_SPREADSHEET(self) -> const.EventCode: ...
    @property
    def KEY_GRAPHICSEDITOR(self) -> const.EventCode: ...
    @property
    def KEY_PRESENTATION(self) -> const.EventCode: ...
    @property
    def KEY_DATABASE(self) -> const.EventCode: ...
    @property
    def KEY_NEWS(self) -> const.EventCode: ...
    @property
    def KEY_VOICEMAIL(self) -> const.EventCode: ...
    @property
    def KEY_ADDRESSBOOK(self) -> const.EventCode: ...
    @property
    def KEY_MESSENGER(self) -> const.EventCode: ...
    @property
    def KEY_DISPLAYTOGGLE(self) -> const.EventCode: ...
    @property
    def KEY_SPELLCHECK(self) -> const.EventCode: ...
    @property
    def KEY_LOGOFF(self) -> const.EventCode: ...
    @property
    def KEY_DOLLAR(self) -> const.EventCode: ...
    @property
    def KEY_EURO(self) -> const.EventCode: ...
    @property
    def KEY_FRAMEBACK(self) -> const.EventCode: ...
    @property
    def KEY_FRAMEFORWARD(self) -> const.EventCode: ...
    @property
    def KEY_CONTEXT_MENU(self) -> const.EventCode: ...
    @property
    def KEY_MEDIA_REPEAT(self) -> const.EventCode: ...
    @property
    def KEY_10CHANNELSUP(self) -> const.EventCode: ...
    @property
    def KEY_10CHANNELSDOWN(self) -> const.EventCode: ...
    @property
    def KEY_IMAGES(self) -> const.EventCode: ...
    @property
    def KEY_NOTIFICATION_CENTER(self) -> const.EventCode: ...
    @property
    def KEY_PICKUP_PHONE(self) -> const.EventCode: ...
    @property
    def KEY_HANGUP_PHONE(self) -> const.EventCode: ...
    @property
    def KEY_LINK_PHONE(self) -> const.EventCode: ...
    @property
    def KEY_DEL_EOL(self) -> const.EventCode: ...
    @property
    def KEY_DEL_EOS(self) -> const.EventCode: ...
    @property
    def KEY_INS_LINE(self) -> const.EventCode: ...
    @property
    def KEY_DEL_LINE(self) -> const.EventCode: ...
    @property
    def KEY_FN(self) -> const.EventCode: ...
    @property
    def KEY_FN_ESC(self) -> const.EventCode: ...
    @property
    def KEY_FN_F1(self) -> const.EventCode: ...
    @property
    def KEY_FN_F2(self) -> const.EventCode: ...
    @property
    def KEY_FN_F3(self) -> const.EventCode: ...
    @property
    def KEY_FN_F4(self) -> const.EventCode: ...
    @property
    def KEY_FN_F5(self) -> const.EventCode: ...
    @property
    def KEY_FN_F6(self) -> const.EventCode: ...
    @property
    def KEY_FN_F7(self) -> const.EventCode: ...
    @property
    def KEY_FN_F8(self) -> const.EventCode: ...
    @property
    def KEY_FN_F9(self) -> const.EventCode: ...
    @property
    def KEY_FN_F10(self) -> const.EventCode: ...
    @property
    def KEY_FN_F11(self) -> const.EventCode: ...
    @property
    def KEY_FN_F12(self) -> const.EventCode: ...
    @property
    def KEY_FN_1(self) -> const.EventCode: ...
    @property
    def KEY_FN_2(self) -> const.EventCode: ...
    @property
    def KEY_FN_D(self) -> const.EventCode: ...
    @property
    def KEY_FN_E(self) -> const.EventCode: ...
    @property
    def KEY_FN_F(self) -> const.EventCode: ...
    @property
    def KEY_FN_S(self) -> const.EventCode: ...
    @property
    def KEY_FN_B(self) -> const.EventCode: ...
    @property
    def KEY_FN_RIGHT_SHIFT(self) -> const.EventCode: ...
    @property
    def KEY_BRL_DOT1(self) -> const.EventCode: ...
    @property
    def KEY_BRL_DOT2(self) -> const.EventCode: ...
    @property
    def KEY_BRL_DOT3(self) -> const.EventCode: ...
    @property
    def KEY_BRL_DOT4(self) -> const.EventCode: ...
    @property
    def KEY_BRL_DOT5(self) -> const.EventCode: ...
    @property
    def KEY_BRL_DOT6(self) -> const.EventCode: ...
    @property
    def KEY_BRL_DOT7(self) -> const.EventCode: ...
    @property
    def KEY_BRL_DOT8(self) -> const.EventCode: ...
    @property
    def KEY_BRL_DOT9(self) -> const.EventCode: ...
    @property
    def KEY_BRL_DOT10(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_0(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_1(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_2(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_3(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_4(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_5(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_6(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_7(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_8(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_9(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_STAR(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_POUND(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_A(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_B(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_C(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_D(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA_FOCUS(self) -> const.EventCode: ...
    @property
    def KEY_WPS_BUTTON(self) -> const.EventCode: ...
    @property
    def KEY_TOUCHPAD_TOGGLE(self) -> const.EventCode: ...
    @property
    def KEY_TOUCHPAD_ON(self) -> const.EventCode: ...
    @property
    def KEY_TOUCHPAD_OFF(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA_ZOOMIN(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA_ZOOMOUT(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA_UP(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA_DOWN(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA_LEFT(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA_RIGHT(self) -> const.EventCode: ...
    @property
    def KEY_ATTENDANT_ON(self) -> const.EventCode: ...
    @property
    def KEY_ATTENDANT_OFF(self) -> const.EventCode: ...
    @property
    def KEY_ATTENDANT_TOGGLE(self) -> const.EventCode: ...
    @property
    def KEY_LIGHTS_TOGGLE(self) -> const.EventCode: ...
    @property
    def BTN_DPAD_UP(self) -> const.EventCode: ...
    @property
    def BTN_DPAD_DOWN(self) -> const.EventCode: ...
    @property
    def BTN_DPAD_LEFT(self) -> const.EventCode: ...
    @property
    def BTN_DPAD_RIGHT(self) -> const.EventCode: ...
    @property
    def BTN_GRIPL(self) -> const.EventCode: ...
    @property
    def BTN_GRIPR(self) -> const.EventCode: ...
    @property
    def BTN_GRIPL2(self) -> const.EventCode: ...
    @property
    def BTN_GRIPR2(self) -> const.EventCode: ...
    @property
    def KEY_ALS_TOGGLE(self) -> const.EventCode: ...
    @property
    def KEY_ROTATE_LOCK_TOGGLE(self) -> const.EventCode: ...
    @property
    def KEY_REFRESH_RATE_TOGGLE(self) -> const.EventCode: ...
    @property
    def KEY_BUTTONCONFIG(self) -> const.EventCode: ...
    @property
    def KEY_TASKMANAGER(self) -> const.EventCode: ...
    @property
    def KEY_JOURNAL(self) -> const.EventCode: ...
    @property
    def KEY_CONTROLPANEL(self) -> const.EventCode: ...
    @property
    def KEY_APPSELECT(self) -> const.EventCode: ...
    @property
    def KEY_SCREENSAVER(self) -> const.EventCode: ...
    @property
    def KEY_VOICECOMMAND(self) -> const.EventCode: ...
    @property
    def KEY_ASSISTANT(self) -> const.EventCode: ...
    @property
    def KEY_KBD_LAYOUT_NEXT(self) -> const.EventCode: ...
    @property
    def KEY_EMOJI_PICKER(self) -> const.EventCode: ...
    @property
    def KEY_DICTATE(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA_ACCESS_ENABLE(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA_ACCESS_DISABLE(self) -> const.EventCode: ...
    @property
    def KEY_CAMERA_ACCESS_TOGGLE(self) -> const.EventCode: ...
    @property
    def KEY_ACCESSIBILITY(self) -> const.EventCode: ...
    @property
    def KEY_DO_NOT_DISTURB(self) -> const.EventCode: ...
    @property
    def KEY_BRIGHTNESS_MIN(self) -> const.EventCode: ...
    @property
    def KEY_BRIGHTNESS_MAX(self) -> const.EventCode: ...
    @property
    def KEY_KBDINPUTASSIST_PREV(self) -> const.EventCode: ...
    @property
    def KEY_KBDINPUTASSIST_NEXT(self) -> const.EventCode: ...
    @property
    def KEY_KBDINPUTASSIST_PREVGROUP(self) -> const.EventCode: ...
    @property
    def KEY_KBDINPUTASSIST_NEXTGROUP(self) -> const.EventCode: ...
    @property
    def KEY_KBDINPUTASSIST_ACCEPT(self) -> const.EventCode: ...
    @property
    def KEY_KBDINPUTASSIST_CANCEL(self) -> const.EventCode: ...
    @property
    def KEY_RIGHT_UP(self) -> const.EventCode: ...
    @property
    def KEY_RIGHT_DOWN(self) -> const.EventCode: ...
    @property
    def KEY_LEFT_UP(self) -> const.EventCode: ...
    @property
    def KEY_LEFT_DOWN(self) -> const.EventCode: ...
    @property
    def KEY_ROOT_MENU(self) -> const.EventCode: ...
    @property
    def KEY_MEDIA_TOP_MENU(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_11(self) -> const.EventCode: ...
    @property
    def KEY_NUMERIC_12(self) -> const.EventCode: ...
    @property
    def KEY_AUDIO_DESC(self) -> const.EventCode: ...
    @property
    def KEY_3D_MODE(self) -> const.EventCode: ...
    @property
    def KEY_NEXT_FAVORITE(self) -> const.EventCode: ...
    @property
    def KEY_STOP_RECORD(self) -> const.EventCode: ...
    @property
    def KEY_PAUSE_RECORD(self) -> const.EventCode: ...
    @property
    def KEY_VOD(self) -> const.EventCode: ...
    @property
    def KEY_UNMUTE(self) -> const.EventCode: ...
    @property
    def KEY_FASTREVERSE(self) -> const.EventCode: ...
    @property
    def KEY_SLOWREVERSE(self) -> const.EventCode: ...
    @property
    def KEY_DATA(self) -> const.EventCode: ...
    @property
    def KEY_ONSCREEN_KEYBOARD(self) -> const.EventCode: ...
    @property
    def KEY_PRIVACY_SCREEN_TOGGLE(self) -> const.EventCode: ...
    @property
    def KEY_SELECTIVE_SCREENSHOT(self) -> const.EventCode: ...
    @property
    def KEY_NEXT_ELEMENT(self) -> const.EventCode: ...
    @property
    def KEY_PREVIOUS_ELEMENT(self) -> const.EventCode: ...
    @property
    def KEY_AUTOPILOT_ENGAGE_TOGGLE(self) -> const.EventCode: ...
    @property
    def KEY_MARK_WAYPOINT(self) -> const.EventCode: ...
    @property
    def KEY_SOS(self) -> const.EventCode: ...
    @property
    def KEY_NAV_CHART(self) -> const.EventCode: ...
    @property
    def KEY_FISHING_CHART(self) -> const.EventCode: ...
    @property
    def KEY_SINGLE_RANGE_RADAR(self) -> const.EventCode: ...
    @property
    def KEY_DUAL_RANGE_RADAR(self) -> const.EventCode: ...
    @property
    def KEY_RADAR_OVERLAY(self) -> const.EventCode: ...
    @property
    def KEY_TRADITIONAL_SONAR(self) -> const.EventCode: ...
    @property
    def KEY_CLEARVU_SONAR(self) -> const.EventCode: ...
    @property
    def KEY_SIDEVU_SONAR(self) -> const.EventCode: ...
    @property
    def KEY_NAV_INFO(self) -> const.EventCode: ...
    @property
    def KEY_BRIGHTNESS_MENU(self) -> const.EventCode: ...
    @property
    def KEY_MACRO1(self) -> const.EventCode: ...
    @property
    def KEY_MACRO2(self) -> const.EventCode: ...
    @property
    def KEY_MACRO3(self) -> const.EventCode: ...
    @property
    def KEY_MACRO4(self) -> const.EventCode: ...
    @property
    def KEY_MACRO5(self) -> const.EventCode: ...
    @property
    def KEY_MACRO6(self) -> const.EventCode: ...
    @property
    def KEY_MACRO7(self) -> const.EventCode: ...
    @property
    def KEY_MACRO8(self) -> const.EventCode: ...
    @property
    def KEY_MACRO9(self) -> const.EventCode: ...
    @property
    def KEY_MACRO10(self) -> const.EventCode: ...
    @property
    def KEY_MACRO11(self) -> const.EventCode: ...
    @property
    def KEY_MACRO12(self) -> const.EventCode: ...
    @property
    def KEY_MACRO13(self) -> const.EventCode: ...
    @property
    def KEY_MACRO14(self) -> const.EventCode: ...
    @property
    def KEY_MACRO15(self) -> const.EventCode: ...
    @property
    def KEY_MACRO16(self) -> const.EventCode: ...
    @property
    def KEY_MACRO17(self) -> const.EventCode: ...
    @property
    def KEY_MACRO18(self) -> const.EventCode: ...
    @property
    def KEY_MACRO19(self) -> const.EventCode: ...
    @property
    def KEY_MACRO20(self) -> const.EventCode: ...
    @property
    def KEY_MACRO21(self) -> const.EventCode: ...
    @property
    def KEY_MACRO22(self) -> const.EventCode: ...
    @property
    def KEY_MACRO23(self) -> const.EventCode: ...
    @property
    def KEY_MACRO24(self) -> const.EventCode: ...
    @property
    def KEY_MACRO25(self) -> const.EventCode: ...
    @property
    def KEY_MACRO26(self) -> const.EventCode: ...
    @property
    def KEY_MACRO27(self) -> const.EventCode: ...
    @property
    def KEY_MACRO28(self) -> const.EventCode: ...
    @property
    def KEY_MACRO29(self) -> const.EventCode: ...
    @property
    def KEY_MACRO30(self) -> const.EventCode: ...
    @property
    def KEY_MACRO_RECORD_START(self) -> const.EventCode: ...
    @property
    def KEY_MACRO_RECORD_STOP(self) -> const.EventCode: ...
    @property
    def KEY_MACRO_PRESET_CYCLE(self) -> const.EventCode: ...
    @property
    def KEY_MACRO_PRESET1(self) -> const.EventCode: ...
    @property
    def KEY_MACRO_PRESET2(self) -> const.EventCode: ...
    @property
    def KEY_MACRO_PRESET3(self) -> const.EventCode: ...
    @property
    def KEY_KBD_LCD_MENU1(self) -> const.EventCode: ...
    @property
    def KEY_KBD_LCD_MENU2(self) -> const.EventCode: ...
    @property
    def KEY_KBD_LCD_MENU3(self) -> const.EventCode: ...
    @property
    def KEY_KBD_LCD_MENU4(self) -> const.EventCode: ...
    @property
    def KEY_KBD_LCD_MENU5(self) -> const.EventCode: ...
    @property
    def KEY_PERFORMANCE(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY1(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY2(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY3(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY4(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY5(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY6(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY7(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY8(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY9(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY10(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY11(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY12(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY13(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY14(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY15(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY16(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY17(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY18(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY19(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY20(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY21(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY22(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY23(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY24(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY25(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY26(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY27(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY28(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY29(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY30(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY31(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY32(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY33(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY34(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY35(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY36(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY37(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY38(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY39(self) -> const.EventCode: ...
    @property
    def BTN_TRIGGER_HAPPY40(self) -> const.EventCode: ...
    @property
    def KEY_AI_ASSISTANT(self) -> const.EventCode: ...
    @property
    def KEY_MAX(self) -> const.EventCode: ...

class _EV_REL(const.EventType):
    @property
    def REL_X(self) -> const.EventCode: ...
    @property
    def REL_Y(self) -> const.EventCode: ...
    @property
    def REL_Z(self) -> const.EventCode: ...
    @property
    def REL_RX(self) -> const.EventCode: ...
    @property
    def REL_RY(self) -> const.EventCode: ...
    @property
    def REL_RZ(self) -> const.EventCode: ...
    @property
    def REL_HWHEEL(self) -> const.EventCode: ...
    @property
    def REL_DIAL(self) -> const.EventCode: ...
    @property
    def REL_WHEEL(self) -> const.EventCode: ...
    @property
    def REL_MISC(self) -> const.EventCode: ...
    @property
    def REL_RESERVED(self) -> const.EventCode: ...
    @property
    def REL_WHEEL_HI_RES(self) -> const.EventCode: ...
    @property
    def REL_HWHEEL_HI_RES(self) -> const.EventCode: ...
    @property
    def REL_MAX(self) -> const.EventCode: ...

class _EV_ABS(const.EventType):
    @property
    def ABS_X(self) -> const.EventCode: ...
    @property
    def ABS_Y(self) -> const.EventCode: ...
    @property
    def ABS_Z(self) -> const.EventCode: ...
    @property
    def ABS_RX(self) -> const.EventCode: ...
    @property
    def ABS_RY(self) -> const.EventCode: ...
    @property
    def ABS_RZ(self) -> const.EventCode: ...
    @property
    def ABS_THROTTLE(self) -> const.EventCode: ...
    @property
    def ABS_RUDDER(self) -> const.EventCode: ...
    @property
    def ABS_WHEEL(self) -> const.EventCode: ...
    @property
    def ABS_GAS(self) -> const.EventCode: ...
    @property
    def ABS_BRAKE(self) -> const.EventCode: ...
    @property
    def ABS_HAT0X(self) -> const.EventCode: ...
    @property
    def ABS_HAT0Y(self) -> const.EventCode: ...
    @property
    def ABS_HAT1X(self) -> const.EventCode: ...
    @property
    def ABS_HAT1Y(self) -> const.EventCode: ...
    @property
    def ABS_HAT2X(self) -> const.EventCode: ...
    @property
    def ABS_HAT2Y(self) -> const.EventCode: ...
    @property
    def ABS_HAT3X(self) -> const.EventCode: ...
    @property
    def ABS_HAT3Y(self) -> const.EventCode: ...
    @property
    def ABS_PRESSURE(self) -> const.EventCode: ...
    @property
    def ABS_DISTANCE(self) -> const.EventCode: ...
    @property
    def ABS_TILT_X(self) -> const.EventCode: ...
    @property
    def ABS_TILT_Y(self) -> const.EventCode: ...
    @property
    def ABS_TOOL_WIDTH(self) -> const.EventCode: ...
    @property
    def ABS_VOLUME(self) -> const.EventCode: ...
    @property
    def ABS_PROFILE(self) -> const.EventCode: ...
    @property
    def ABS_MISC(self) -> const.EventCode: ...
    @property
    def ABS_RESERVED(self) -> const.EventCode: ...
    @property
    def ABS_MT_SLOT(self) -> const.EventCode: ...
    @property
    def ABS_MT_TOUCH_MAJOR(self) -> const.EventCode: ...
    @property
    def ABS_MT_TOUCH_MINOR(self) -> const.EventCode: ...
    @property
    def ABS_MT_WIDTH_MAJOR(self) -> const.EventCode: ...
    @property
    def ABS_MT_WIDTH_MINOR(self) -> const.EventCode: ...
    @property
    def ABS_MT_ORIENTATION(self) -> const.EventCode: ...
    @property
    def ABS_MT_POSITION_X(self) -> const.EventCode: ...
    @property
    def ABS_MT_POSITION_Y(self) -> const.EventCode: ...
    @property
    def ABS_MT_TOOL_TYPE(self) -> const.EventCode: ...
    @property
    def ABS_MT_BLOB_ID(self) -> const.EventCode: ...
    @property
    def ABS_MT_TRACKING_ID(self) -> const.EventCode: ...
    @property
    def ABS_MT_PRESSURE(self) -> const.EventCode: ...
    @property
    def ABS_MT_DISTANCE(self) -> const.EventCode: ...
    @property
    def ABS_MT_TOOL_X(self) -> const.EventCode: ...
    @property
    def ABS_MT_TOOL_Y(self) -> const.EventCode: ...
    @property
    def ABS_MAX(self) -> const.EventCode: ...

class _EV_MSC(const.EventType):
    @property
    def MSC_SERIAL(self) -> const.EventCode: ...
    @property
    def MSC_PULSELED(self) -> const.EventCode: ...
    @property
    def MSC_GESTURE(self) -> const.EventCode: ...
    @property
    def MSC_RAW(self) -> const.EventCode: ...
    @property
    def MSC_SCAN(self) -> const.EventCode: ...
    @property
    def MSC_TIMESTAMP(self) -> const.EventCode: ...
    @property
    def MSC_MAX(self) -> const.EventCode: ...

class _EV_SW(const.EventType):
    @property
    def SW_LID(self) -> const.EventCode: ...
    @property
    def SW_TABLET_MODE(self) -> const.EventCode: ...
    @property
    def SW_HEADPHONE_INSERT(self) -> const.EventCode: ...
    @property
    def SW_RFKILL_ALL(self) -> const.EventCode: ...
    @property
    def SW_MICROPHONE_INSERT(self) -> const.EventCode: ...
    @property
    def SW_DOCK(self) -> const.EventCode: ...
    @property
    def SW_LINEOUT_INSERT(self) -> const.EventCode: ...
    @property
    def SW_JACK_PHYSICAL_INSERT(self) -> const.EventCode: ...
    @property
    def SW_VIDEOOUT_INSERT(self) -> const.EventCode: ...
    @property
    def SW_CAMERA_LENS_COVER(self) -> const.EventCode: ...
    @property
    def SW_KEYPAD_SLIDE(self) -> const.EventCode: ...
    @property
    def SW_FRONT_PROXIMITY(self) -> const.EventCode: ...
    @property
    def SW_ROTATE_LOCK(self) -> const.EventCode: ...
    @property
    def SW_LINEIN_INSERT(self) -> const.EventCode: ...
    @property
    def SW_MUTE_DEVICE(self) -> const.EventCode: ...
    @property
    def SW_PEN_INSERTED(self) -> const.EventCode: ...
    @property
    def SW_MACHINE_COVER(self) -> const.EventCode: ...
    @property
    def SW_USB_INSERT(self) -> const.EventCode: ...

class _EV_LED(const.EventType):
    @property
    def LED_NUML(self) -> const.EventCode: ...
    @property
    def LED_CAPSL(self) -> const.EventCode: ...
    @property
    def LED_SCROLLL(self) -> const.EventCode: ...
    @property
    def LED_COMPOSE(self) -> const.EventCode: ...
    @property
    def LED_KANA(self) -> const.EventCode: ...
    @property
    def LED_SLEEP(self) -> const.EventCode: ...
    @property
    def LED_SUSPEND(self) -> const.EventCode: ...
    @property
    def LED_MUTE(self) -> const.EventCode: ...
    @property
    def LED_MISC(self) -> const.EventCode: ...
    @property
    def LED_MAIL(self) -> const.EventCode: ...
    @property
    def LED_CHARGING(self) -> const.EventCode: ...
    @property
    def LED_MAX(self) -> const.EventCode: ...

class _EV_SND(const.EventType):
    @property
    def SND_CLICK(self) -> const.EventCode: ...
    @property
    def SND_BELL(self) -> const.EventCode: ...
    @property
    def SND_TONE(self) -> const.EventCode: ...
    @property
    def SND_MAX(self) -> const.EventCode: ...

class _EV_REP(const.EventType):
    @property
    def REP_DELAY(self) -> const.EventCode: ...
    @property
    def REP_PERIOD(self) -> const.EventCode: ...

class _EV_FF(const.EventType):
    @property
    def FF_STATUS_STOPPED(self) -> const.EventCode: ...
    @property
    def FF_STATUS_MAX(self) -> const.EventCode: ...
    @property
    def FF_RUMBLE(self) -> const.EventCode: ...
    @property
    def FF_PERIODIC(self) -> const.EventCode: ...
    @property
    def FF_CONSTANT(self) -> const.EventCode: ...
    @property
    def FF_SPRING(self) -> const.EventCode: ...
    @property
    def FF_FRICTION(self) -> const.EventCode: ...
    @property
    def FF_DAMPER(self) -> const.EventCode: ...
    @property
    def FF_INERTIA(self) -> const.EventCode: ...
    @property
    def FF_RAMP(self) -> const.EventCode: ...
    @property
    def FF_SQUARE(self) -> const.EventCode: ...
    @property
    def FF_TRIANGLE(self) -> const.EventCode: ...
    @property
    def FF_SINE(self) -> const.EventCode: ...
    @property
    def FF_SAW_UP(self) -> const.EventCode: ...
    @property
    def FF_SAW_DOWN(self) -> const.EventCode: ...
    @property
    def FF_CUSTOM(self) -> const.EventCode: ...
    @property
    def FF_GAIN(self) -> const.EventCode: ...
    @property
    def FF_AUTOCENTER(self) -> const.EventCode: ...
    @property
    def FF_MAX(self) -> const.EventCode: ...

EV_SYN: _EV_SYN
EV_KEY: _EV_KEY
EV_REL: _EV_REL
EV_ABS: _EV_ABS
EV_MSC: _EV_MSC
EV_SW: _EV_SW
EV_LED: _EV_LED
EV_SND: _EV_SND
EV_REP: _EV_REP
EV_FF: _EV_FF
SYN_REPORT: const.EventCode
SYN_CONFIG: const.EventCode
SYN_MT_REPORT: const.EventCode
SYN_DROPPED: const.EventCode
SYN_MAX: const.EventCode
KEY_RESERVED: const.EventCode
KEY_ESC: const.EventCode
KEY_1: const.EventCode
KEY_2: const.EventCode
KEY_3: const.EventCode
KEY_4: const.EventCode
KEY_5: const.EventCode
KEY_6: const.EventCode
KEY_7: const.EventCode
KEY_8: const.EventCode
KEY_9: const.EventCode
KEY_0: const.EventCode
KEY_MINUS: const.EventCode
KEY_EQUAL: const.EventCode
KEY_BACKSPACE: const.EventCode
KEY_TAB: const.EventCode
KEY_Q: const.EventCode
KEY_W: const.EventCode
KEY_E: const.EventCode
KEY_R: const.EventCode
KEY_T: const.EventCode
KEY_Y: const.EventCode
KEY_U: const.EventCode
KEY_I: const.EventCode
KEY_O: const.EventCode
KEY_P: const.EventCode
KEY_LEFTBRACE: const.EventCode
KEY_RIGHTBRACE: const.EventCode
KEY_ENTER: const.EventCode
KEY_LEFTCTRL: const.EventCode
KEY_A: const.EventCode
KEY_S: const.EventCode
KEY_D: const.EventCode
KEY_F: const.EventCode
KEY_G: const.EventCode
KEY_H: const.EventCode
KEY_J: const.EventCode
KEY_K: const.EventCode
KEY_L: const.EventCode
KEY_SEMICOLON: const.EventCode
KEY_APOSTROPHE: const.EventCode
KEY_GRAVE: const.EventCode
KEY_LEFTSHIFT: const.EventCode
KEY_BACKSLASH: const.EventCode
KEY_Z: const.EventCode
KEY_X: const.EventCode
KEY_C: const.EventCode
KEY_V: const.EventCode
KEY_B: const.EventCode
KEY_N: const.EventCode
KEY_M: const.EventCode
KEY_COMMA: const.EventCode
KEY_DOT: const.EventCode
KEY_SLASH: const.EventCode
KEY_RIGHTSHIFT: const.EventCode
KEY_KPASTERISK: const.EventCode
KEY_LEFTALT: const.EventCode
KEY_SPACE: const.EventCode
KEY_CAPSLOCK: const.EventCode
KEY_F1: const.EventCode
KEY_F2: const.EventCode
KEY_F3: const.EventCode
KEY_F4: const.EventCode
KEY_F5: const.EventCode
KEY_F6: const.EventCode
KEY_F7: const.EventCode
KEY_F8: const.EventCode
KEY_F9: const.EventCode
KEY_F10: const.EventCode
KEY_NUMLOCK: const.EventCode
KEY_SCROLLLOCK: const.EventCode
KEY_KP7: const.EventCode
KEY_KP8: const.EventCode
KEY_KP9: const.EventCode
KEY_KPMINUS: const.EventCode
KEY_KP4: const.EventCode
KEY_KP5: const.EventCode
KEY_KP6: const.EventCode
KEY_KPPLUS: const.EventCode
KEY_KP1: const.EventCode
KEY_KP2: const.EventCode
KEY_KP3: const.EventCode
KEY_KP0: const.EventCode
KEY_KPDOT: const.EventCode
KEY_ZENKAKUHANKAKU: const.EventCode
KEY_102ND: const.EventCode
KEY_F11: const.EventCode
KEY_F12: const.EventCode
KEY_RO: const.EventCode
KEY_KATAKANA: const.EventCode
KEY_HIRAGANA: const.EventCode
KEY_HENKAN: const.EventCode
KEY_KATAKANAHIRAGANA: const.EventCode
KEY_MUHENKAN: const.EventCode
KEY_KPJPCOMMA: const.EventCode
KEY_KPENTER: const.EventCode
KEY_RIGHTCTRL: const.EventCode
KEY_KPSLASH: const.EventCode
KEY_SYSRQ: const.EventCode
KEY_RIGHTALT: const.EventCode
KEY_LINEFEED: const.EventCode
KEY_HOME: const.EventCode
KEY_UP: const.EventCode
KEY_PAGEUP: const.EventCode
KEY_LEFT: const.EventCode
KEY_RIGHT: const.EventCode
KEY_END: const.EventCode
KEY_DOWN: const.EventCode
KEY_PAGEDOWN: const.EventCode
KEY_INSERT: const.EventCode
KEY_DELETE: const.EventCode
KEY_MACRO: const.EventCode
KEY_MUTE: const.EventCode
KEY_VOLUMEDOWN: const.EventCode
KEY_VOLUMEUP: const.EventCode
KEY_POWER: const.EventCode
KEY_KPEQUAL: const.EventCode
KEY_KPPLUSMINUS: const.EventCode
KEY_PAUSE: const.EventCode
KEY_SCALE: const.EventCode
KEY_KPCOMMA: const.EventCode
KEY_HANGEUL: const.EventCode
KEY_HANJA: const.EventCode
KEY_YEN: const.EventCode
KEY_LEFTMETA: const.EventCode
KEY_RIGHTMETA: const.EventCode
KEY_COMPOSE: const.EventCode
KEY_STOP: const.EventCode
KEY_AGAIN: const.EventCode
KEY_PROPS: const.EventCode
KEY_UNDO: const.EventCode
KEY_FRONT: const.EventCode
KEY_COPY: const.EventCode
KEY_OPEN: const.EventCode
KEY_PASTE: const.EventCode
KEY_FIND: const.EventCode
KEY_CUT: const.EventCode
KEY_HELP: const.EventCode
KEY_MENU: const.EventCode
KEY_CALC: const.EventCode
KEY_SETUP: const.EventCode
KEY_SLEEP: const.EventCode
KEY_WAKEUP: const.EventCode
KEY_FILE: const.EventCode
KEY_SENDFILE: const.EventCode
KEY_DELETEFILE: const.EventCode
KEY_XFER: const.EventCode
KEY_PROG1: const.EventCode
KEY_PROG2: const.EventCode
KEY_WWW: const.EventCode
KEY_MSDOS: const.EventCode
KEY_COFFEE: const.EventCode
KEY_ROTATE_DISPLAY: const.EventCode
KEY_CYCLEWINDOWS: const.EventCode
KEY_MAIL: const.EventCode
KEY_BOOKMARKS: const.EventCode
KEY_COMPUTER: const.EventCode
KEY_BACK: const.EventCode
KEY_FORWARD: const.EventCode
KEY_CLOSECD: const.EventCode
KEY_EJECTCD: const.EventCode
KEY_EJECTCLOSECD: const.EventCode
KEY_NEXTSONG: const.EventCode
KEY_PLAYPAUSE: const.EventCode
KEY_PREVIOUSSONG: const.EventCode
KEY_STOPCD: const.EventCode
KEY_RECORD: const.EventCode
KEY_REWIND: const.EventCode
KEY_PHONE: const.EventCode
KEY_ISO: const.EventCode
KEY_CONFIG: const.EventCode
KEY_HOMEPAGE: const.EventCode
KEY_REFRESH: const.EventCode
KEY_EXIT: const.EventCode
KEY_MOVE: const.EventCode
KEY_EDIT: const.EventCode
KEY_SCROLLUP: const.EventCode
KEY_SCROLLDOWN: const.EventCode
KEY_KPLEFTPAREN: const.EventCode
KEY_KPRIGHTPAREN: const.EventCode
KEY_NEW: const.EventCode
KEY_REDO: const.EventCode
KEY_F13: const.EventCode
KEY_F14: const.EventCode
KEY_F15: const.EventCode
KEY_F16: const.EventCode
KEY_F17: const.EventCode
KEY_F18: const.EventCode
KEY_F19: const.EventCode
KEY_F20: const.EventCode
KEY_F21: const.EventCode
KEY_F22: const.EventCode
KEY_F23: const.EventCode
KEY_F24: const.EventCode
KEY_PLAYCD: const.EventCode
KEY_PAUSECD: const.EventCode
KEY_PROG3: const.EventCode
KEY_PROG4: const.EventCode
KEY_ALL_APPLICATIONS: const.EventCode
KEY_SUSPEND: const.EventCode
KEY_CLOSE: const.EventCode
KEY_PLAY: const.EventCode
KEY_FASTFORWARD: const.EventCode
KEY_BASSBOOST: const.EventCode
KEY_PRINT: const.EventCode
KEY_HP: const.EventCode
KEY_CAMERA: const.EventCode
KEY_SOUND: const.EventCode
KEY_QUESTION: const.EventCode
KEY_EMAIL: const.EventCode
KEY_CHAT: const.EventCode
KEY_SEARCH: const.EventCode
KEY_CONNECT: const.EventCode
KEY_FINANCE: const.EventCode
KEY_SPORT: const.EventCode
KEY_SHOP: const.EventCode
KEY_ALTERASE: const.EventCode
KEY_CANCEL: const.EventCode
KEY_BRIGHTNESSDOWN: const.EventCode
KEY_BRIGHTNESSUP: const.EventCode
KEY_MEDIA: const.EventCode
KEY_SWITCHVIDEOMODE: const.EventCode
KEY_KBDILLUMTOGGLE: const.EventCode
KEY_KBDILLUMDOWN: const.EventCode
KEY_KBDILLUMUP: const.EventCode
KEY_SEND: const.EventCode
KEY_REPLY: const.EventCode
KEY_FORWARDMAIL: const.EventCode
KEY_SAVE: const.EventCode
KEY_DOCUMENTS: const.EventCode
KEY_BATTERY: const.EventCode
KEY_BLUETOOTH: const.EventCode
KEY_WLAN: const.EventCode
KEY_UWB: const.EventCode
KEY_UNKNOWN: const.EventCode
KEY_VIDEO_NEXT: const.EventCode
KEY_VIDEO_PREV: const.EventCode
KEY_BRIGHTNESS_CYCLE: const.EventCode
KEY_BRIGHTNESS_AUTO: const.EventCode
KEY_DISPLAY_OFF: const.EventCode
KEY_WWAN: const.EventCode
KEY_RFKILL: const.EventCode
KEY_MICMUTE: const.EventCode
BTN_0: const.EventCode
BTN_1: const.EventCode
BTN_2: const.EventCode
BTN_3: const.EventCode
BTN_4: const.EventCode
BTN_5: const.EventCode
BTN_6: const.EventCode
BTN_7: const.EventCode
BTN_8: const.EventCode
BTN_9: const.EventCode
BTN_LEFT: const.EventCode
BTN_RIGHT: const.EventCode
BTN_MIDDLE: const.EventCode
BTN_SIDE: const.EventCode
BTN_EXTRA: const.EventCode
BTN_FORWARD: const.EventCode
BTN_BACK: const.EventCode
BTN_TASK: const.EventCode
BTN_TRIGGER: const.EventCode
BTN_THUMB: const.EventCode
BTN_THUMB2: const.EventCode
BTN_TOP: const.EventCode
BTN_TOP2: const.EventCode
BTN_PINKIE: const.EventCode
BTN_BASE: const.EventCode
BTN_BASE2: const.EventCode
BTN_BASE3: const.EventCode
BTN_BASE4: const.EventCode
BTN_BASE5: const.EventCode
BTN_BASE6: const.EventCode
BTN_DEAD: const.EventCode
BTN_SOUTH: const.EventCode
BTN_EAST: const.EventCode
BTN_C: const.EventCode
BTN_NORTH: const.EventCode
BTN_WEST: const.EventCode
BTN_Z: const.EventCode
BTN_TL: const.EventCode
BTN_TR: const.EventCode
BTN_TL2: const.EventCode
BTN_TR2: const.EventCode
BTN_SELECT: const.EventCode
BTN_START: const.EventCode
BTN_MODE: const.EventCode
BTN_THUMBL: const.EventCode
BTN_THUMBR: const.EventCode
BTN_TOOL_PEN: const.EventCode
BTN_TOOL_RUBBER: const.EventCode
BTN_TOOL_BRUSH: const.EventCode
BTN_TOOL_PENCIL: const.EventCode
BTN_TOOL_AIRBRUSH: const.EventCode
BTN_TOOL_FINGER: const.EventCode
BTN_TOOL_MOUSE: const.EventCode
BTN_TOOL_LENS: const.EventCode
BTN_TOOL_QUINTTAP: const.EventCode
BTN_STYLUS3: const.EventCode
BTN_TOUCH: const.EventCode
BTN_STYLUS: const.EventCode
BTN_STYLUS2: const.EventCode
BTN_TOOL_DOUBLETAP: const.EventCode
BTN_TOOL_TRIPLETAP: const.EventCode
BTN_TOOL_QUADTAP: const.EventCode
BTN_GEAR_DOWN: const.EventCode
BTN_GEAR_UP: const.EventCode
KEY_OK: const.EventCode
KEY_SELECT: const.EventCode
KEY_GOTO: const.EventCode
KEY_CLEAR: const.EventCode
KEY_POWER2: const.EventCode
KEY_OPTION: const.EventCode
KEY_INFO: const.EventCode
KEY_TIME: const.EventCode
KEY_VENDOR: const.EventCode
KEY_ARCHIVE: const.EventCode
KEY_PROGRAM: const.EventCode
KEY_CHANNEL: const.EventCode
KEY_FAVORITES: const.EventCode
KEY_EPG: const.EventCode
KEY_PVR: const.EventCode
KEY_MHP: const.EventCode
KEY_LANGUAGE: const.EventCode
KEY_TITLE: const.EventCode
KEY_SUBTITLE: const.EventCode
KEY_ANGLE: const.EventCode
KEY_FULL_SCREEN: const.EventCode
KEY_MODE: const.EventCode
KEY_KEYBOARD: const.EventCode
KEY_ASPECT_RATIO: const.EventCode
KEY_PC: const.EventCode
KEY_TV: const.EventCode
KEY_TV2: const.EventCode
KEY_VCR: const.EventCode
KEY_VCR2: const.EventCode
KEY_SAT: const.EventCode
KEY_SAT2: const.EventCode
KEY_CD: const.EventCode
KEY_TAPE: const.EventCode
KEY_RADIO: const.EventCode
KEY_TUNER: const.EventCode
KEY_PLAYER: const.EventCode
KEY_TEXT: const.EventCode
KEY_DVD: const.EventCode
KEY_AUX: const.EventCode
KEY_MP3: const.EventCode
KEY_AUDIO: const.EventCode
KEY_VIDEO: const.EventCode
KEY_DIRECTORY: const.EventCode
KEY_LIST: const.EventCode
KEY_MEMO: const.EventCode
KEY_CALENDAR: const.EventCode
KEY_RED: const.EventCode
KEY_GREEN: const.EventCode
KEY_YELLOW: const.EventCode
KEY_BLUE: const.EventCode
KEY_CHANNELUP: const.EventCode
KEY_CHANNELDOWN: const.EventCode
KEY_FIRST: const.EventCode
KEY_LAST: const.EventCode
KEY_AB: const.EventCode
KEY_NEXT: const.EventCode
KEY_RESTART: const.EventCode
KEY_SLOW: const.EventCode
KEY_SHUFFLE: const.EventCode
KEY_BREAK: const.EventCode
KEY_PREVIOUS: const.EventCode
KEY_DIGITS: const.EventCode
KEY_TEEN: const.EventCode
KEY_TWEN: const.EventCode
KEY_VIDEOPHONE: const.EventCode
KEY_GAMES: const.EventCode
KEY_ZOOMIN: const.EventCode
KEY_ZOOMOUT: const.EventCode
KEY_ZOOMRESET: const.EventCode
KEY_WORDPROCESSOR: const.EventCode
KEY_EDITOR: const.EventCode
KEY_SPREADSHEET: const.EventCode
KEY_GRAPHICSEDITOR: const.EventCode
KEY_PRESENTATION: const.EventCode
KEY_DATABASE: const.EventCode
KEY_NEWS: const.EventCode
KEY_VOICEMAIL: const.EventCode
KEY_ADDRESSBOOK: const.EventCode
KEY_MESSENGER: const.EventCode
KEY_DISPLAYTOGGLE: const.EventCode
KEY_SPELLCHECK: const.EventCode
KEY_LOGOFF: const.EventCode
KEY_DOLLAR: const.EventCode
KEY_EURO: const.EventCode
KEY_FRAMEBACK: const.EventCode
KEY_FRAMEFORWARD: const.EventCode
KEY_CONTEXT_MENU: const.EventCode
KEY_MEDIA_REPEAT: const.EventCode
KEY_10CHANNELSUP: const.EventCode
KEY_10CHANNELSDOWN: const.EventCode
KEY_IMAGES: const.EventCode
KEY_NOTIFICATION_CENTER: const.EventCode
KEY_PICKUP_PHONE: const.EventCode
KEY_HANGUP_PHONE: const.EventCode
KEY_LINK_PHONE: const.EventCode
KEY_DEL_EOL: const.EventCode
KEY_DEL_EOS: const.EventCode
KEY_INS_LINE: const.EventCode
KEY_DEL_LINE: const.EventCode
KEY_FN: const.EventCode
KEY_FN_ESC: const.EventCode
KEY_FN_F1: const.EventCode
KEY_FN_F2: const.EventCode
KEY_FN_F3: const.EventCode
KEY_FN_F4: const.EventCode
KEY_FN_F5: const.EventCode
KEY_FN_F6: const.EventCode
KEY_FN_F7: const.EventCode
KEY_FN_F8: const.EventCode
KEY_FN_F9: const.EventCode
KEY_FN_F10: const.EventCode
KEY_FN_F11: const.EventCode
KEY_FN_F12: const.EventCode
KEY_FN_1: const.EventCode
KEY_FN_2: const.EventCode
KEY_FN_D: const.EventCode
KEY_FN_E: const.EventCode
KEY_FN_F: const.EventCode
KEY_FN_S: const.EventCode
KEY_FN_B: const.EventCode
KEY_FN_RIGHT_SHIFT: const.EventCode
KEY_BRL_DOT1: const.EventCode
KEY_BRL_DOT2: const.EventCode
KEY_BRL_DOT3: const.EventCode
KEY_BRL_DOT4: const.EventCode
KEY_BRL_DOT5: const.EventCode
KEY_BRL_DOT6: const.EventCode
KEY_BRL_DOT7: const.EventCode
KEY_BRL_DOT8: const.EventCode
KEY_BRL_DOT9: const.EventCode
KEY_BRL_DOT10: const.EventCode
KEY_NUMERIC_0: const.EventCode
KEY_NUMERIC_1: const.EventCode
KEY_NUMERIC_2: const.EventCode
KEY_NUMERIC_3: const.EventCode
KEY_NUMERIC_4: const.EventCode
KEY_NUMERIC_5: const.EventCode
KEY_NUMERIC_6: const.EventCode
KEY_NUMERIC_7: const.EventCode
KEY_NUMERIC_8: const.EventCode
KEY_NUMERIC_9: const.EventCode
KEY_NUMERIC_STAR: const.EventCode
KEY_NUMERIC_POUND: const.EventCode
KEY_NUMERIC_A: const.EventCode
KEY_NUMERIC_B: const.EventCode
KEY_NUMERIC_C: const.EventCode
KEY_NUMERIC_D: const.EventCode
KEY_CAMERA_FOCUS: const.EventCode
KEY_WPS_BUTTON: const.EventCode
KEY_TOUCHPAD_TOGGLE: const.EventCode
KEY_TOUCHPAD_ON: const.EventCode
KEY_TOUCHPAD_OFF: const.EventCode
KEY_CAMERA_ZOOMIN: const.EventCode
KEY_CAMERA_ZOOMOUT: const.EventCode
KEY_CAMERA_UP: const.EventCode
KEY_CAMERA_DOWN: const.EventCode
KEY_CAMERA_LEFT: const.EventCode
KEY_CAMERA_RIGHT: const.EventCode
KEY_ATTENDANT_ON: const.EventCode
KEY_ATTENDANT_OFF: const.EventCode
KEY_ATTENDANT_TOGGLE: const.EventCode
KEY_LIGHTS_TOGGLE: const.EventCode
BTN_DPAD_UP: const.EventCode
BTN_DPAD_DOWN: const.EventCode
BTN_DPAD_LEFT: const.EventCode
BTN_DPAD_RIGHT: const.EventCode
BTN_GRIPL: const.EventCode
BTN_GRIPR: const.EventCode
BTN_GRIPL2: const.EventCode
BTN_GRIPR2: const.EventCode
KEY_ALS_TOGGLE: const.EventCode
KEY_ROTATE_LOCK_TOGGLE: const.EventCode
KEY_REFRESH_RATE_TOGGLE: const.EventCode
KEY_BUTTONCONFIG: const.EventCode
KEY_TASKMANAGER: const.EventCode
KEY_JOURNAL: const.EventCode
KEY_CONTROLPANEL: const.EventCode
KEY_APPSELECT: const.EventCode
KEY_SCREENSAVER: const.EventCode
KEY_VOICECOMMAND: const.EventCode
KEY_ASSISTANT: const.EventCode
KEY_KBD_LAYOUT_NEXT: const.EventCode
KEY_EMOJI_PICKER: const.EventCode
KEY_DICTATE: const.EventCode
KEY_CAMERA_ACCESS_ENABLE: const.EventCode
KEY_CAMERA_ACCESS_DISABLE: const.EventCode
KEY_CAMERA_ACCESS_TOGGLE: const.EventCode
KEY_ACCESSIBILITY: const.EventCode
KEY_DO_NOT_DISTURB: const.EventCode
KEY_BRIGHTNESS_MIN: const.EventCode
KEY_BRIGHTNESS_MAX: const.EventCode
KEY_KBDINPUTASSIST_PREV: const.EventCode
KEY_KBDINPUTASSIST_NEXT: const.EventCode
KEY_KBDINPUTASSIST_PREVGROUP: const.EventCode
KEY_KBDINPUTASSIST_NEXTGROUP: const.EventCode
KEY_KBDINPUTASSIST_ACCEPT: const.EventCode
KEY_KBDINPUTASSIST_CANCEL: const.EventCode
KEY_RIGHT_UP: const.EventCode
KEY_RIGHT_DOWN: const.EventCode
KEY_LEFT_UP: const.EventCode
KEY_LEFT_DOWN: const.EventCode
KEY_ROOT_MENU: const.EventCode
KEY_MEDIA_TOP_MENU: const.EventCode
KEY_NUMERIC_11: const.EventCode
KEY_NUMERIC_12: const.EventCode
KEY_AUDIO_DESC: const.EventCode
KEY_3D_MODE: const.EventCode
KEY_NEXT_FAVORITE: const.EventCode
KEY_STOP_RECORD: const.EventCode
KEY_PAUSE_RECORD: const.EventCode
KEY_VOD: const.EventCode
KEY_UNMUTE: const.EventCode
KEY_FASTREVERSE: const.EventCode
KEY_SLOWREVERSE: const.EventCode
KEY_DATA: const.EventCode
KEY_ONSCREEN_KEYBOARD: const.EventCode
KEY_PRIVACY_SCREEN_TOGGLE: const.EventCode
KEY_SELECTIVE_SCREENSHOT: const.EventCode
KEY_NEXT_ELEMENT: const.EventCode
KEY_PREVIOUS_ELEMENT: const.EventCode
KEY_AUTOPILOT_ENGAGE_TOGGLE: const.EventCode
KEY_MARK_WAYPOINT: const.EventCode
KEY_SOS: const.EventCode
KEY_NAV_CHART: const.EventCode
KEY_FISHING_CHART: const.EventCode
KEY_SINGLE_RANGE_RADAR: const.EventCode
KEY_DUAL_RANGE_RADAR: const.EventCode
KEY_RADAR_OVERLAY: const.EventCode
KEY_TRADITIONAL_SONAR: const.EventCode
KEY_CLEARVU_SONAR: const.EventCode
KEY_SIDEVU_SONAR: const.EventCode
KEY_NAV_INFO: const.EventCode
KEY_BRIGHTNESS_MENU: const.EventCode
KEY_MACRO1: const.EventCode
KEY_MACRO2: const.EventCode
KEY_MACRO3: const.EventCode
KEY_MACRO4: const.EventCode
KEY_MACRO5: const.EventCode
KEY_MACRO6: const.EventCode
KEY_MACRO7: const.EventCode
KEY_MACRO8: const.EventCode
KEY_MACRO9: const.EventCode
KEY_MACRO10: const.EventCode
KEY_MACRO11: const.EventCode
KEY_MACRO12: const.EventCode
KEY_MACRO13: const.EventCode
KEY_MACRO14: const.EventCode
KEY_MACRO15: const.EventCode
KEY_MACRO16: const.EventCode
KEY_MACRO17: const.EventCode
KEY_MACRO18: const.EventCode
KEY_MACRO19: const.EventCode
KEY_MACRO20: const.EventCode
KEY_MACRO21: const.EventCode
KEY_MACRO22: const.EventCode
KEY_MACRO23: const.EventCode
KEY_MACRO24: const.EventCode
KEY_MACRO25: const.EventCode
KEY_MACRO26: const.EventCode
KEY_MACRO27: const.EventCode
KEY_MACRO28: const.EventCode
KEY_MACRO29: const.EventCode
KEY_MACRO30: const.EventCode
KEY_MACRO_RECORD_START: const.EventCode
KEY_MACRO_RECORD_STOP: const.EventCode
KEY_MACRO_PRESET_CYCLE: const.EventCode
KEY_MACRO_PRESET1: const.EventCode
KEY_MACRO_PRESET2: const.EventCode
KEY_MACRO_PRESET3: const.EventCode
KEY_KBD_LCD_MENU1: const.EventCode
KEY_KBD_LCD_MENU2: const.EventCode
KEY_KBD_LCD_MENU3: const.EventCode
KEY_KBD_LCD_MENU4: const.EventCode
KEY_KBD_LCD_MENU5: const.EventCode
KEY_PERFORMANCE: const.EventCode
BTN_TRIGGER_HAPPY1: const.EventCode
BTN_TRIGGER_HAPPY2: const.EventCode
BTN_TRIGGER_HAPPY3: const.EventCode
BTN_TRIGGER_HAPPY4: const.EventCode
BTN_TRIGGER_HAPPY5: const.EventCode
BTN_TRIGGER_HAPPY6: const.EventCode
BTN_TRIGGER_HAPPY7: const.EventCode
BTN_TRIGGER_HAPPY8: const.EventCode
BTN_TRIGGER_HAPPY9: const.EventCode
BTN_TRIGGER_HAPPY10: const.EventCode
BTN_TRIGGER_HAPPY11: const.EventCode
BTN_TRIGGER_HAPPY12: const.EventCode
BTN_TRIGGER_HAPPY13: const.EventCode
BTN_TRIGGER_HAPPY14: const.EventCode
BTN_TRIGGER_HAPPY15: const.EventCode
BTN_TRIGGER_HAPPY16: const.EventCode
BTN_TRIGGER_HAPPY17: const.EventCode
BTN_TRIGGER_HAPPY18: const.EventCode
BTN_TRIGGER_HAPPY19: const.EventCode
BTN_TRIGGER_HAPPY20: const.EventCode
BTN_TRIGGER_HAPPY21: const.EventCode
BTN_TRIGGER_HAPPY22: const.EventCode
BTN_TRIGGER_HAPPY23: const.EventCode
BTN_TRIGGER_HAPPY24: const.EventCode
BTN_TRIGGER_HAPPY25: const.EventCode
BTN_TRIGGER_HAPPY26: const.EventCode
BTN_TRIGGER_HAPPY27: const.EventCode
BTN_TRIGGER_HAPPY28: const.EventCode
BTN_TRIGGER_HAPPY29: const.EventCode
BTN_TRIGGER_HAPPY30: const.EventCode
BTN_TRIGGER_HAPPY31: const.EventCode
BTN_TRIGGER_HAPPY32: const.EventCode
BTN_TRIGGER_HAPPY33: const.EventCode
BTN_TRIGGER_HAPPY34: const.EventCode
BTN_TRIGGER_HAPPY35: const.EventCode
BTN_TRIGGER_HAPPY36: const.EventCode
BTN_TRIGGER_HAPPY37: const.EventCode
BTN_TRIGGER_HAPPY38: const.EventCode
BTN_TRIGGER_HAPPY39: const.EventCode
BTN_TRIGGER_HAPPY40: const.EventCode
KEY_AI_ASSISTANT: const.EventCode
KEY_MAX: const.EventCode
REL_X: const.EventCode
REL_Y: const.EventCode
REL_Z: const.EventCode
REL_RX: const.EventCode
REL_RY: const.EventCode
REL_RZ: const.EventCode
REL_HWHEEL: const.EventCode
REL_DIAL: const.EventCode
REL_WHEEL: const.EventCode
REL_MISC: const.EventCode
REL_RESERVED: const.EventCode
REL_WHEEL_HI_RES: const.EventCode
REL_HWHEEL_HI_RES: const.EventCode
REL_MAX: const.EventCode
ABS_X: const.EventCode
ABS_Y: const.EventCode
ABS_Z: const.EventCode
ABS_RX: const.EventCode
ABS_RY: const.EventCode
ABS_RZ: const.EventCode
ABS_THROTTLE: const.EventCode
ABS_RUDDER: const.EventCode
ABS_WHEEL: const.EventCode
ABS_GAS: const.EventCode
ABS_BRAKE: const.EventCode
ABS_HAT0X: const.EventCode
ABS_HAT0Y: const.EventCode
ABS_HAT1X: const.EventCode
ABS_HAT1Y: const.EventCode
ABS_HAT2X: const.EventCode
ABS_HAT2Y: const.EventCode
ABS_HAT3X: const.EventCode
ABS_HAT3Y: const.EventCode
ABS_PRESSURE: const.EventCode
ABS_DISTANCE: const.EventCode
ABS_TILT_X: const.EventCode
ABS_TILT_Y: const.EventCode
ABS_TOOL_WIDTH: const.EventCode
ABS_VOLUME: const.EventCode
ABS_PROFILE: const.EventCode
ABS_MISC: const.EventCode
ABS_RESERVED: const.EventCode
ABS_MT_SLOT: const.EventCode
ABS_MT_TOUCH_MAJOR: const.EventCode
ABS_MT_TOUCH_MINOR: const.EventCode
ABS_MT_WIDTH_MAJOR: const.EventCode
ABS_MT_WIDTH_MINOR: const.EventCode
ABS_MT_ORIENTATION: const.EventCode
ABS_MT_POSITION_X: const.EventCode
ABS_MT_POSITION_Y: const.EventCode
ABS_MT_TOOL_TYPE: const.EventCode
ABS_MT_BLOB_ID: const.EventCode
ABS_MT_TRACKING_ID: const.EventCode
ABS_MT_PRESSURE: const.EventCode
ABS_MT_DISTANCE: const.EventCode
ABS_MT_TOOL_X: const.EventCode
ABS_MT_TOOL_Y: const.EventCode
ABS_MAX: const.EventCode
MSC_SERIAL: const.EventCode
MSC_PULSELED: const.EventCode
MSC_GESTURE: const.EventCode
MSC_RAW: const.EventCode
MSC_SCAN: const.EventCode
MSC_TIMESTAMP: const.EventCode
MSC_MAX: const.EventCode
SW_LID: const.EventCode
SW_TABLET_MODE: const.EventCode
SW_HEADPHONE_INSERT: const.EventCode
SW_RFKILL_ALL: const.EventCode
SW_MICROPHONE_INSERT: const.EventCode
SW_DOCK: const.EventCode
SW_LINEOUT_INSERT: const.EventCode
SW_JACK_PHYSICAL_INSERT: const.EventCode
SW_VIDEOOUT_INSERT: const.EventCode
SW_CAMERA_LENS_COVER: const.EventCode
SW_KEYPAD_SLIDE: const.EventCode
SW_FRONT_PROXIMITY: const.EventCode
SW_ROTATE_LOCK: const.EventCode
SW_LINEIN_INSERT: const.EventCode
SW_MUTE_DEVICE: const.EventCode
SW_PEN_INSERTED: const.EventCode
SW_MACHINE_COVER: const.EventCode
SW_USB_INSERT: const.EventCode
LED_NUML: const.EventCode
LED_CAPSL: const.EventCode
LED_SCROLLL: const.EventCode
LED_COMPOSE: const.EventCode
LED_KANA: const.EventCode
LED_SLEEP: const.EventCode
LED_SUSPEND: const.EventCode
LED_MUTE: const.EventCode
LED_MISC: const.EventCode
LED_MAIL: const.EventCode
LED_CHARGING: const.EventCode
LED_MAX: const.EventCode
SND_CLICK: const.EventCode
SND_BELL: const.EventCode
SND_TONE: const.EventCode
SND_MAX: const.EventCode
REP_DELAY: const.EventCode
REP_PERIOD: const.EventCode
FF_STATUS_STOPPED: const.EventCode
FF_STATUS_MAX: const.EventCode
FF_RUMBLE: const.EventCode
FF_PERIODIC: const.EventCode
FF_CONSTANT: const.EventCode
FF_SPRING: const.EventCode
FF_FRICTION: const.EventCode
FF_DAMPER: const.EventCode
FF_INERTIA: const.EventCode
FF_RAMP: const.EventCode
FF_SQUARE: const.EventCode
FF_TRIANGLE: const.EventCode
FF_SINE: const.EventCode
FF_SAW_UP: const.EventCode
FF_SAW_DOWN: const.EventCode
FF_CUSTOM: const.EventCode
FF_GAIN: const.EventCode
FF_AUTOCENTER: const.EventCode
FF_MAX: const.EventCode
INPUT_PROP_POINTER: const.InputProperty
INPUT_PROP_DIRECT: const.InputProperty
INPUT_PROP_BUTTONPAD: const.InputProperty
INPUT_PROP_SEMI_MT: const.InputProperty
INPUT_PROP_TOPBUTTONPAD: const.InputProperty
INPUT_PROP_POINTING_STICK: const.InputProperty
INPUT_PROP_ACCELEROMETER: const.InputProperty
INPUT_PROP_MAX: const.InputProperty
types: list[const.EventType]
props: list[const.InputProperty]
