# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.field_lookup import FieldLookup

class TestFieldLookup(unittest.TestCase):
    """FieldLookup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldLookup:
        """Test FieldLookup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldLookup`
        """
        model = FieldLookup()
        if include_optional:
            return FieldLookup(
                column_id = '',
                version = 1.337,
                validation_status = 'valid',
                invalid_data = do_sdk_platform.models.invalid_data.InvalidData(
                    message = '', ),
                type = 'lookup',
                system_type = 'name',
                value = None
            )
        else:
            return FieldLookup(
                column_id = '',
                validation_status = 'valid',
                type = 'lookup',
        )
        """

    def testFieldLookup(self):
        """Test FieldLookup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
