# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.user_schema_dto import UserSchemaDto

class TestUserSchemaDto(unittest.TestCase):
    """UserSchemaDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSchemaDto:
        """Test UserSchemaDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSchemaDto`
        """
        model = UserSchemaDto()
        if include_optional:
            return UserSchemaDto(
                first_name = '',
                last_name = '',
                email = '',
                auth_id = '',
                company = '',
                title = '',
                pending_invites = [
                    ''
                    ]
            )
        else:
            return UserSchemaDto(
                first_name = '',
                last_name = '',
                email = '',
                auth_id = '',
        )
        """

    def testUserSchemaDto(self):
        """Test UserSchemaDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
