# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.files_post_url_file200_response import FilesPostUrlFile200Response

class TestFilesPostUrlFile200Response(unittest.TestCase):
    """FilesPostUrlFile200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilesPostUrlFile200Response:
        """Test FilesPostUrlFile200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilesPostUrlFile200Response`
        """
        model = FilesPostUrlFile200Response()
        if include_optional:
            return FilesPostUrlFile200Response(
                e_tag = ''
            )
        else:
            return FilesPostUrlFile200Response(
        )
        """

    def testFilesPostUrlFile200Response(self):
        """Test FilesPostUrlFile200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
