# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.column_reference_base import ColumnReferenceBase

class TestColumnReferenceBase(unittest.TestCase):
    """ColumnReferenceBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ColumnReferenceBase:
        """Test ColumnReferenceBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ColumnReferenceBase`
        """
        model = ColumnReferenceBase()
        if include_optional:
            return ColumnReferenceBase(
                type = 'reference',
                reference_database_row_id = ''
            )
        else:
            return ColumnReferenceBase(
                type = 'reference',
                reference_database_row_id = '',
        )
        """

    def testColumnReferenceBase(self):
        """Test ColumnReferenceBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
