# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.data_platform_create_one_request import DataPlatformCreateOneRequest

class TestDataPlatformCreateOneRequest(unittest.TestCase):
    """DataPlatformCreateOneRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataPlatformCreateOneRequest:
        """Test DataPlatformCreateOneRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataPlatformCreateOneRequest`
        """
        model = DataPlatformCreateOneRequest()
        if include_optional:
            return DataPlatformCreateOneRequest(
                set = {
                    'key' : null
                    },
                returning = [
                    ''
                    ]
            )
        else:
            return DataPlatformCreateOneRequest(
                set = {
                    'key' : null
                    },
        )
        """

    def testDataPlatformCreateOneRequest(self):
        """Test DataPlatformCreateOneRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
