# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.chat_thread import ChatThread

class TestChatThread(unittest.TestCase):
    """ChatThread unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatThread:
        """Test ChatThread
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatThread`
        """
        model = ChatThread()
        if include_optional:
            return ChatThread(
                id = '',
                openai_id = '',
                created_by_user_drn = '',
                created_at = ''
            )
        else:
            return ChatThread(
                id = '',
                openai_id = '',
                created_at = '',
        )
        """

    def testChatThread(self):
        """Test ChatThread"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
