# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.add_column_reference import AddColumnReference

class TestAddColumnReference(unittest.TestCase):
    """AddColumnReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddColumnReference:
        """Test AddColumnReference
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddColumnReference`
        """
        model = AddColumnReference()
        if include_optional:
            return AddColumnReference(
                type = 'reference',
                reference_database_row_id = '',
                name = '/UR,rZ',
                json_field = '',
                cardinality = 'one',
                system_type = 'name',
                is_required = True,
                enabled_viewers = [
                    'code'
                    ],
                cell_json_schema = None,
                inline_viewer = 'molecule2d'
            )
        else:
            return AddColumnReference(
                type = 'reference',
                reference_database_row_id = '',
                name = '/UR,rZ',
                cardinality = 'one',
        )
        """

    def testAddColumnReference(self):
        """Test AddColumnReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
