# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.add_column_float import AddColumnFloat

class TestAddColumnFloat(unittest.TestCase):
    """AddColumnFloat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddColumnFloat:
        """Test AddColumnFloat
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddColumnFloat`
        """
        model = AddColumnFloat()
        if include_optional:
            return AddColumnFloat(
                type = 'float',
                config_numeric = do_sdk_platform.models.column_float_base_config_numeric.ColumnFloatBase_configNumeric(
                    unit = '', 
                    number_format = do_sdk_platform.models.number_format.NumberFormat(
                        minimum_fraction_digits = 0, 
                        maximum_fraction_digits = 0, 
                        minimum_significant_digits = 1, 
                        maximum_significant_digits = 1, ), ),
                name = '/UR,rZ',
                json_field = '',
                cardinality = 'one',
                system_type = 'name',
                is_required = True,
                enabled_viewers = [
                    'code'
                    ],
                cell_json_schema = None,
                inline_viewer = 'molecule2d'
            )
        else:
            return AddColumnFloat(
                type = 'float',
                name = '/UR,rZ',
                cardinality = 'one',
        )
        """

    def testAddColumnFloat(self):
        """Test AddColumnFloat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
