---
Title: "WOW Power BI 2023 week 52 demonstration"
---

# What you'll learn
This blog post shows how I used the PowerBpy python module to recreate an example dashboard from the <a href="https://workout-wednesday.com/">Workout Wednesday Group</a>. This particular example recreates the dashboard from the <a href="https://workout-wednesday.com/pbi-2023-w52/">2023 Week 52 | Power BI: Format Bar Charts with Transparency, Borders, and Detail Labels</a> challenge. 

# Setup   
## Assumptions
This example assumes that you already have python installed and setup and that you know how to install python modules such as pandas. 

## Obtain and prepare data
One of the central assumptions built into the PowerBpy package is that you'd prefer to write python code over using Power BI. Therefore this example will use garden variety python including standard modules for data science to load and transform the data. Once the data is ready will use PowerBpy to create the dashboard. 

The data for this example is provided as a pdf file that you're supposed to import using a Power BI pdf importer and then manipulate the data using DAX. Instead we'll use python to read the text from the pdf and then parse and clean the data from the extracted text. 

```python



```

