"""Type stubs for liru package."""

import types

__version__: str

class Sender:
    """Spout sender for sharing GPU textures."""

    def __init__(self, name: str, width: int, height: int) -> None: ...
    def send_texture(self, texture_id: int) -> None: ...
    def release(self) -> None: ...
    def get_fps(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def last_send_time_ms(self) -> float: ...
    def __enter__(self) -> Sender: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Receiver:
    """Spout receiver for receiving GPU textures."""

    def __init__(self, sender_name: str = "") -> None: ...
    def receive_texture(self, texture_id: int) -> tuple[int, int]: ...
    def is_updated(self) -> bool: ...
    def select_sender(self, name: str) -> None: ...
    def get_sender_list(self) -> list[str]: ...
    @property
    def active_sender(self) -> str: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def last_receive_time_ms(self) -> float: ...
    def __enter__(self) -> Receiver: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

__all__ = ["Sender", "Receiver", "__version__"]
