"""
------------------------------------------------------------------------------
<auto-generated>
    This code was auto-generated by main/tools/jsonparser.
    Do not change this file.
</auto-generated>
------------------------------------------------------------------------------
"""
import json
import sys
import re
from six import string_types
from .ClusterRequestStatus import ClusterRequestStatus

# Unused import over optimization prevention
str(repr(ClusterRequestStatus))


if sys.version_info > (3,):
    long = int
    unicode = str

class ClusterSuccessResponse(object):
    """Cluster Success Response"""
    def __init__(self, propDict=None):
        fromDict = propDict is not None and isinstance(propDict, dict)
        self.clusterStatus = (
            None if not fromDict or propDict.get(
                "clusterStatus"
            ) is None
            else propDict["clusterStatus"])
        self.version = (
            None if not fromDict or propDict.get(
                "version"
            ) is None
            else propDict["version"])

    @property
    def clusterStatus(self):
        """ClusterRequestStatus: Cluster Request status"""
        return self._clusterStatus

    @clusterStatus.setter
    def clusterStatus(self, value):
        if value is not None and not isinstance(value, ClusterRequestStatus):
            value = ClusterRequestStatus(value)
        if (value is None) or isinstance(value, ClusterRequestStatus):
            self._clusterStatus = value
        else:
            raise TypeError(
                'Property "clusterStatus" of type "list<ClusterRequestStatus>'
                '" set to wrong type'
            )

    @property
    def version(self):
        """str: Payload version"""
        return self._version

    @version.setter
    def version(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._version = value
        else:
            raise TypeError(
                'Property "version" of type "list<str>" set to wrong type'
            )

    def toDict(self):
        result = {}
        if self._clusterStatus:
            result["clusterStatus"] = \
                self._clusterStatus.toDict() if self._clusterStatus is not None else None
        if self._version is not None:
            result["version"] = \
                self._version
        return result

    def toJSON(self, pretty=False):
        if pretty:
            return json.dumps(self.toDict(), sort_keys=True, indent=4)
        else:
            return json.dumps(self.toDict(), sort_keys=True)

    def isValid(self):
        if self._version is None:
            raise ValueError(
                "ClusterSuccessResponse.version doesnt match requirement:" 
                "required: True"
            )
        if self._clusterStatus is None:
            raise ValueError(
                "ClusterSuccessResponse.clusterStatus doesnt match requirement:" 
                "required: True"
            )
        if (self._clusterStatus is not None): self._clusterStatus.isValid()
        return True
    

