# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from fireblocks.models.create_quote_scope_inner import CreateQuoteScopeInner
from fireblocks.models.dvp_settlement import DVPSettlement
from fireblocks.models.transfer_rail import TransferRail
from typing import Optional, Set
from typing_extensions import Self

class CreateQuote(BaseModel):
    """
    CreateQuote
    """ # noqa: E501
    scope: List[CreateQuoteScopeInner]
    base_asset_id: StrictStr = Field(alias="baseAssetId")
    base_asset_rail: Optional[TransferRail] = Field(default=None, alias="baseAssetRail")
    quote_asset_id: StrictStr = Field(alias="quoteAssetId")
    quote_asset_rail: Optional[TransferRail] = Field(default=None, alias="quoteAssetRail")
    base_amount: Annotated[str, Field(strict=True)] = Field(description="The amount to convert from", alias="baseAmount")
    slippage_bps: Optional[Union[Annotated[float, Field(le=10000, strict=True, ge=1)], Annotated[int, Field(le=10000, strict=True, ge=1)]]] = Field(default=50, description="Slippage tolerance in basis points (bps) for defi quotes - 1 is 0.01% and 10000 is 100%", alias="slippageBps")
    settlement: Optional[DVPSettlement] = None
    side: StrictStr = Field(description="Side of the order")
    __properties: ClassVar[List[str]] = ["scope", "baseAssetId", "baseAssetRail", "quoteAssetId", "quoteAssetRail", "baseAmount", "slippageBps", "settlement", "side"]

    @field_validator('base_amount')
    def base_amount_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)?$/")
        return value

    @field_validator('side')
    def side_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['BUY', 'SELL']):
            raise ValueError("must be one of enum values ('BUY', 'SELL')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateQuote from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in scope (list)
        _items = []
        if self.scope:
            for _item_scope in self.scope:
                if _item_scope:
                    _items.append(_item_scope.to_dict())
            _dict['scope'] = _items
        # override the default output from pydantic by calling `to_dict()` of settlement
        if self.settlement:
            _dict['settlement'] = self.settlement.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateQuote from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scope": [CreateQuoteScopeInner.from_dict(_item) for _item in obj["scope"]] if obj.get("scope") is not None else None,
            "baseAssetId": obj.get("baseAssetId"),
            "baseAssetRail": obj.get("baseAssetRail"),
            "quoteAssetId": obj.get("quoteAssetId"),
            "quoteAssetRail": obj.get("quoteAssetRail"),
            "baseAmount": obj.get("baseAmount"),
            "slippageBps": obj.get("slippageBps") if obj.get("slippageBps") is not None else 50,
            "settlement": DVPSettlement.from_dict(obj["settlement"]) if obj.get("settlement") is not None else None,
            "side": obj.get("side")
        })
        return _obj


