from _typeshed import Incomplete

class Buffer:
    max_size: Incomplete
    def __init__(self, max_size: int = 65536) -> None: ...
    def write(self, data: bytes) -> int: ...
    def read(self, size: int = -1) -> bytes: ...
    def peek(self, size: int = -1) -> bytes: ...
    def clear(self) -> None: ...
    @property
    def size(self) -> int: ...
