import asyncio
from .buffer import Buffer as Buffer
from .flow_control import FlowControl as FlowControl
from _typeshed import Incomplete
from typing import Any

class Connection:
    reader: Incomplete
    writer: Incomplete
    buffer: Incomplete
    flow_control: Incomplete
    def __init__(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter, buffer_size: int = 65536) -> None: ...
    @property
    def closed(self) -> bool: ...
    async def read(self, n: int = -1) -> bytes: ...
    async def write(self, data: bytes | bytearray) -> None: ...
    async def close(self) -> None: ...
    def get_extra_info(self, name: str) -> Any | None: ...
    @property
    def peer(self) -> str: ...
