from _typeshed import Incomplete
from typing import Any

class SSOError(Exception):
    message: Incomplete
    error_code: Incomplete
    provider: Incomplete
    extra: Incomplete
    def __init__(self, message: str, error_code: str | None = None, provider: str | None = None, **kwargs: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class SSOProviderError(SSOError):
    def __init__(self, message: str, provider: str, error_code: str | None = None, **kwargs: Any) -> None: ...

class SSOAuthError(SSOError):
    def __init__(self, message: str, provider: str, error_code: str | None = None, **kwargs: Any) -> None: ...

class SSOConfigError(SSOError):
    def __init__(self, message: str, provider: str | None = None, **kwargs: Any) -> None: ...

class SSOUserNotFoundError(SSOError):
    def __init__(self, message: str = 'User not found', provider: str | None = None, user_id: str | None = None, **kwargs: Any) -> None: ...

class SSOProviderNotFoundError(SSOError):
    def __init__(self, provider: str, **kwargs: Any) -> None: ...

class SSOInvalidStateError(SSOError):
    def __init__(self, message: str = 'Invalid or expired state parameter', state: str | None = None, **kwargs: Any) -> None: ...

class SSOAuthCancelledError(SSOError):
    def __init__(self, provider: str, **kwargs: Any) -> None: ...

class SSOAuthTimeoutError(SSOError):
    def __init__(self, provider: str, timeout_seconds: int | None = None, **kwargs: Any) -> None: ...

class SSOInvalidCredentialsError(SSOError):
    def __init__(self, provider: str, **kwargs: Any) -> None: ...

class SSOAccessDeniedError(SSOError):
    def __init__(self, provider: str, reason: str | None = None, **kwargs: Any) -> None: ...

class SSOProviderUnavailableError(SSOError):
    def __init__(self, provider: str, **kwargs: Any) -> None: ...

class SSOInvalidResponseError(SSOError):
    def __init__(self, provider: str, response_data: Any | None = None, **kwargs: Any) -> None: ...

class SSOTokenExpiredError(SSOError):
    def __init__(self, provider: str, token_type: str | None = None, **kwargs: Any) -> None: ...

class SSOInvalidTokenError(SSOError):
    def __init__(self, provider: str, token_type: str | None = None, **kwargs: Any) -> None: ...

class SSORateLimitError(SSOError):
    def __init__(self, provider: str, retry_after: int | None = None, **kwargs: Any) -> None: ...

class SSONetworkError(SSOError):
    def __init__(self, provider: str, original_error: Exception | None = None, **kwargs: Any) -> None: ...

class SSOValidationError(SSOError):
    def __init__(self, message: str, field: str | None = None, value: Any | None = None, **kwargs: Any) -> None: ...

class SSOUnsupportedProviderError(SSOError):
    def __init__(self, provider: str, **kwargs: Any) -> None: ...

class SSOProviderConfigurationError(SSOError):
    def __init__(self, provider: str, config_field: str | None = None, **kwargs: Any) -> None: ...

class SSOUserMappingError(SSOError):
    def __init__(self, provider: str, sso_user_data: dict[str, Any] | None = None, **kwargs: Any) -> None: ...

class SSOAttributeMappingError(SSOError):
    def __init__(self, provider: str, attribute: str | None = None, **kwargs: Any) -> None: ...
