import types
from .config import SSOConfig as SSOConfig
from .exceptions import SSOConfigError as SSOConfigError, SSOProviderNotFoundError as SSOProviderNotFoundError, SSOUnsupportedProviderError as SSOUnsupportedProviderError
from .models import SSOAuthResult as SSOAuthResult, SSOAuthState as SSOAuthState, SSOUser as SSOUser, create_auth_state as create_auth_state
from .providers import SSOProvider as SSOProvider, create_sso_provider as create_sso_provider
from _typeshed import Incomplete
from datetime import datetime as datetime, timedelta as timedelta
from typing import Any

class SSOManager:
    config: Incomplete
    logger: Incomplete
    providers: dict[str, SSOProvider]
    auth_states: dict[str, SSOAuthState]
    def __init__(self, config: SSOConfig) -> None: ...
    def get_provider(self, provider_name: str) -> SSOProvider: ...
    def get_available_providers(self) -> list[str]: ...
    def is_provider_available(self, provider_name: str) -> bool: ...
    def create_auth_state(self, provider: str, redirect_url: str | None = None, user_id: str | None = None, **kwargs: Any) -> SSOAuthState: ...
    def get_auth_state(self, state: str) -> SSOAuthState | None: ...
    def mark_auth_state_used(self, state: str) -> None: ...
    def get_authorization_url(self, provider: str, redirect_url: str | None = None, user_id: str | None = None, **kwargs: Any) -> str: ...
    async def authenticate(self, provider: str, code: str, state: str) -> SSOAuthResult: ...
    async def get_user_info(self, provider: str, access_token: str) -> dict[str, Any]: ...
    def map_user_data(self, provider: str, user_data: dict[str, Any]) -> SSOUser: ...
    def get_provider_info(self, provider: str) -> dict[str, Any]: ...
    def get_all_providers_info(self) -> list[dict[str, Any]]: ...
    def cleanup_expired_states(self) -> int: ...
    def get_stats(self) -> dict[str, Any]: ...
    async def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
