# Generated by Django 5.1.7 on 2025-03-29 13:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feed_url", models.URLField(db_index=True, unique=True)),
                ("cache_date", models.DateTimeField(null=True)),
                ("feed_body", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FilteredFeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("feed_url", models.URLField()),
                ("filtered_words", models.CharField(blank=True, max_length=1024)),
                ("filtered_categories", models.CharField(blank=True, max_length=1024)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("cache_date", models.DateTimeField(editable=False, null=True)),
                ("filtered_feed_body", models.TextField(editable=False)),
            ],
        ),
    ]
