"""Type stubs for provider configuration"""

from pathlib import Path
from typing import Any

class ProviderConfig:
    """Manages provider configuration with environment variable substitution."""

    config_path: Path

    def __init__(self, config_path: Path | str | None = None) -> None: ...
    def load(self) -> None: ...
    def get(self, path: str, default: Any = None) -> Any: ...
    def get_text_config(self, provider_name: str) -> dict[str, Any]: ...
    def get_image_config(self, provider_name: str) -> dict[str, Any]: ...
    def get_audio_config(self, provider_name: str) -> dict[str, Any]: ...
    def get_role_config(
        self, role_name: str, *args: Any, **kwargs: Any
    ) -> dict[str, Any]: ...
    def get_role_provider(
        self, role_name: str, *args: Any, **kwargs: Any
    ) -> str | None: ...
    def get_default_text_provider(self) -> str | None: ...
    def get_default_image_provider(self) -> str | None: ...
    def get_default_audio_provider(self) -> str | None: ...
