from _typeshed import Incomplete
from collections.abc import Callable as Callable
from typing_extensions import Annotated
from zephyr._types import (
    ASGIApp as ASGIApp,
    AppType as AppType,
    Lifespan as Lifespan,
    Receive as Receive,
    Scope as Scope,
    Send as Send,
)
from zephyr.app import routing as routing
from zephyr.app._utils import generate_unique_id as generate_unique_id
from zephyr.app.datastructures import Default as Default, State as State
from zephyr.app.middleware import Middleware as Middleware
from zephyr.app.requests import Request as Request
from zephyr.app.responses import Response as Response
from zephyr.app.routing import BaseRoute as BaseRoute
from zephyr.conf import settings as settings
from zephyr.core.logging import get_logger as get_logger

class Zephyr:
    HOOKS: list[str]
    logger: Incomplete
    debug: Incomplete
    title: Incomplete
    version: Incomplete
    description: Incomplete
    root_path: Incomplete
    router: routing.Router
    state: Incomplete
    exception_handlers: Incomplete
    user_middleware: Incomplete
    middleware_stack: ASGIApp | None
    dependency_overrides: dict[Callable, Callable]
    _server: Incomplete
    _server_config: Incomplete
    _hooks: dict[str, Callable]
    def __init__(
        self,
        *,
        debug: bool | None = None,
        routes: Annotated[list[BaseRoute] | None, None, None] = None,
        title: Annotated[str, None] = "Zephyr",
        version: str = "1.0.0",
        description: str | None = None,
        root_path: str = "",
        lifespan: Annotated[Lifespan[AppType] | None, None] = None,
        generate_unique_id_function: Annotated[Callable[[routing.Route], str], None] = ...,
    ) -> None: ...
    def build_middleware_stack(self) -> ASGIApp: ...
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None: ...
    def get(self, path: str, *, status_code: int | None = None): ...
    def put(self, path: str, *, status_code: int | None = None): ...
    def post(self, path: str, *, status_code: int | None = None): ...
    def delete(self, path: str, *, status_code: int | None = None): ...
    def websocket(self, path: str, name: str | None = None): ...
    def middleware(self, middleware_class, *args, **kwargs): ...
    def add_middleware(self, middleware_class, *args, **kwargs): ...
    def use_cors(self, **kwargs): ...
    def configure_server(self, **kwargs): ...
    @property
    def server(self): ...
    def run(self, host: str = "127.0.0.1", port: int = 8000, **kwargs) -> None: ...
    async def serve(self, host: str = "127.0.0.1", port: int = 8000, **kwargs) -> None: ...
    def register_hook(self, hook_name: str): ...
    async def run_hook(self, hook_name: str) -> None: ...
    async def run_after_startup_hook(self) -> None: ...
    async def run_before_shutdown_hook(self) -> None: ...
    def on_event(self, event_type: str): ...
    def add_event_handler(self, event_type: str, func: Callable) -> None: ...
    def include_router(self, router: routing.Router, *, prefix: str = "", tags: list[str] | None = None) -> None: ...
    def mount(self, path: str, app: ASGIApp, name: str | None = None) -> None: ...
    def add_api_route(self, path: str, endpoint: Callable, **kwargs) -> None: ...
    def add_exception_handler(
        self, exc_class_or_status_code: int | type[Exception], handler: Callable[[Request, Exception], Response]
    ) -> None: ...
    def exception_handler(self, exc_class_or_status_code: int | type[Exception]): ...
