"""Type stubs for zephyr.app.websockets module."""

import enum
from typing import Any, AsyncIterator

from zephyr._types import Scope, Receive, Send, Message
from zephyr.app.requests import HTTPConnection

class WebSocketState(enum.Enum):
    CONNECTING: int
    CONNECTED: int
    DISCONNECTED: int
    RESPONSE: int

class WebSocketDisconnect(Exception):
    code: int
    reason: str
    def __init__(self, code: int = 1000, reason: str | None = None) -> None: ...

class WebSocket(HTTPConnection):
    client_state: WebSocketState
    application_state: WebSocketState
    def __init__(self, scope: Scope, receive: Receive, send: Send) -> None: ...
    async def accept(
        self,
        subprotocol: str | None = None,
        headers: list[tuple[bytes, bytes]] | None = None,
    ) -> None: ...
    async def receive(self) -> Message: ...
    async def receive_text(self) -> str: ...
    async def receive_bytes(self) -> bytes: ...
    async def receive_json(self, mode: str = "text") -> Any: ...
    async def send(self, message: Message) -> None: ...
    async def send_text(self, data: str) -> None: ...
    async def send_bytes(self, data: bytes) -> None: ...
    async def send_json(self, data: Any, mode: str = "text") -> None: ...
    async def close(self, code: int = 1000, reason: str | None = None) -> None: ...
    def iter_text(self) -> AsyncIterator[str]: ...
    def iter_bytes(self) -> AsyncIterator[bytes]: ...
    def iter_json(self) -> AsyncIterator[Any]: ...
