_DEFAULT_PYTHON_VERSION: str
_SELECTED_PYTHON_VERSION: str

def is_using_windows() -> bool: ...
def execute_python(*cmd: str, cwd: str | None = None) -> None: ...
def set_python_version(v: str = ...) -> None: ...
def get_current_python_version() -> list[str]: ...
