"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class RepositorySpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPOSITORY_KEY_FIELD_NUMBER: builtins.int
    PROJECT_KEY_FIELD_NUMBER: builtins.int
    REPOSITORY_CLASS_FIELD_NUMBER: builtins.int
    PACKAGE_TYPE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    NOTES_FIELD_NUMBER: builtins.int
    repository_key: builtins.str
    project_key: builtins.str
    @property
    def repository_class(self) -> global___RepositoryClass: ...
    @property
    def package_type(self) -> global___PackageType: ...
    description: builtins.str
    notes: builtins.str
    def __init__(
        self,
        *,
        repository_key: builtins.str = ...,
        project_key: builtins.str = ...,
        repository_class: global___RepositoryClass | None = ...,
        package_type: global___PackageType | None = ...,
        description: builtins.str = ...,
        notes: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["package_type", b"package_type", "repository_class", b"repository_class"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "notes", b"notes", "package_type", b"package_type", "project_key", b"project_key", "repository_class", b"repository_class", "repository_key", b"repository_key"]) -> None: ...

global___RepositorySpec = RepositorySpec

class RepositoryClass(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOCAL_FIELD_NUMBER: builtins.int
    @property
    def local(self) -> global___RepositoryClassLocal: ...
    def __init__(
        self,
        *,
        local: global___RepositoryClassLocal | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["class", b"class", "local", b"local"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["class", b"class", "local", b"local"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["class", b"class"]) -> typing_extensions.Literal["local"] | None: ...

global___RepositoryClass = RepositoryClass

class RepositoryClassLocal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RepositoryClassLocal = RepositoryClassLocal

class PackageType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GENERIC_FIELD_NUMBER: builtins.int
    DOCKER_FIELD_NUMBER: builtins.int
    MACHINE_LEARNING_FIELD_NUMBER: builtins.int
    @property
    def generic(self) -> global___PackageTypeGeneric: ...
    @property
    def docker(self) -> global___PackageTypeDocker: ...
    @property
    def machine_learning(self) -> global___PackageTypeMachineLearning: ...
    def __init__(
        self,
        *,
        generic: global___PackageTypeGeneric | None = ...,
        docker: global___PackageTypeDocker | None = ...,
        machine_learning: global___PackageTypeMachineLearning | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["docker", b"docker", "generic", b"generic", "machine_learning", b"machine_learning", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["docker", b"docker", "generic", b"generic", "machine_learning", b"machine_learning", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["type", b"type"]) -> typing_extensions.Literal["generic", "docker", "machine_learning"] | None: ...

global___PackageType = PackageType

class PackageTypeGeneric(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PackageTypeGeneric = PackageTypeGeneric

class PackageTypeDocker(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PackageTypeDocker = PackageTypeDocker

class PackageTypeMachineLearning(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PackageTypeMachineLearning = PackageTypeMachineLearning
