import typing
from _typeshed import Incomplete
from dataclasses import dataclass, field
from enum import Enum
from python_multipart.multipart import MultipartCallbacks as MultipartCallbacks, QuerystringCallbacks as QuerystringCallbacks
from zephyr.app.datastructures import FormData as FormData, Headers as Headers, UploadFile as UploadFile

class FormMessage(Enum):
    FIELD_START = 1
    FIELD_NAME = 2
    FIELD_DATA = 3
    FIELD_END = 4
    END = 5

@dataclass
class MultipartPart:
    content_disposition: bytes | None = ...
    field_name: str = ...
    data: bytearray = field(default_factory=bytearray)
    file: UploadFile | None = ...
    item_headers: list[tuple[bytes, bytes]] = field(default_factory=list)

class MultiPartException(Exception):
    message: Incomplete
    def __init__(self, message: str) -> None: ...

class FormParser:
    headers: Incomplete
    stream: Incomplete
    messages: list[tuple[FormMessage, bytes]]
    def __init__(self, headers: Headers, stream: typing.AsyncGenerator[bytes, None]) -> None: ...
    def on_field_start(self) -> None: ...
    def on_field_name(self, data: bytes, start: int, end: int) -> None: ...
    def on_field_data(self, data: bytes, start: int, end: int) -> None: ...
    def on_field_end(self) -> None: ...
    def on_end(self) -> None: ...
    async def parse(self) -> FormData: ...

class MultiPartParser:
    spool_max_size: Incomplete
    max_part_size: Incomplete
    headers: Incomplete
    stream: Incomplete
    max_files: Incomplete
    max_fields: Incomplete
    items: list[tuple[str, str | UploadFile]]
    def __init__(self, headers: Headers, stream: typing.AsyncGenerator[bytes, None], *, max_files: int | float = 1000, max_fields: int | float = 1000, max_part_size: int = ...) -> None: ...
    def on_part_begin(self) -> None: ...
    def on_part_data(self, data: bytes, start: int, end: int) -> None: ...
    def on_part_end(self) -> None: ...
    def on_header_field(self, data: bytes, start: int, end: int) -> None: ...
    def on_header_value(self, data: bytes, start: int, end: int) -> None: ...
    def on_header_end(self) -> None: ...
    def on_headers_finished(self) -> None: ...
    def on_end(self) -> None: ...
    async def parse(self) -> FormData: ...
