import typing
from _typeshed import Incomplete
from zephyr._types import Message as Message, Receive as Receive, Scope as Scope, Send as Send
from zephyr.app._utils import AwaitableOrContextManager as AwaitableOrContextManager, AwaitableOrContextManagerWrapper as AwaitableOrContextManagerWrapper
from zephyr.app.application import Zephyr as Zephyr
from zephyr.app.datastructures import Address as Address, FormData as FormData, Headers as Headers, QueryParams as QueryParams, State as State, URL as URL
from zephyr.app.exceptions import HTTPException as HTTPException
from zephyr.app.formparsers import FormParser as FormParser, MultiPartException as MultiPartException, MultiPartParser as MultiPartParser
from zephyr.app.routing import Router as Router

SERVER_PUSH_HEADERS_TO_COPY: Incomplete

def cookie_parser(cookie_string: str) -> dict[str, str]: ...

class ClientDisconnect(Exception): ...

class HTTPConnection(typing.Mapping[str, typing.Any]):
    scope: Incomplete
    def __init__(self, scope: Scope, receive: Receive | None = None) -> None: ...
    def __getitem__(self, key: str) -> typing.Any: ...
    def __iter__(self) -> typing.Iterator[str]: ...
    def __len__(self) -> int: ...
    __eq__: Incomplete
    __hash__: Incomplete
    @property
    def app(self) -> typing.Any: ...
    @property
    def url(self) -> URL: ...
    @property
    def base_url(self) -> URL: ...
    @property
    def headers(self) -> Headers: ...
    @property
    def query_params(self) -> QueryParams: ...
    @property
    def path_params(self) -> dict[str, typing.Any]: ...
    @property
    def cookies(self) -> dict[str, str]: ...
    @property
    def client(self) -> Address | None: ...
    @property
    def session(self) -> dict[str, typing.Any]: ...
    @property
    def auth(self) -> typing.Any: ...
    @property
    def user(self) -> typing.Any: ...
    @property
    def state(self) -> State: ...
    def url_for(self, name: str, /, **path_params: typing.Any) -> URL: ...

async def empty_receive() -> typing.NoReturn: ...
async def empty_send(message: Message) -> typing.NoReturn: ...

class Request(HTTPConnection):
    def __init__(self, scope: Scope, receive: Receive = ..., send: Send = ...) -> None: ...
    @property
    def method(self) -> str: ...
    @property
    def receive(self) -> Receive: ...
    async def stream(self) -> typing.AsyncGenerator[bytes, None]: ...
    async def body(self) -> bytes: ...
    async def json(self) -> typing.Any: ...
    def form(self, *, max_files: int | float = 1000, max_fields: int | float = 1000, max_part_size: int = ...) -> AwaitableOrContextManager[FormData]: ...
    async def close(self) -> None: ...
    async def is_disconnected(self) -> bool: ...
    async def send_push_promise(self, path: str) -> None: ...
