ray_tool = {
    "RayWriterJsonline": {
        "class_name": "RayWriterJsonline",
        "description": "保存数据集为JSON/JSONL格式",
        "name": "ray_writer_jsonline",
        "label": "存储JSONL文件",
        "params": [
            {
                "name": "path",
                "label": "输出路径",
                "description": "JSON/JSONL 文件保存的目标根目录路径,默认存储result目录",
                "default": "",
                "type": "str",
                "require": 0,
                "choice": None,
            },
            {
                "name": "try_create_dir",
                "label": "创建目录",
                "description": "是否尝试自动创建目标路径中的目录",
                "default": True,
                "type": "bool",
                "require": 1,
                "choice": None,
            },
            {
                "name": "arrow_open_stream_args",
                "label": "打开流参数",
                "description": "传递给 pyarrow.fs.FileSystem.open_output_stream 的参数",
                "default": {},
                "type": "dict",
                "require": 1,
                "choice": None,
            },
            {
                "name": "force_ascii",
                "label": "强制编码字符串为ASCII",
                "description": "强制编码字符串为ASCII",
                "default": False,
                "type": "bool",
                "require": 1,
                "choice": None,
            },
            {
                "name": "min_rows_per_file",
                "label": "每文件最小行数",
                "description": "每个文件写入的最小行数提示（系统可能写入更多或更少）",
                "default": 100,
                "type": "int",
                "require": 1,
                "choice": None,
            },
            {
                "name": "concurrency",
                "label": "并发任务数",
                "description": "可同时运行的最大 Ray 写入任务数，不影响任务总数，默认根据可用资源动态决定",
                "default": None,
                "type": "int",
                "require": 1,
                "choice": None,
            },
            {
                "name": "mode",
                "label": "写入模式",
                "description": "控制处理已存在文件的方式，可选 overwrite（覆盖）、error（报错）、ignore（忽略）、append（追加）",
                "default": "append",
                "type": "enum",
                "choice": ["overwrite", "error", "ignore", "append"],
                "require": 1,
            },
        ],
        "category": "consumer",
    },
    "RayWriterCsv": {
        "class_name": "RayWriterCsv",
        "description": "保存数据集为CSV格式",
        "name": "ray_writer_csv",
        "label": "存储CSV文件",
        "params": [
            {
                "name": "path",
                "label": "输出路径",
                "description": "csv 文件保存的目标根目录路径,默认存储result目录",
                "default": "",
                "type": "str",
                "require": 0,
                "choice": None,
            },
            {
                "name": "try_create_dir",
                "label": "创建目录",
                "description": "是否尝试自动创建目标路径中的目录",
                "default": True,
                "type": "bool",
                "require": 1,
                "choice": None,
            },
            {
                "name": "arrow_open_stream_args",
                "label": "打开流参数",
                "description": "传递给 pyarrow.fs.FileSystem.open_output_stream 的参数",
                "default": {},
                "type": "dict",
                "require": 1,
                "choice": None,
            },
            {
                "name": "min_rows_per_file",
                "label": "每文件最小行数",
                "description": "每个文件写入的最小行数提示（系统可能写入更多或更少）",
                "default": 100,
                "type": "int",
                "require": 1,
                "choice": None,
            },
            {
                "name": "concurrency",
                "label": "并发任务数",
                "description": "可同时运行的最大 Ray 写入任务数，不影响任务总数，默认根据可用资源动态决定",
                "default": None,
                "type": "int",
                "require": 1,
                "choice": None,
            },
            {
                "name": "mode",
                "label": "写入模式",
                "description": "控制处理已存在文件的方式，可选 overwrite（覆盖）、error（报错）、ignore（忽略）、append（追加）",
                "default": "append",
                "type": "enum",
                "choice": ["overwrite", "error", "ignore", "append"],
                "require": 1,
            },
        ],
        "category": "consumer",
    },
    "RayWriterParquet": {
        "class_name": "RayWriterParquet",
        "description": "保存数据集为Parque格式",
        "name": "ray_writer_parquet",
        "label": "存储Parquet",
        "params": [
            {
                "name": "path",
                "label": "输出路径",
                "description": "Parquet 文件的保存路径（目录）,默认存储result目录",
                "default": "",
                "type": "str",
                "require": 0,
                "choice": None,
            },
            {
                "name": "partition_cols",
                "label": "分区列",
                "description": "用于分区的列名，文件以 Hive 格式保存",
                "default": None,
                "type": "list",
                "require": 1,
                "choice": None,
                "item_type": "str",
            },
            {
                "name": "try_create_dir",
                "label": "创建目录",
                "description": "是否尝试自动创建目录",
                "default": True,
                "type": "bool",
                "require": 1,
                "choice": None,
            },
            {
                "name": "arrow_open_stream_args",
                "label": "打开流参数",
                "description": "传递给 open_output_stream 的参数",
                "default": {},
                "type": "dict",
                "require": 1,
                "choice": None,
            },
            {
                "name": "min_rows_per_file",
                "label": "每文件最小行数",
                "description": "每个文件写入的最小行数（系统可能略多或略少）",
                "default": 100,
                "type": "int",
                "require": 1,
                "choice": None,
            },
            {
                "name": "concurrency",
                "label": "并发任务数",
                "description": "同时运行的最大 Ray 任务数",
                "default": None,
                "type": "int",
                "require": 1,
                "choice": None,
            },
            {
                "name": "row_group_sizeint",
                "label": "行组大小",
                "description": "每个组中的最大行数。如果没有，则行组的大小将是表大小的最小值和1024 * 1024。如果设置大于64mi，则将使用64mi。",
                "default": None,
                "type": "int",
                "require": 1,
                "choice": None,
            },
            {
                "name": "mode",
                "label": "写入模式",
                "description": "处理已有文件的方式，可选项包括 overwrite、error、ignore、append",
                "default": "append",
                "type": "enum",
                "choice": ["overwrite", "error", "ignore", "append"],
                "require": 1,
            },
        ],
        "category": "consumer",
    },
    "ToolLimit": {
        "class_name": "ToolLimit",
        "description": "按数据集原有顺序，从起始位置依次截取前n条记录",
        "name": "tool_limit",
        "label": "截取数据(Limit)",
        "params": [
            {
                "name": "limit",
                "label": "截断大小",
                "description": "将数据集截断到指定的大小，限制返回的记录数",
                "type": "int",
                "require": 1,
                "choice": None,
                "default": 20,
            }
        ],
        "category": "tool",
    },
    "ToolCount": {
        "class_name": "ToolCount",
        "description": "计算数据集的行数",
        "name": "tool_count",
        "label": "数据集行数",
        "sub_type": "state",
        "params": [
            {
                "name": "path",
                "label": "统计结果保存文件【json格式】",
                "type": "str",
                "default": "",
                "description": "统计结果保存文件【json格式】,默认存储result目录",
                "require": 0,
                "choice": None,
            }
        ],
        "category": "tool",
        "sub_type": "state",
    },
    "ToolColumns": {
        "class_name": "ToolColumns",
        "description": "返回此数据集的列名称",
        "name": "tool_columns",
        "label": "返回此数据集的列名称",
        "sub_type": "state",
        "params": [
            {
                "name": "path",
                "label": "统计结果保存文件【json格式】",
                "type": "str",
                "default": "无",
                "description": "统计结果保存文件【json格式】,默认存储result目录",
                "require": 0,
                "choice": None,
            }
        ],
        "category": "tool",
    },
    "ToolRepartition": {
        "class_name": "ToolRepartition",
        "description": "将数据集重新分区为指定数量的块",
        "name": "tool_repartition",
        "label": "重新分区数据集",
        "params": [
            {
                "name": "num_blocks",
                "label": "分区后块数量",
                "type": "int",
                "description": "分区后块的数量",
                "require": 1,
                "choice": None,
                "default": "无",
            },
            {
                "name": "shuffle",
                "label": "是否随机打散",
                "type": "bool",
                "default": False,
                "description": "是否执行分布式 shuffle",
                "require": 1,
                "choice": None,
            },
            # {
            #     "name": "keys",
            #     "label": "哈希分区键",
            #     "type": "list",
            #     "default": None,
            #     "description": "用于哈希分区的列名列表",
            #     "require": 1,
            #     "choice": None,
            #     "item_type": "str",
            # },
            {
                "name": "sort",
                "label": "是否排序",
                "type": "bool",
                "default": False,
                "description": "是否在重新分区后对各块进行排序",
                "require": 1,
                "choice": None,
            },
        ],
        "category": "tool",
    },
    "ToolTake": {
        "class_name": "ToolTake",
        "description": "从数据集中返回最多指定行数",
        "name": "tool_take",
        "label": "显示前若干行",
        "params": [
            {
                "name": "limit",
                "label": "最多返回行数",
                "type": "int",
                "description": "要返回的最大行数",
                "require": 0,
                "choice": None,
                "default": 20,
            },
            {
                "name": "path",
                "label": "统计结果保存文件【json格式】",
                "type": "str",
                "default": "",
                "description": "统计结果保存文件【json格式】,默认存储result目录",
                "require": 0,
                "choice": None,
            },
        ],
        "category": "tool",
        "sub_type": "state",
    },
    "ToolRenameColumns": {
        "class_name": "ToolRenameColumns",
        "description": "重命名数据集中的列",
        "name": "tool_rename_columns",
        "label": "重命名数据集中的列",
        "params": [
            {
                "name": "names",
                "label": "新列名称映射",
                "type": "text",
                "description": "旧列名到新列名的映射",
                "require": 1,
                "choice": None,
                "default": "无",
            },
            {
                "name": "concurrency",
                "label": "并发数",
                "type": "int",
                "default": None,
                "description": "并行使用的 Ray worker 数量",
                "require": 1,
                "choice": None,
            },
        ],
        "category": "tool",
    },
    "ToolSelectColumns": {
        "class_name": "ToolSelectColumns",
        "description": "从数据集中选择一个或多个列",
        "name": "tool_select_columns",
        "label": "选择列",
        "params": [
            {
                "name": "cols",
                "label": "列名列表",
                "type": "list",
                "description": "要选择的列名，必须在 schema 中且唯一",
                "require": 1,
                "choice": None,
                "default": "无",
                "item_type": "str",
            },
            {
                "name": "concurrency",
                "label": "并发数",
                "type": "int",
                "default": None,
                "description": "并行使用的 Ray worker 数量",
                "require": 1,
                "choice": None,
            },
        ],
        "category": "tool",
    },
    "ToolDropColumns": {
        "class_name": "ToolDropColumns",
        "description": "从数据集中删除一个或多个列",
        "name": "tool_drop_columns",
        "label": "删除列",
        "params": [
            {
                "name": "cols",
                "label": "列名列表",
                "type": "list",
                "default": "无",
                "description": "要删除的列名，必须在 schema 中且唯一",
                "require": 1,
                "choice": None,
                "item_type": "str",
            },
            {
                "name": "concurrency",
                "label": "并发数",
                "type": "int",
                "default": None,
                "description": "并行使用的 Ray worker 数量",
                "require": 1,
                "choice": None,
            },
        ],
        "category": "tool",
    },
    "ToolMax": {
        "class_name": "ToolMax",
        "description": "返回指定一列或多个数值列的最大值，返回字典（列名→最大值）",
        "name": "tool_max",
        "label": "最大值",
        "params": [
            {
                "name": "on",
                "label": "聚合列",
                "type": "list",
                "description": "最大值的列名或列名列表",
                "require": 1,
                "choice": None,
                "default": "无",
                "item_type": "str",
            },
            {
                "name": "ignore_nulls",
                "label": "忽略空值",
                "type": "bool",
                "default": True,
                "description": "是否忽略空值（np.nan, None, pd.NaT）",
                "require": 1,
                "choice": None,
            },
            {
                "name": "path",
                "label": "统计结果保存文件【json格式】",
                "type": "str",
                "default": "无",
                "description": "统计结果保存文件【json格式】,默认存储result目录",
                "require": 0,
                "choice": None,
            },
        ],
        "category": "consumer",
        "sub_type": "state",
    },
    "ToolMin": {
        "class_name": "ToolMin",
        "description": "返回指定一个数值列或多个数值列的最小值，返回字典（列名→最小值）",
        "name": "tool_min",
        "label": "最小值",
        "params": [
            {
                "name": "on",
                "label": "聚合列",
                "type": "list",
                "description": "最小值的列名或列名列表",
                "require": 1,
                "choice": None,
                "default": "无",
                "item_type": "str",
            },
            {
                "name": "ignore_nulls",
                "label": "忽略空值",
                "type": "bool",
                "default": True,
                "description": "是否忽略空值（np.nan, None, pd.NaT）",
                "require": 1,
                "choice": None,
            },
            {
                "name": "path",
                "label": "统计结果保存文件【json格式】",
                "type": "str",
                "default": "无",
                "description": "统计结果保存文件【json格式】,默认存储result目录",
                "require": 0,
                "choice": None,
            },
        ],
        "category": "consumer",
        "sub_type": "state",
    },
    "ToolMean": {
        "class_name": "ToolMean",
        "description": "计算一列或多列的平均值",
        "name": "tool_mean",
        "label": "平均值",
        "params": [
            {
                "name": "on",
                "label": "聚合列",
                "type": "str",
                "description": "平均值的列名或列名列表",
                "require": 1,
                "choice": None,
                "default": "无",
            },
            {
                "name": "ignore_nulls",
                "label": "忽略空值",
                "type": "bool",
                "default": True,
                "description": "是否忽略空值（np.nan, None, pd.NaT）",
                "require": 1,
                "choice": None,
            },
            {
                "name": "path",
                "label": "统计结果保存文件【json格式】",
                "type": "str",
                "default": "无",
                "description": "统计结果保存文件【json格式】,默认存储result目录",
                "require": 0,
                "choice": None,
            },
        ],
        "category": "consumer",
        "sub_type": "state",
    },
    "ToolStd": {
        "class_name": "ToolStd",
        "description": "计算一列或多列的标准差",
        "name": "tool_std",
        "label": "标准差",
        "params": [
            {
                "name": "on",
                "label": "聚合列",
                "type": "str",
                "description": "标准差的列名或列名列表",
                "require": 1,
                "choice": None,
                "default": "无",
            },
            {
                "name": "ignore_nulls",
                "label": "忽略空值",
                "type": "bool",
                "default": True,
                "description": "是否忽略空值（np.nan, None, pd.NaT）",
                "require": 1,
                "choice": None,
            },
            {
                "name": "path",
                "label": "统计结果保存文件【json格式】",
                "type": "str",
                "default": "无",
                "description": "统计结果保存文件【json格式】,默认存储result目录",
                "require": 0,
                "choice": None,
            },
        ],
        "category": "consumer",
        "sub_type": "state",
    },
    "ToolSum": {
        "class_name": "ToolSum",
        "description": "计算一列或多个数值列的总和",
        "name": "tool_sum",
        "label": "总和",
        "params": [
            {
                "name": "on",
                "label": "聚合列",
                "type": "str",
                "description": "求总和的列名或列名列表",
                "require": 1,
                "choice": None,
                "default": "无",
            },
            {
                "name": "ignore_nulls",
                "label": "忽略空值",
                "type": "bool",
                "default": True,
                "description": "是否忽略空值（np.nan, None, pd.NaT）",
                "require": 1,
                "choice": None,
            },
            {
                "name": "path",
                "label": "统计结果保存文件【json格式】",
                "type": "str",
                "default": "无",
                "description": "统计结果保存文件【json格式】,默认存储result目录",
                "require": 0,
                "choice": None,
            },
        ],
        "category": "consumer",
        "sub_type": "state",
    },
    "ToolUnique": {
        "class_name": "ToolUnique",
        "description": "获得列的去重结果",
        "name": "tool_unique",
        "label": "去重",
        "params": [
            {
                "name": "column",
                "label": "列名",
                "type": "str",
                "description": "要收集唯一元素的列",
                "require": 1,
                "choice": None,
                "default": "无",
            },
            {
                "name": "path",
                "label": "统计结果保存文件【json格式】",
                "type": "str",
                "default": "无",
                "description": "统计结果保存文件【json格式】,默认存储result目录",
                "require": 0,
                "choice": None,
            },
        ],
        "category": "consumer",
    },
    "ToolSort": {
        "class_name": "ToolSort",
        "description": "按指定列排序数据集",
        "name": "tool_sort",
        "label": "排序",
        "params": [
            {
                "name": "key",
                "label": "排序列",
                "type": "list",
                "description": "用于排序的列名或列名列表",
                "require": 1,
                "choice": None,
                "default": "无",
                "item_type": "str",
            },
            {
                "name": "descending",
                "label": "降序",
                "type": ["list", "bool"],
                "default": False,
                "description": "是否降序排序",
                "require": 0,
                "choice": None,
                "item_type": "bool",
            },
            {
                "name": "boundaries",
                "label": "分区边界",
                "type": "list",
                "description": "用于分区的边界列表，仅支持数值列",
                "require": 0,
                "choice": None,
                "default": None,
            },
        ],
        "category": "tool",
    },
    "ToolRandomShuffle": {
        "class_name": "ToolRandomShuffle",
        "description": "随机洗牌此数据集",
        "name": "tool_random_shuffle",
        "label": "随机洗牌此数据集",
        "params": [
            {
                "name": "num_blocks",
                "label": "块数量",
                "type": "int",
                "description": "块数量",
                "require": 0,
                "choice": None,
                "default": "无",
            },
            {
                "name": "seed",
                "label": "随机种子",
                "type": "int",
                "default": None,
                "description": "用于初始化 Python 随机数生成器的种子",
                "require": 0,
                "choice": None,
            },
        ],
        "category": "tool",
    },
    "ToolAddColumn": {
        "class_name": "ToolAddColumn",
        "description": "将给定列添加到数据集必须指定以pyarrow或pandas格式生成新列值的函数。此功能必须在批处理_format上操作。",
        "name": "tool_add_column",
        "label": "将给定列添加到数据集",
        "params": [
            {
                "name": "col",
                "label": "要添加的列的名称",
                "type": "str",
                "description": "要添加的列的名称。如果该名称已存在，则将覆盖该列",
                "require": 1,
                "choice": None,
                "default": "无",
            },
            {
                "name": "fn",
                "label": "映射函数",
                "type": "str",
                "default": "无",
                "description": "映射函数生成列值给定的一批记录，以熊猫格式的格式。示例: \ndef main(df):\n    return 'value1'",
                "require": 1,
                "choice": None,
            },
            {
                "name": "concurrency",
                "label": "并行度",
                "type": "int",
                "default": "无",
                "description": "要并发使用的最大Ray工作线程数",
                "require": 1,
                "choice": None,
            },
        ],
        "category": "tool",
    },
    "ToolAddId": {
        "class_name": "ToolAddId",
        "description": "添加唯一自增id列，默认增加的列名为id",
        "name": "tool_add_id",
        "label": "添加唯一自增id列",
        "params": [
            {
                "name": "col",
                "label": "唯一自增id列的名称",
                "type": "str",
                "description": "唯一自增id列名称",
                "require": 1,
                "choice": None,
                "default": "id",
            }
        ],
        "category": "tool",
    },
    "PythonCode": {
        "label": "执行python代码",
        "category": "tool",
        "description": "输入python 代码执行\n例如：\nimport pandas as pd\ndef aa(data):\nreturn data",
        "params": [
            {
                "name": "code",
                "label": "python代码",
                "description": "需要执行的python代码",
                "default": "无",
                "type": "str",
                "rows": 3,
                "choice": None,
                "require": 1,
            },
            {
                "name": "data_type",
                "label": "算子输入的数据类型",
                "description": "data表示单行数据，dataset表示整个数据集",
                "choice": ["data", "dataset"],
                "default": "data",
                "type": "enum",
                "require": 0,
            },
        ],
        "name": "python_code",
        "class_name": "PythonCode",
        "exec_params": [
            {
                "name": "num_cpus",
                "label": "CPU 资源数量",
                "description": "为任务保留的 CPU 资源数量，默认值为 1。",
                "default": 1,
                "type": "float",
                "choice": None,
                "require": 0,
            },
            {
                "name": "resources",
                "label": "自定义资源",
                "description": "保留的自定义资源数量，字典形式 {'资源名': 数量}，默认值为空。",
                "default": {},
                "type": "dict",
                "choice": None,
                "require": 0,
                "item_type": ["str", "float"],
            },
            {
                "name": "memory",
                "label": "内存请求",
                "description": "请求的堆内存字节数，会向下取整。",
                "default": None,
                "type": "int",
                "choice": None,
                "require": 0,
            },
            {
                "name": "max_calls",
                "label": "最大调用次数",
                "description": "单个 Worker 执行远程函数的最大次数，默认 CPU 任务无限次，GPU 任务默认为 1（完成后释放资源）。",
                "default": None,
                "type": "int",
                "choice": None,
                "require": 0,
            },
            {
                "name": "max_retries",
                "label": "最大重试次数",
                "description": "Worker 崩溃时重试远程函数的最大次数，默认值为 3，0表示不重试",
                "default": 3,
                "type": "int",
                "choice": None,
                "require": 0,
            },
            {
                "name": "retry_exceptions",
                "label": "是否重试异常",
                "description": "是否对应用级异常进行最多max_retries 次重试。",
                "default": False,
                "type": "bool",
                "choice": None,
                "require": 0,
            },
            {
                "name": "runtime_env",
                "label": "运行环境",
                "description": "任务及子任务所使用的运行环境配置。",
                "default": {},
                "type": "dict",
                "choice": None,
                "require": 0,
                "item_type": ["str", "any"],
            },
            {
                "name": "scheduling_strategy",
                "label": "调度策略",
                "description": "任务的调度策略，可选值包括 'DEFAULT'（默认）、'SPREAD'（尽量分布）等。",
                "default": "DEFAULT",
                "choice": ["DEFAULT", "SPREAD"],
                "type": "enum",
                "require": 0,
            },
            {
                "name": "_labels",
                "label": "标签",
                "description": "任务的键值标签。",
                "default": {},
                "type": "dict",
                "choice": None,
                "require": 0,
                "item_type": ["str", "str"],
            },
        ],
    },
    "ToolRandomSample": {
        "class_name": "ToolRandomSample",
        "description": "随机采样抽数",
        "name": "tool_random_sample",
        "label": "随机采样抽数",
        "params": [
            {
                "name": "fraction",
                "label": "抽样比例",
                "type": "float",
                "range": {"min": 0.0, "max": 1.0},
                "description": "抽取的行比例，取值范围 [0, 1]",
                "require": 1,
                "choice": None,
                "default": "无",
            },
            {
                "name": "seed",
                "label": "随机种子",
                "type": "int",
                "default": None,
                "description": "用于初始化 Python 随机数生成器的种子",
                "require": 1,
                "choice": None,
            },
        ],
        "category": "tool",
    },
    "RayReaderText": {
        "class_name": "RayReaderText",
        "description": "从文本文件中创建数据集。返回的列名为text，值为文本内容",
        "name": "ray_reader_text",
        "label": "读取文本文件",
        "params": [
            {
                "name": "paths",
                "label": "文件路径",
                "description": "支持单个文件、目录，或包含文件与目录的路径列表",
                "type": "dataSource",
                "expand": 1,
                "item_type": "str",
                "default": "",
                "require": 1,
                "choice": None,
            },
            {
                "name": "sub_path",
                "label": "相对路径",
                "description": "数据集或者运行实例的相对路径",
                "type": "str",
                "default": "",
                "require": 0,
            },
            {
                "name": "encoding",
                "label": "文件编码",
                "description": "文本文件编码格式，例如 'utf-8' 或 'ascii'",
                "type": "enum",
                "default": "utf-8",
                "require": 0,
                "choice": ["utf-8", "ascii"],
            },
            {
                "name": "arrow_open_stream_args",
                "label": "Arrow流参数",
                "description": "传递给 pyarrow.fs.FileSystem.open_input_file 的参数",
                "type": "dict",
                "default": {},
                "require": 0,
                "choice": None,
            },
            {
                "name": "include_paths",
                "label": "包含路径",
                "description": "是否在结果中包含文件路径，路径会存储在 'path' 列中",
                "type": "bool",
                "default": False,
                "require": 0,
                "choice": None,
            },
            {
                "name": "ignore_missing_paths",
                "label": "忽略缺失路径",
                "description": "若为 True，则忽略未找到的文件或目录路径",
                "type": "bool",
                "default": False,
                "require": 0,
                "choice": None,
            },
            {
                "name": "shuffle",
                "label": "文件打乱",
                "description": "是否对输入文件顺序进行打乱，可传入 'files' 或 FileShuffleConfig",
                "type": "enum",
                "choice": [None, "files"],
                "default": None,
                "require": 0,
            },
            {
                "name": "file_extensions",
                "label": "文件扩展名过滤",
                "description": "过滤指定扩展名的文件列表",
                "type": "list",
                "item_type": "str",
                "default": None,
                "require": 0,
                "choice": None,
            },
            {
                "name": "concurrency",
                "label": "并发数",
                "description": "最大并发任务数，不影响任务总数，仅控制同时运行的任务数量",
                "type": "int",
                "default": None,
                "require": 0,
                "choice": None,
            },
            {
                "name": "override_num_blocks",
                "label": "输出块数量",
                "description": "覆盖所有读取任务的输出块数量，通常不建议手动设置",
                "type": "int",
                "default": None,
                "require": 0,
                "choice": None,
            },
        ],
        "category": "reader",
    },
    "RayReaderJsonline": {
        "class_name": "RayReaderJsonline",
        "description": "从 标准JSON 或 JSONL 文件中读取数据集",
        "name": "ray_reader_jsonline",
        "label": "读取JSONL文件",
        "params": [
            {
                "name": "paths",
                "label": "文件路径",
                "description": "支持文件路径或目录路径，支持混合类型的路径列表",
                "type": "dataSource",
                "expand": 1,
                "item_type": "str",
                "default": "",
                "require": 1,
                "choice": None,
            },
            {
                "name": "sub_path",
                "label": "相对路径",
                "description": "数据集或者运行实例的相对路径",
                "type": "str",
                "default": "",
                "require": 0,
            },
            {
                "name": "include_paths",
                "label": "包含路径",
                "description": "是否在结果中包含文件路径",
                "type": "bool",
                "default": False,
                "require": 1,
                "choice": None,
            },
            {
                "name": "ignore_missing_paths",
                "label": "paths 参数中的文件或者文件夹不存在时，是否忽略",
                "description": "若为 True,，则忽略未找到的路径",
                "type": "bool",
                "default": False,
                "require": 1,
                "choice": None,
            },
            {
                "name": "shuffle",
                "label": "文件打乱",
                "description": "是否对输入文件顺序进行打乱，可传入 FileShuffleConfig",
                "type": "enum",
                "choice": [None, "files"],
                "default": None,
                "require": 1,
            },
            {
                "name": "concurrency",
                "label": "并发数",
                "description": "最大并发任务数",
                "type": "int",
                "default": None,
                "require": 1,
                "choice": None,
            },
            {
                "name": "override_num_blocks",
                "label": "输出块数量",
                "description": "覆盖所有读取任务的输出块数量",
                "type": "int",
                "default": None,
                "require": 1,
                "choice": None,
            },
        ],
        "category": "reader",
    },
    "RayReaderParquet": {
        "class_name": "RayReaderParquet",
        "description": "从 Parquet 文件中创建数据集",
        "name": "ray_reader_parquet",
        "label": "读取Parquet文件",
        "params": [
            {
                "name": "paths",
                "label": "文件路径",
                "description": "支持单个路径或目录，多个目录暂不支持",
                "type": "dataSource",
                "expand": 1,
                "default": "",
                "require": 1,
                "choice": None,
            },
            {
                "name": "sub_path",
                "label": "相对路径",
                "description": "数据集或者运行实例的相对路径",
                "type": "str",
                "default": "",
                "require": 0,
            },
            {
                "name": "columns",
                "label": "读取列",
                "description": "指定要读取的列名",
                "type": "List[str]",
                "default": None,
                "require": 1,
                "choice": None,
            },
            {
                "name": "shuffle",
                "label": "文件打乱",
                "description": "是否对输入文件顺序进行打乱，可传入 FileShuffleConfig",
                "type": "enum",
                "choice": [None, "files"],
                "default": None,
                "require": 1,
            },
            {
                "name": "concurrency",
                "label": "并发数",
                "description": "最大并发任务数",
                "type": "int",
                "default": None,
                "require": 1,
                "choice": None,
            },
            {
                "name": "override_num_blocks",
                "label": "输出块数量",
                "description": "覆盖所有读取任务的输出块数量",
                "type": "int",
                "default": None,
                "require": 1,
                "choice": None,
            },
        ],
        "category": "reader",
    },
    "RayReaderFromItems": {
        "class_name": "RayReaderFromItems",
        "description": '读取构造的数据，多用于测试。例如：[{"text": "测试数据"}]',
        "name": "ray_reader_from_items",
        "label": "从列表创建数据集",
        "sub_type": "user_input",
        "params": [
            {
                "name": "items",
                "label": "对象列表",
                "description": "内存中的 Python 对象组成的列表",
                "type": "list",
                "default": "无",
                "require": 1,
                "choice": None,
            },
            {
                "name": "override_num_blocks",
                "label": "输出块数量",
                "description": "覆盖所有读取任务的输出块数量",
                "type": "int",
                "default": None,
                "require": 1,
                "choice": None,
            },
        ],
        "category": "reader",
    },
}

task_exec_params = [
    {
        "name": "num_cpus",
        "label": "CPU 资源数量",
        "description": "为任务保留的 CPU 资源数量，默认值为 1。",
        "default": 1,
        "type": "float",
    },
    # {
    #     "name": "num_gpus",
    #     "label": "GPU 资源数量",
    #     "description": "为任务保留的 GPU 资源数量，默认值为 0。",
    #     "default": 0,
    #     "type": "float",
    # },
    {
        "name": "concurrency",
        "label": "并发任务数",
        "description": "可同时运行的最大 Ray 写入任务数，不影响任务总数，默认根据可用资源动态决定",
        "default": None,
        "type": "int",
        "require": 1,
        "choice": None,
    },
    {
        "name": "resources",
        "label": "自定义资源",
        "description": "保留的自定义资源数量，字典形式 {'资源名': 数量}，默认值为空。",
        "default": {},
        "type": "dict[str, float]",
    },
    {
        "name": "memory",
        "label": "内存请求",
        "description": "请求的堆内存字节数，会向下取整。",
        "default": None,
        "type": "int",
    },
    {
        "name": "max_calls",
        "label": "最大调用次数",
        "description": "单个 Worker 执行远程函数的最大次数，默认 CPU 任务无限次，GPU 任务默认为 1（完成后释放资源）。",
        "default": None,
        "type": "int",
    },
    {
        "name": "max_retries",
        "label": "最大重试次数",
        "description": "Worker 崩溃时重试远程函数的最大次数，默认值为 3，0 表示不重试",
        "default": 3,
        "type": "int",
    },
    {
        "name": "retry_exceptions",
        "label": "是否重试异常",
        "description": "是否对应用级异常进行最多 max_retries 次重试。",
        "default": False,
        "type": "bool",
    },
    {
        "name": "runtime_env",
        "label": "运行环境",
        "description": "任务及子任务所使用的运行环境配置。",
        "default": {},
        "type": "dict[str, any]",
    },
    {
        "name": "scheduling_strategy",
        "label": "调度策略",
        "description": "任务的调度策略，可选值包括 'DEFAULT'（默认）、'SPREAD'（尽量分布）等。",
        "default": "DEFAULT",
        "choice": ["DEFAULT", "SPREAD"],
        "type": "str",
    },
    {
        "name": "_labels",
        "label": "标签",
        "description": "任务的键值标签。",
        "default": {},
        "type": "dict[str, str]",
    },
]


actor_exec_params = [
    {
        "name": "num_cpus",
        "label": "CPU 资源数量",
        "description": "为 Actor 生命周期保留的 CPU 资源数量。默认调度需要 1 CPU，运行时需要 0 CPU，推荐显式设置避免调度问题。",
        "default": 1,
        "type": "float",
    },
    {
        "name": "concurrency",
        "label": "并发任务数",
        "description": "可同时运行的最大 Ray 写入任务数，不影响任务总数，默认根据可用资源动态决定",
        "default": None,
        "type": "int",
        "require": 1,
        "choice": None,
    },
    {
        "name": "num_gpus",
        "label": "GPU 资源数量",
        "description": "为 Actor 生命周期保留的 GPU 资源数量，默认值为 0。",
        "default": 0,
        "type": "float",
    },
    {
        "name": "resources",
        "label": "自定义资源",
        "description": "保留的自定义资源数量，字典形式 {'资源名': 数量}，默认值为空。",
        "default": {},
        "type": "dict[str, float]",
    },
    {
        "name": "accelerator_type",
        "label": "加速器类型",
        "description": "指定 Actor 必须在哪种加速器类型节点上运行。",
        "default": None,
        "type": "str",
    },
    {
        "name": "memory",
        "label": "内存请求",
        "description": "请求的堆内存字节数，会向下取整。",
        "default": None,
        "type": "int",
    },
    {
        "name": "max_restarts",
        "label": "最大重启次数",
        "description": "Actor 异常退出后最多可重启的次数，默认为 0 表示不重启。",
        "default": 0,
        "type": "int",
    },
    {
        "name": "max_task_retries",
        "label": "任务最大重试次数",
        "description": "当 Actor 上的任务因系统错误失败时，最大重试次数，默认为 0，达到上限后触发RayActorError异常。",
        "default": 0,
        "type": "int",
    },
    {
        "name": "runtime_env",
        "label": "运行环境",
        "description": "Actor 及子任务的运行环境配置。",
        "default": {},
        "type": "dict[str, any]",
    },
    {
        "name": "scheduling_strategy",
        "label": "调度策略",
        "description": "任务的调度策略，可选值包括 'DEFAULT'（默认）、'SPREAD'（尽量分布）等。",
        "default": "DEFAULT",
        "choice": ["DEFAULT", "SPREAD"],
        "type": "str",
    },
    {
        "name": "_labels",
        "label": "标签",
        "description": "Actor 的键值标签。",
        "default": {},
        "type": "dict[str, str]",
    },
]


spark_tool = {
    # "SparkWriterJsonline": {
    #     "class_name": "SparkWriterJsonline",
    #     "description": "从JSON文件创建数据集",
    #     "name": "spark_writer_jsonline",
    #     "label": "存储JSONL文件",
    #     "params": [
    #         {
    #             "name": "path",
    #             "label": "输出路径",
    #             "description": "JSON文件保存的目标根目录路径",
    #             "default": "无",
    #             "type": "str",
    #             "require": 1,
    #             "choice": None,
    #         },
    #         {
    #             "name": "mode",
    #             "label": "写入模式:overwrite(覆盖) / append(追加) / ignore(忽略)",
    #             "description": "写入模式:overwrite(覆盖)/ append(追加) / ignore(忽略)",
    #             "default": "overwrite",
    #             "type": "str",
    #             "require": 0,
    #             "choice": None,
    #         },
    #         {
    #             "name": "encoding",
    #             "label": "文件编码格式",
    #             "description": "文件编码格式,默认utf-8",
    #             "default": "utf-8",
    #             "type": "str",
    #             "require": 0,
    #             "choice": None,
    #         },
    #     ],
    #     "category": "consumer",
    # },
    "SparkWriter": {
        "class_name": "SparkWriter",
        "description": "将数据集写入文件(JSON、JSONL、csv、parquet)中",
        "name": "spark_writer",
        "label": "写入数据集到文件中",
        "params": [
            {
                "name": "path",
                "label": "写入的文件路径",
                "description": "写入的文件路径",
                "type": "str",
                "default": "",
                "require": 1,
                "choice": None,
            },
            {
                "name": "format",
                "label": "文件格式",
                "description": "文件格式,如csv,json,parquet",
                "default": "parquet",
                "type": "str",
                "require": 0,
                "choice": ["csv", "json", "parquet"],
            },
            {
                "name": "mode",
                "label": "文件写入模式",
                "description": "写入模式:overwrite(覆盖)/ append(追加) / ignore(忽略)/errorifexists(存在则报错)",
                "default": "overwrite",
                "type": "str",
                "require": 0,
                "choice": ["overwrite", "append", "ignore", "errorifexists"],
            },
        ],
        "category": "consumer",
    },
    # "SparkReaderJsonline": {
    #     "class_name": "SparkReaderJsonline",
    #     "description": "从JSON或JSONL文件中读取数据集",
    #     "name": "spark_reader_jsonline",
    #     "label": "读取JSON文件",
    #     "params": [
    #         {
    #             "name": "path",
    #             "label": "文件路径",
    #             "description": "支持文件路径或目录路径。多个文件用,分开",
    #             "type": "list",
    #             "item_type": "str",
    #             "default": "无",
    #             "require": 1,
    #             "choice": None,
    #         },
    #     ],
    #     "category": "reader",
    # },
    "SparkReader": {
        "class_name": "SparkReader",
        "description": "从数据源文件(json、csv、parquet)中读取数据集",
        "name": "spark_reader",
        "label": "读取文件数据集",
        "params": [
            {
                "name": "paths",
                "label": "文件路径",
                "description": "支持文件路径或目录路径。多个文件用,分开",
                "type": "dataSource",
                "expand": 1,
                "item_type": "str",
                "default": "无",
                "require": 0,
                "choice": None,
            },
            {
                "name": "sub_path",
                "label": "相对路径",
                "description": "数据集或者运行实例的相对路径",
                "type": "str",
                "default": "",
                "require": 0,
            },
            {
                "name": "format",
                "label": "文件格式",
                "description": "文件格式,如csv,json,parquet",
                "default": "parquet",
                "type": "str",
                "require": 0,
                "choice": ["csv", "json", "parquet"],
            },
            {
                "name": "multiline",
                "label": "一条json数据是否跨多行,默认False,针对json格式有效",
                "description": "",
                "default": "False",
                "type": "bool",
                "require": 0,
                "choice": None,
            },
        ],
        "category": "reader",
    },
    # "SparkTake": {
    #     "class_name": "SparkTake",
    #     "description": "从数据集中返回最多指定行数",
    #     "name": "spark_take",
    #     "label": "显示前若干行",
    #     "params": [
    #         {
    #             "name": "limit",
    #             "label": "最多返回行数",
    #             "type": "int",
    #             "description": "要返回的最大行数",
    #             "require": 0,
    #             "choice": None,
    #             "default": 20,
    #         },
    #         {
    #             "name": "path",
    #             "label": "统计结果保存文件路径【json格式】",
    #             "type": "str",
    #             "default": None,
    #             "description": "统计结果保存文件路径【json格式】",
    #             "require": 1,
    #             "choice": None,
    #         },
    #     ],
    #     "category": "tool",
    # },
    # "SparkCount": {
    #     "class_name": "SparkCount",
    #     "description": "计算数据集行数",
    #     "name": "spark_count",
    #     "label": "数据集行数",
    #     "sub_type": "state",
    #     "params": [
    #         {
    #             "name": "path",
    #             "label": "保存数据集结果路径",
    #             "type": "str",
    #             "default": None,
    #             "description": "保存数据集结果路径",
    #             "require": 1,
    #             "choice": None,
    #         }
    #     ],
    #     "category": "tool",
    # },
    # "SparkAddId": {
    #     "class_name": "SparkAddId",
    #     "description": "数据集添加唯一自增id列",
    #     "name": "spark_add_id",
    #     "label": "数据集添加自增ID列",
    #     "params": [
    #         {
    #             "name": "col",
    #             "label": "唯一自增id列的名称",
    #             "type": "str",
    #             "description": "唯一自增id列名称",
    #             "require": 1,
    #             "choice": None,
    #             "default": "id",
    #         }
    #     ],
    #     "category": "tool",
    # },
    "SparkToolTake": {
        "class_name": "SparkToolTake",
        "description": "从数据集中查询前若干行数据",
        "name": "spark_tool_take",
        "label": "显示前若干行",
        "params": [
            {
                "name": "num",
                "label": "最大返回行数",
                "type": "int",
                "description": "要返回的最大行数",
                "require": 0,
                "choice": None,
                "default": 20,
            },
            {
                "name": "path",
                "label": "统计结果保存文件路径【json格式】",
                "type": "str",
                "default": "",
                "description": "统计结果保存文件路径【json格式】,默认存储result目录",
                "require": 0,
                "choice": None,
            },
        ],
        "category": "tool",
    },
    "SparkToolCount": {
        "class_name": "SparkToolCount",
        "description": "计算数据集行数",
        "name": "spark_tool_count",
        "label": "数据集行数",
        "sub_type": "state",
        "params": [
            {
                "name": "path",
                "label": "保存统计数据集行数结果路径，默认result目录",
                "type": "str",
                "default": "",
                "description": "保存统计数据集行数",
                "require": 0,
                "choice": None,
            }
        ],
        "category": "tool",
    },
    "SparkToolAddId": {
        "class_name": "SparkToolAddId",
        "description": "数据集添加单调递增但不连续ID列",
        "name": "spark_tool_add_id",
        "label": "数据集添加递增ID列",
        "params": [
            {
                "name": "col",
                "label": "递增列的名称,如ID",
                "type": "str",
                "description": "递增ID列名称",
                "require": 1,
                "choice": None,
                "default": "id",
            }
        ],
        "category": "tool",
    },
    "SparkToolRenameColumns": {
        "class_name": "SparkToolRenameColumns",
        "description": "重命名数据集中的列名称",
        "name": "spark_tool_rename_columns",
        "label": "重命名数据集中的列名称",
        "params": [
            {
                "name": "names",
                "label": "新列名称映射",
                "type": "dict",
                "description": "旧列名到新列名的映射",
                "require": 1,
                "choice": None,
                "default": "无",
            },
        ],
        "category": "tool",
    },
}
ray_tool.update(spark_tool)
