# coding: utf-8

"""
    ANTENNEX Reverberation Chamber API

    HTTP API for ANTENNEX The Wireless Connector(tm)

    The version of the OpenAPI document: 3.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SettingsTypes(str, Enum):
    """
    The type of the settings structure. Supply a \"calibration\" settings structure for calibrations, and  a \"measurement\" structure for measurements.
    """

    """
    allowed enum values
    """
    MEASUREMENT = 'measurement'
    CALIBRATION = 'calibration'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SettingsTypes from a JSON string"""
        return cls(json.loads(json_str))


