from .config import KeycloakConfig as KeycloakConfig
from .exceptions import KeycloakAuthenticationError as KeycloakAuthenticationError, KeycloakConnectionError as KeycloakConnectionError, KeycloakExpiredTokenError as KeycloakExpiredTokenError, KeycloakInvalidTokenError as KeycloakInvalidTokenError, KeycloakTokenError as KeycloakTokenError
from .models import KeycloakToken as KeycloakToken, KeycloakUserInfo as KeycloakUserInfo
from _typeshed import Incomplete
from datetime import timedelta as timedelta
from jose import jwk as jwk
from typing import Any

class KeycloakClient:
    config: Incomplete
    http_client: Incomplete
    def __init__(self, config: KeycloakConfig) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> KeycloakClient: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def get_authorization_url(self, redirect_uri: str, state: str | None = None, scopes: list[str] | None = None, **kwargs: Any) -> str: ...
    async def exchange_code_for_token(self, code: str, redirect_uri: str, code_verifier: str | None = None) -> KeycloakToken: ...
    async def refresh_token(self, refresh_token: str) -> KeycloakToken: ...
    async def get_user_info(self, access_token: str) -> KeycloakUserInfo: ...
    async def logout(self, refresh_token: str, redirect_uri: str | None = None) -> None: ...
    async def introspect_token(self, token: str) -> dict[str, Any]: ...
    async def get_jwks(self, force_refresh: bool = False) -> dict[str, Any]: ...
    async def validate_token(self, token: str, verify_signature: bool | None = None, verify_audience: bool | None = None, verify_expiry: bool | None = None) -> dict[str, Any]: ...
    def generate_pkce_challenge(self, code_verifier: str | None = None) -> tuple[str, str]: ...
    async def get_well_known_config(self) -> dict[str, Any]: ...
