"""Type stubs for eo_processor"""

from typing import Literal
import numpy as np
from numpy.typing import NDArray

# Inputs accept any numeric dtype; implementation coerces to float64 internally.
NumericArray = NDArray[np.generic]

__version__: Literal["0.3.0"]

def normalized_difference(a: NumericArray, b: NumericArray) -> NDArray[np.float64]: ...
def ndvi(nir: NumericArray, red: NumericArray) -> NDArray[np.float64]: ...
def ndwi(green: NumericArray, nir: NumericArray) -> NDArray[np.float64]: ...
def savi(
    nir: NumericArray, red: NumericArray, L: float = ...
) -> NDArray[np.float64]: ...
def nbr(nir: NumericArray, swir2: NumericArray) -> NDArray[np.float64]: ...
def ndmi(nir: NumericArray, swir1: NumericArray) -> NDArray[np.float64]: ...
def nbr2(swir1: NumericArray, swir2: NumericArray) -> NDArray[np.float64]: ...
def gci(nir: NumericArray, green: NumericArray) -> NDArray[np.float64]: ...
def delta_ndvi(
    pre_nir: NumericArray,
    pre_red: NumericArray,
    post_nir: NumericArray,
    post_red: NumericArray,
) -> NDArray[np.float64]: ...
def delta_nbr(
    pre_nir: NumericArray,
    pre_swir2: NumericArray,
    post_nir: NumericArray,
    post_swir2: NumericArray,
) -> NDArray[np.float64]: ...
def enhanced_vegetation_index(
    nir: NumericArray, red: NumericArray, blue: NumericArray
) -> NDArray[np.float64]: ...

evi = enhanced_vegetation_index

def median(arr: NumericArray, skip_na: bool = ...) -> NDArray[np.float64]: ...
def composite(
    arr: NumericArray, method: str = ..., **kwargs
) -> NDArray[np.float64]: ...
def temporal_mean(arr: NumericArray, skip_na: bool = ...) -> NDArray[np.float64]: ...
def temporal_std(arr: NumericArray, skip_na: bool = ...) -> NDArray[np.float64]: ...
def euclidean_distance(
    points_a: NumericArray, points_b: NumericArray
) -> NDArray[np.float64]: ...
def manhattan_distance(
    points_a: NumericArray, points_b: NumericArray
) -> NDArray[np.float64]: ...
def chebyshev_distance(
    points_a: NumericArray, points_b: NumericArray
) -> NDArray[np.float64]: ...
def minkowski_distance(
    points_a: NumericArray, points_b: NumericArray, p: float
) -> NDArray[np.float64]: ...

# Raises ValueError if p < 1.0
