"""
------------------------------------------------------------------------------
<auto-generated>
    This code was auto-generated by main/tools/jsonparser.
    Do not change this file.
</auto-generated>
------------------------------------------------------------------------------
"""
import json
import sys
import re
from six import string_types

# Unused import over optimization prevention


if sys.version_info > (3,):
    long = int
    unicode = str

class Artifact(object):
    """NGC Artifact"""
    def __init__(self, propDict=None):
        fromDict = propDict is not None and isinstance(propDict, dict)
        self.environmentUri = (
            None if not fromDict or propDict.get(
                "environmentUri"
            ) is None
            else propDict["environmentUri"])
        self.name = (
            None if not fromDict or propDict.get(
                "name"
            ) is None
            else propDict["name"])
        self.org = (
            None if not fromDict or propDict.get(
                "org"
            ) is None
            else propDict["org"])
        self.team = (
            None if not fromDict or propDict.get(
                "team"
            ) is None
            else propDict["team"])
        self.version = (
            None if not fromDict or propDict.get(
                "version"
            ) is None
            else propDict["version"])

    @property
    def environmentUri(self):
        """str: Environment and microservice URI artifact is from. Examples: h
        ttps://models.ngc.nvidia.com, https://nvcr.io, etc."""
        return self._environmentUri

    @environmentUri.setter
    def environmentUri(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._environmentUri = value
        else:
            raise TypeError(
                'Property "environmentUri" of type "list<str>" set to wrong t'
                'ype'
            )

    @property
    def name(self):
        """str: Name of the NGC artifact unique to the org or team"""
        return self._name

    @name.setter
    def name(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._name = value
        else:
            raise TypeError(
                'Property "name" of type "list<str>" set to wrong type'
            )

    @property
    def org(self):
        """str: Name of the NGC org that owns the artifact"""
        return self._org

    @org.setter
    def org(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._org = value
        else:
            raise TypeError(
                'Property "org" of type "list<str>" set to wrong type'
            )

    @property
    def team(self):
        """str: (Optional) Name of the NGC team under the specified org that o
        wns the artifact"""
        return self._team

    @team.setter
    def team(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._team = value
        else:
            raise TypeError(
                'Property "team" of type "list<str>" set to wrong type'
            )

    @property
    def version(self):
        """str: Version/Tag of the NGC artifact"""
        return self._version

    @version.setter
    def version(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._version = value
        else:
            raise TypeError(
                'Property "version" of type "list<str>" set to wrong type'
            )

    def toDict(self):
        result = {}
        if self._environmentUri is not None:
            result["environmentUri"] = \
                self._environmentUri
        if self._name is not None:
            result["name"] = \
                self._name
        if self._org is not None:
            result["org"] = \
                self._org
        if self._team is not None:
            result["team"] = \
                self._team
        if self._version is not None:
            result["version"] = \
                self._version
        return result

    def toJSON(self, pretty=False):
        if pretty:
            return json.dumps(self.toDict(), sort_keys=True, indent=4)
        else:
            return json.dumps(self.toDict(), sort_keys=True)

    def isValid(self):
        if self._org is None:
            raise ValueError(
                "Artifact.org doesnt match requirement:" 
                "required: True"
            )
        if self._name is None:
            raise ValueError(
                "Artifact.name doesnt match requirement:" 
                "required: True"
            )
        return True
    

