"""Constants for transcription and TTS services."""

# Audio processing constants
DEFAULT_SAMPLE_RATE = 16000
MAX_SINGLE_FILE_SIZE_MB = 20.0
OPENAI_MAX_FILE_SIZE_MB = 24.5
DEFAULT_CHUNK_DURATION_SEC = 300
MAX_TRANSCRIPTION_RETRIES = 3

# TTS constants
MIN_TTS_SPEED = 0.25
MAX_TTS_SPEED = 4.0
MAX_TTS_TEXT_LENGTH = 4096

# Parallel processing constants
DEFAULT_MAX_CONCURRENT = 4
MIN_CONCURRENT_WORKERS = 1
MAX_CONCURRENT_WORKERS = 10

# Temperature ranges
MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 1.0