from typing import List, Any

class SnowballStemmer:
    def __init__(self, lang: str, cache: bool = True) -> None: ...
    def stem_word(self, input: str) -> str: ...
    def stem_words_parallel(self, py: Any, inputs: List[str]) -> List[str]: ...
    def stem_words(self, inputs: List[str]) -> List[str]: ...

def py_rust_stemmers_tuned(*args, **kwargs) -> Any: ...
