from ..sso.models import SSOAuthResult as SSOAuthResult, SSOUser as SSOUser
from ..sso.providers import SSOProvider as SSOProvider
from .client import KeycloakClient as KeycloakClient
from .config import KeycloakConfig as KeycloakConfig
from .exceptions import KeycloakError as KeycloakError
from _typeshed import Incomplete
from typing import Any

class KeycloakSSOProvider(SSOProvider):
    keycloak_config: Incomplete
    keycloak_client: Incomplete
    def __init__(self, config: KeycloakConfig) -> None: ...
    def get_provider_name(self) -> str: ...
    def get_authorization_url(self, state: str, **kwargs: Any) -> str: ...
    async def exchange_code_for_token(self, code: str, state: str) -> dict[str, Any]: ...
    async def get_user_info(self, access_token: str) -> dict[str, Any]: ...
    def map_user_data(self, user_data: dict[str, Any]) -> SSOUser: ...
    async def authenticate(self, code: str, state: str) -> SSOAuthResult: ...
    async def logout(self, refresh_token: str, redirect_uri: str | None = None) -> None: ...
    async def refresh_token(self, refresh_token: str) -> dict[str, Any]: ...
    async def validate_token(self, access_token: str) -> dict[str, Any]: ...
    async def close(self) -> None: ...
