# coding: utf-8

"""
    Oliver API

    Oliver API service  # noqa: E501

    OpenAPI spec version: 4.5.9
    Contact: api@behavioralsignals.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import behavioral_signals_swagger_client
from behavioral_signals_swagger_client.models.id_patch import IdPatch  # noqa: E501
from behavioral_signals_swagger_client.rest import ApiException


class TestIdPatch(unittest.TestCase):
    """IdPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdPatch(self):
        """Test IdPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = behavioral_signals_swagger_client.models.id_patch.IdPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
