from ._base_enum import BaseEnum


class LIDGroupCode(BaseEnum):
    CONTROL_FACILITY = "CONTROL FACILITY"
    FLIGHT_SERVICE_STATION = "FLIGHT SERVICE STATION"
    INSTRUMENT_LANDING_FACILITY = "INSTRUMENT LANDING FACILITY"
    LANDING_FACILITY = "LANDING FACILITY"
    NAVIGATION_AID = "NAVIGATION AID"
    REMOTE_COMMUNICATION_OUTLET = "REMOTE COMMUNICATION OUTLET"
    SPECIAL_USE_RESOURCE = "SPECIAL USE RESOURCE"
    WEATHER_REPORTING_STATION = "WEATHER REPORTING STATION"
    WEATHER_SENSOR = "WEATHER SENSOR"
    NULL = None
