from ._base_enum import BaseEnum


class MAATypeCode(BaseEnum):
    AEROBATIC_PRACTICE = "AEROBATIC PRACTICE"
    GLIDER = "GLIDER"
    HANG_GLIDER = "HANG GLIDER"
    SPACE_LAUNCH = "SPACE LAUNCH"
    ULTRALIGHT = "ULTRALIGHT"
    UNMANNED_AIRCRAFT = "UNMANNED AIRCRAFT"
    OTHER = "OTHER"
    NULL = None
