from ._base_enum import BaseEnum


class Part77Code(BaseEnum):
    UTILITY_RUNWAY_VISUAL = "A(V)"
    NON_UTILITY_RUNWAY_VISUAL = "B(V)"
    UTILITY_RUNWAY_NON_PRECISION = "A(NP)"
    NON_UTILITY_RUNWAY_NON_PRECISION_MINIMUMS_ABOVE_3QTR_MI = "C"
    NON_UTILITY_RUNWAY_NON_PRECISION_MINIMUMS_AT_3QTR_MI = "D"
    RUNWAY_PRECISION = "PIR"
    NULL = None
