from ._base_enum import BaseEnum


class PrefRouteTypeCode(BaseEnum):
    LOW_ALTITUDE = "L"
    HIGH_ALTITUDE = "H"
    LOW_ALTITUDE_PREFERRED_DIRECTION = "LPD"
    HIGH_ALTITUDE_PREFERRED_DIRECTION = "HPD"
    SPECIAL_LOW_ALTITUDE_DIRECTIONAL = "SLD"
    SPECIAL_HIGH_ALTITUDE_DIRECTIONAL = "SHD"
    TOWER_ENROUTE_CONTROL = "TEC"
    NORTH_AMERICAN_ROUTE = "NAR"
    NULL = None
