from nasrparse.records.types._base_enum import BaseEnum


class ServiceCode(BaseEnum):
    AIR_FREIGHT_SERVICES = "AFRT"
    CROP_DUSTING_SERVICES = "AGRI"
    AIR_AMBULANCE_SERVICES = "AMB"
    AVIONICS = "AVNCS"
    BEACHING_GEAR = "BCHGR"
    CARGO_HANDLING_SERVICES = "CARGO"
    CHARTER_SERVICE = "CHTR"
    GLIDER_SERVICE = "GLD"
    PILOT_INSTRUCTION = "INSTR"
    PARACHUTE_JUMP_ACTIVITY = "PAJA"
    AIRCRAFT_RENTAL = "RNTL"
    AIRCRAFT_SALES = "SALES"
    ANNUAL_SURVEYING = "SURV"
    GLIDER_TOWING_SERVICES = "TOW"
    NULL = None
