# coding: utf-8

"""
    Oliver API

    Oliver API service  # noqa: E501

    OpenAPI spec version: 4.5.9
    Contact: api@behavioralsignals.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import behavioral_signals_swagger_client
from behavioral_signals_swagger_client.models.request_task_options_data import RequestTaskOptionsData  # noqa: E501
from behavioral_signals_swagger_client.rest import ApiException


class TestRequestTaskOptionsData(unittest.TestCase):
    """RequestTaskOptionsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestTaskOptionsData(self):
        """Test RequestTaskOptionsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = behavioral_signals_swagger_client.models.request_task_options_data.RequestTaskOptionsData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
