from typing import Any, BinaryIO

__version__: str

def load(fp: BinaryIO, /, *, parse_datetime: bool = True) -> dict[str, Any]: ...
def loads(s: str, /, *, parse_datetime: bool = True) -> dict[str, Any]: ...

class YAMLDecodeError(ValueError): ...
