# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Blackcat Informatics® Inc.
"""Aggregate configuration models and helpers for pyqa."""

from __future__ import annotations

from ..model_defs import (
    DEFAULT_IMPLICATIONS,
    NO_BASELINE,
    UNSET,
    BanditConfidence,
    BanditLevel,
    ConfigError,
    ConfigSentinel,
    GenericValueTypesConfig,
    GenericValueTypesImplication,
    GenericValueTypesRule,
    SensitivityLevel,
    StrictnessLevel,
    ValueTypeFindingSeverity,
    ValueTypeTriggerKind,
)
from ..model_defs.config_container import (
    _STRICT_DEDUPE_SENSITIVITY_LEVELS,
    _TOOL_KNOB_MAPPING,
    MYPY_TOOL_KEY,
    SENSITIVITY_PRESETS,
    Config,
    ConfigOverrideKey,
    SensitivityOverrideValue,
    SensitivityPreset,
    SharedKnobSnapshot,
    ToolOverrideValue,
    ToolSpecificOverride,
)
from .sections import (
    CleanConfig,
    ComplexityConfig,
    DedupeConfig,
    ExecutionConfig,
    FileDiscoveryConfig,
    LicenseConfig,
    OutputConfig,
    QualityConfigSection,
    SeverityConfig,
    StrictnessConfig,
    UpdateConfig,
    default_parallel_jobs,
)

__all__ = [
    "BanditConfidence",
    "BanditLevel",
    "CleanConfig",
    "ComplexityConfig",
    "Config",
    "ConfigError",
    "ConfigOverrideKey",
    "ConfigSentinel",
    "DEFAULT_IMPLICATIONS",
    "DedupeConfig",
    "ExecutionConfig",
    "FileDiscoveryConfig",
    "GenericValueTypesConfig",
    "GenericValueTypesImplication",
    "GenericValueTypesRule",
    "LicenseConfig",
    "MYPY_TOOL_KEY",
    "NO_BASELINE",
    "OutputConfig",
    "QualityConfigSection",
    "SENSITIVITY_PRESETS",
    "SensitivityLevel",
    "SensitivityOverrideValue",
    "SensitivityPreset",
    "SeverityConfig",
    "SharedKnobSnapshot",
    "StrictnessConfig",
    "StrictnessLevel",
    "ToolOverrideValue",
    "ToolSpecificOverride",
    "UNSET",
    "UpdateConfig",
    "ValueTypeFindingSeverity",
    "ValueTypeTriggerKind",
    "_STRICT_DEDUPE_SENSITIVITY_LEVELS",
    "_TOOL_KNOB_MAPPING",
    "default_parallel_jobs",
]
