from typing import Any
from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class PushNotificationActionSchema(BaseModel):
    url: str | None = None
    data: dict[Any, Any] | None = None
    silent: bool | None = None
    openInBrowser: bool | None = None
    httpMethod: str | None = None