from _typeshed import Incomplete
from typing import Any

class OAuth2Error(Exception):
    error: Incomplete
    description: Incomplete
    uri: Incomplete
    state: Incomplete
    extra: Incomplete
    def __init__(self, error: str, description: str | None = None, uri: str | None = None, state: str | None = None, **kwargs: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class InvalidRequestError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidClientError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidGrantError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class UnauthorizedClientError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class UnsupportedGrantTypeError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class UnsupportedResponseTypeError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidScopeError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class AccessDeniedError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class UnsupportedTokenTypeError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class ServerError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class TemporarilyUnavailableError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InsufficientScopeError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidTokenError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class ExpiredTokenError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class RevokedTokenError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class MalformedTokenError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class MissingTokenError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidRedirectUriError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidCodeChallengeError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidCodeVerifierError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidClientCredentialsError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class ClientNotFoundError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class DuplicateClientError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidClientTypeError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidGrantTypeError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidResponseTypeError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class InvalidScopeRequestError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class AuthorizationExpiredError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class AuthorizationUsedError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class AuthorizationRevokedError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class DeviceCodeExpiredError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class DeviceCodePendingError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class DeviceCodeSlowDownError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...

class DeviceCodeAccessDeniedError(OAuth2Error):
    def __init__(self, description: str | None = None, **kwargs: Any) -> None: ...
