from .config import OAuth2Config as OAuth2Config
from .exceptions import AccessDeniedError as AccessDeniedError, DeviceCodeAccessDeniedError as DeviceCodeAccessDeniedError, DeviceCodeExpiredError as DeviceCodeExpiredError, DeviceCodePendingError as DeviceCodePendingError, DeviceCodeSlowDownError as DeviceCodeSlowDownError, InvalidClientError as InvalidClientError, InvalidCodeChallengeError as InvalidCodeChallengeError, InvalidCodeVerifierError as InvalidCodeVerifierError, InvalidGrantError as InvalidGrantError, InvalidRedirectUriError as InvalidRedirectUriError, InvalidRequestError as InvalidRequestError, InvalidScopeError as InvalidScopeError, UnsupportedGrantTypeError as UnsupportedGrantTypeError
from .models import OAuth2AccessToken as OAuth2AccessToken, OAuth2AuthorizationCode as OAuth2AuthorizationCode, OAuth2Client as OAuth2Client, OAuth2DeviceCode as OAuth2DeviceCode, OAuth2RefreshToken as OAuth2RefreshToken, generate_access_token as generate_access_token, generate_authorization_code as generate_authorization_code, generate_device_code as generate_device_code, generate_refresh_token as generate_refresh_token, generate_user_code as generate_user_code
from _typeshed import Incomplete
from typing import Any
from urllib.parse import urlencode as urlencode, urlparse as urlparse

class BaseFlow:
    config: Incomplete
    def __init__(self, config: OAuth2Config) -> None: ...
    def validate_client(self, client: OAuth2Client, grant_type: str) -> None: ...
    def validate_scope(self, requested_scope: str, client: OAuth2Client) -> list[str]: ...
    def validate_redirect_uri(self, redirect_uri: str, client: OAuth2Client) -> None: ...

class AuthorizationCodeFlow(BaseFlow):
    def create_authorization_code(self, client: OAuth2Client, user_id: str, redirect_uri: str, scopes: list[str], code_challenge: str | None = None, code_challenge_method: str | None = None, nonce: str | None = None, **kwargs: Any) -> OAuth2AuthorizationCode: ...
    def exchange_code_for_tokens(self, code: str, client: OAuth2Client, redirect_uri: str, code_verifier: str | None = None, **kwargs: Any) -> tuple[OAuth2AccessToken, OAuth2RefreshToken | None]: ...
    def validate_code_verifier(self, code_challenge: str, code_verifier: str, method: str) -> bool: ...

class ClientCredentialsFlow(BaseFlow):
    def create_access_token(self, client: OAuth2Client, scopes: list[str], **kwargs: Any) -> OAuth2AccessToken: ...

class PKCEFlow(BaseFlow):
    def generate_code_challenge(self, code_verifier: str, method: str = 'S256') -> str: ...
    def generate_code_verifier(self, length: int = 128) -> str: ...
    def validate_code_challenge(self, code_challenge: str, code_verifier: str, method: str) -> bool: ...

class DeviceFlow(BaseFlow):
    def create_device_code(self, client: OAuth2Client, scopes: list[str], **kwargs: Any) -> OAuth2DeviceCode: ...
    def poll_device_code(self, device_code: str) -> dict[str, Any]: ...
    def authorize_device_code(self, device_code: str, user_id: str) -> None: ...

class RefreshTokenFlow(BaseFlow):
    def create_refresh_token(self, client: OAuth2Client, user_id: str, scopes: list[str], **kwargs: Any) -> OAuth2RefreshToken: ...
    def refresh_access_token(self, refresh_token: str, client: OAuth2Client, requested_scopes: list[str] | None = None, **kwargs: Any) -> tuple[OAuth2AccessToken, OAuth2RefreshToken]: ...
    def revoke_refresh_token(self, refresh_token: str) -> None: ...

class ImplicitFlow(BaseFlow):
    def create_access_token(self, client: OAuth2Client, user_id: str, scopes: list[str], **kwargs: Any) -> OAuth2AccessToken: ...

class PasswordFlow(BaseFlow):
    def create_access_token(self, client: OAuth2Client, user_id: str, scopes: list[str], **kwargs: Any) -> tuple[OAuth2AccessToken, OAuth2RefreshToken]: ...

class FlowManager:
    config: Incomplete
    flows: Incomplete
    pkce_flow: Incomplete
    def __init__(self, config: OAuth2Config) -> None: ...
    def get_flow(self, grant_type: str) -> BaseFlow: ...
    def is_grant_type_supported(self, grant_type: str) -> bool: ...
    def is_response_type_supported(self, response_type: str) -> bool: ...
    def validate_authorization_request(self, client: OAuth2Client, response_type: str, redirect_uri: str, scope: str, state: str | None = None, **kwargs: Any) -> dict[str, Any]: ...
    def validate_token_request(self, client: OAuth2Client, grant_type: str, **kwargs: Any) -> dict[str, Any]: ...
