from .config import OAuth2Config as OAuth2Config
from .exceptions import AccessDeniedError as AccessDeniedError, InvalidClientError as InvalidClientError, InvalidGrantError as InvalidGrantError, InvalidRequestError as InvalidRequestError, InvalidScopeError as InvalidScopeError, OAuth2Error as OAuth2Error, ServerError as ServerError, UnsupportedGrantTypeError as UnsupportedGrantTypeError, UnsupportedResponseTypeError as UnsupportedResponseTypeError
from .flows import FlowManager as FlowManager
from .models import OAuth2AccessToken as OAuth2AccessToken, OAuth2AuthorizationCode as OAuth2AuthorizationCode, OAuth2Client as OAuth2Client, OAuth2DeviceCode as OAuth2DeviceCode, OAuth2RefreshToken as OAuth2RefreshToken, generate_client_id as generate_client_id, generate_client_secret as generate_client_secret
from _typeshed import Incomplete
from datetime import datetime as datetime, timedelta as timedelta
from typing import Any
from urllib.parse import parse_qs as parse_qs, urlparse as urlparse

class OAuth2Server:
    config: Incomplete
    flow_manager: Incomplete
    logger: Incomplete
    def __init__(self, config: OAuth2Config) -> None: ...
    def create_client(self, client_name: str, client_type: str = 'confidential', redirect_uris: list[str] | None = None, grant_types: list[str] | None = None, response_types: list[str] | None = None, scopes: list[str] | None = None, **kwargs: Any) -> OAuth2Client: ...
    def get_client(self, client_id: str) -> OAuth2Client | None: ...
    def authenticate_client(self, client_id: str, client_secret: str | None = None) -> OAuth2Client: ...
    def handle_authorization_request(self, client_id: str, response_type: str, redirect_uri: str, scope: str | None = None, state: str | None = None, code_challenge: str | None = None, code_challenge_method: str | None = None, nonce: str | None = None, **kwargs: Any) -> dict[str, Any]: ...
    def handle_token_request(self, grant_type: str, client_id: str, client_secret: str | None = None, code: str | None = None, redirect_uri: str | None = None, code_verifier: str | None = None, refresh_token: str | None = None, scope: str | None = None, username: str | None = None, password: str | None = None, device_code: str | None = None, **kwargs: Any) -> dict[str, Any]: ...
    def get_access_token(self, token: str) -> OAuth2AccessToken | None: ...
    def revoke_access_token(self, token: str) -> bool: ...
    def revoke_refresh_token(self, token: str) -> bool: ...
    def introspect_token(self, token: str) -> dict[str, Any]: ...
