__title__ = "xenoslib"
__description__ = "Xenos' common lib"
__url__ = "https://github.com/XenosLu/xenoslib.git"
__author__ = "Xenocider"
__author_email__ = "xenos.lu@gmail.com"
__license__ = "MIT License"
__version__ = "0.4.2"
