"""Type stubs for file-based state store (hot workspace)"""

from pathlib import Path
from typing import Any

from ..models.artifact import Artifact
from .store import StateStore
from .types import ProjectInfo, SnapshotInfo, TUState

class FileStore(StateStore):
    """File-based storage for hot workspace (work-in-progress artifacts)."""

    root_dir: Path
    hot_dir: Path
    metadata_file: Path

    def __init__(self, root_dir: str | Path) -> None: ...
    def get_project_info(self) -> ProjectInfo: ...
    def save_project_info(self, info: ProjectInfo) -> None: ...
    def save_artifact(self, artifact: Artifact) -> None: ...
    def get_artifact(self, artifact_id: str) -> Artifact | None: ...
    def list_artifacts(
        self,
        artifact_type: str | None = None,
        filters: dict[str, Any] | None = None,
    ) -> list[Artifact]: ...
    def delete_artifact(self, artifact_id: str) -> bool: ...
    def save_tu(self, tu: TUState) -> None: ...
    def get_tu(self, tu_id: str) -> TUState | None: ...
    def list_tus(self, filters: dict[str, Any] | None = None) -> list[TUState]: ...
    def save_snapshot(self, snapshot: SnapshotInfo) -> None: ...
    def get_snapshot(self, snapshot_id: str) -> SnapshotInfo | None: ...
    def list_snapshots(
        self, filters: dict[str, Any] | None = None
    ) -> list[SnapshotInfo]: ...
