"""Type stubs for SQLite state store (cold storage)"""

import sqlite3
from pathlib import Path
from typing import Any

from ..models.artifact import Artifact
from .store import StateStore
from .types import ProjectInfo, SnapshotInfo, TUState

class SQLiteStore(StateStore):
    """SQLite-based storage for cold storage (ship-ready artifacts)."""

    db_path: Path
    conn: sqlite3.Connection | None

    def __init__(self, db_path: str | Path) -> None: ...
    def init_database(self) -> None: ...
    def close(self) -> None: ...
    def get_project_info(self) -> ProjectInfo: ...
    def save_project_info(self, info: ProjectInfo) -> None: ...
    def save_artifact(self, artifact: Artifact) -> None: ...
    def get_artifact(self, artifact_id: str) -> Artifact | None: ...
    def list_artifacts(
        self,
        artifact_type: str | None = None,
        filters: dict[str, Any] | None = None,
    ) -> list[Artifact]: ...
    def delete_artifact(self, artifact_id: str) -> bool: ...
    def save_tu(self, tu: TUState) -> None: ...
    def get_tu(self, tu_id: str) -> TUState | None: ...
    def list_tus(self, filters: dict[str, Any] | None = None) -> list[TUState]: ...
    def save_snapshot(self, snapshot: SnapshotInfo) -> None: ...
    def save_or_replace_snapshot(self, snapshot: SnapshotInfo) -> None: ...
    def get_snapshot(self, snapshot_id: str) -> SnapshotInfo | None: ...
    def list_snapshots(
        self, filters: dict[str, Any] | None = None
    ) -> list[SnapshotInfo]: ...
    def get_artifacts_by_ids(self, artifact_ids: list[str]) -> list[Artifact]: ...
    def get_artifacts_by_snapshot_id(self, snapshot_id: str) -> list[Artifact]: ...
    def __enter__(self) -> SQLiteStore: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
