"""Type stubs for timeline management (Layer 6/7 canon workflows)"""

from dataclasses import dataclass
from typing import Any

@dataclass
class TimelineAnchor:
    """A chronological anchor point in the timeline."""

    anchor_id: str
    event: str
    year: int | None = None
    offset: int | None = None
    description: str = ...
    source: str = ...
    immutable: bool = ...
    metadata: dict[str, Any] = ...

    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TimelineAnchor: ...

class TimelineManager:
    """Manager for timeline anchors across canon workflows."""

    def __init__(self) -> None: ...
    def add_anchor(self, anchor: TimelineAnchor) -> None: ...
    def get_anchor(self, anchor_id: str) -> TimelineAnchor | None: ...
    def get_all_anchors(self) -> list[TimelineAnchor]: ...
    def get_baseline_anchors(self) -> list[TimelineAnchor]: ...
    def get_extension_anchors(self) -> list[TimelineAnchor]: ...
    def update_anchor(self, anchor: TimelineAnchor) -> None: ...
    def delete_anchor(self, anchor_id: str) -> None: ...
    def validate_chronology(self) -> list[str]: ...
    def calculate_offset(self, year: int) -> int | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TimelineManager: ...
    def merge(self, anchors: list[TimelineAnchor]) -> dict[str, Any]: ...
    def __len__(self) -> int: ...
    def __contains__(self, anchor_id: str) -> bool: ...
