from .engine import AccessControlEngine as AccessControlEngine
from .exceptions import AccessDeniedError as AccessDeniedError, PolicyNotFoundError as PolicyNotFoundError, RBACError as RBACError, RoleNotFoundError as RoleNotFoundError
from .models import AccessContext as AccessContext, AccessDecision as AccessDecision, Effect as Effect, Policy as Policy, PolicyRule as PolicyRule, Role as Role
from _typeshed import Incomplete
from typing import Any

class RBACManager:
    engine: Incomplete
    logger: Incomplete
    def __init__(self) -> None: ...
    def add_role(self, role: Role) -> None: ...
    def remove_role(self, role_name: str) -> bool: ...
    def get_role(self, role_name: str) -> Role | None: ...
    def list_roles(self) -> list[Role]: ...
    def assign_role(self, user_id: str, role_name: str) -> None: ...
    def revoke_role(self, user_id: str, role_name: str) -> None: ...
    def get_user_roles(self, user_id: str) -> set[str]: ...
    def has_role(self, user_id: str, role_name: str) -> bool: ...
    def has_permission(self, user_id: str, permission: str) -> bool: ...
    def get_user_permissions(self, user_id: str) -> set[str]: ...
    def check_permission(self, user_id: str, resource: str, action: str) -> bool: ...
    def add_policy(self, policy: Policy) -> None: ...
    def remove_policy(self, policy_name: str) -> bool: ...
    def get_policy(self, policy_name: str) -> Policy | None: ...
    def list_policies(self) -> list[Policy]: ...
    def add_policy_rule(self, policy_name: str, rule: PolicyRule) -> None: ...
    def remove_policy_rule(self, policy_name: str, rule_id: str) -> bool: ...
    def check_access(self, context: AccessContext) -> AccessDecision: ...
    def is_allowed(self, user_id: str, resource: str, action: str, **kwargs: Any) -> bool: ...
    def require_access(self, user_id: str, resource: str, action: str, **kwargs: Any) -> None: ...
    def get_user_info(self, user_id: str) -> dict[str, Any]: ...
    def get_role_info(self, role_name: str) -> dict[str, Any] | None: ...
    def get_policy_info(self, policy_name: str) -> dict[str, Any] | None: ...
    def get_stats(self) -> dict[str, Any]: ...
    def validate_role_hierarchy(self, role_name: str) -> list[str]: ...
    def cleanup_inactive_roles(self) -> int: ...
    def cleanup_inactive_policies(self) -> int: ...
