import abc
from _typeshed import Incomplete
from io import BytesIO as BytesIO
from typing import NamedTuple
from zephyr.core.logging.logger import get_logger as get_logger
from zephyr.core.zserver.net.unreader import UnReader as UnReader
from zephyr.core.zserver.protocol.http.constants import HTTP_METHODS as HTTP_METHODS, ParserState as ParserState
from zephyr.core.zserver.protocol.http.exceptions import HTTPParserError as HTTPParserError, InvalidChunkSize as InvalidChunkSize, InvalidHeader as InvalidHeader, InvalidRequestLine as InvalidRequestLine
from zephyr.core.zserver.protocol.http.http import HTTPProtocol as HTTPProtocol
from zephyr.core.zserver.protocol.http.parser.base import BaseHTTPParser as BaseHTTPParser, BaseParser as BaseParser, ParserCallback as ParserCallback

MAX_LINE_SIZE: int
MAX_HEADERS: int
REQUEST_LINE_RE: Incomplete
HEADER_RE: Incomplete
CHUNK_SIZE_RE: Incomplete

class URLComponents(NamedTuple):
    schema: str
    username: str | None
    password: str | None
    hostname: str
    port: int | None
    path: str
    query: str | None
    fragment: str | None

class HttpParser(BaseParser, metaclass=abc.ABCMeta):
    protocol: Incomplete
    unreader: Incomplete
    def __init__(self, protocol: HTTPProtocol, unreader: UnReader | None = None) -> None: ...
    def on_message_begin(self) -> None: ...
    def on_header(self, name: bytes, value: bytes): ...
    def on_headers_complete(self) -> None: ...
    def on_body(self, data: bytes): ...
    def on_message_complete(self) -> None: ...
    def get_header(self, name: str): ...

class LegacyHTTPRequestParser(BaseHTTPParser, metaclass=abc.ABCMeta):
    def __init__(self, callback: ParserCallback | None = None) -> None: ...
    state: Incomplete
    def reset(self) -> None: ...

class HTTPRequestParser(HttpParser):
    unreader: Incomplete
    callback: Incomplete
    state: Incomplete
    logger: Incomplete
    def __init__(self, protocol: HTTPProtocol) -> None: ...
    @property
    def is_complete(self) -> bool: ...
    @is_complete.setter
    def is_complete(self, value: bool): ...
    def error(self) -> str | None: ...
    @property
    def is_error(self) -> bool: ...
    def on_url(self, url: bytes): ...
    def on_error(self, error: str): ...
    def reset(self) -> None: ...
    def feed_data(self, data: bytes) -> None: ...
    def get_http_version(self): ...
    def should_keep_alive(self): ...
    def get_method(self): ...
    def get_parsed_data(self): ...
    def parse_url(self, url: str): ...
    def is_valid_hostname(self, hostname: str): ...
    def join_url(self, base: str, url: str): ...
    def should_upgrade(self): ...
