from setuptools import setup, find_packages

setup(
    name="passw0rts",
    version="0.2",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    package_data={
        "passw0rts": ["web/templates/*.html"],
    },
    include_package_data=True,
    install_requires=[
        "cryptography>=41.0.7",
        "pyotp>=2.9.0",
        "qrcode>=8.0",
        "pyusb>=1.2.1",
        "click>=8.1.7",
        "rich>=13.7.0",
        "pyperclip>=1.8.2",
        "flask>=3.0.0",
        "flask-cors>=4.0.0",
        "pydantic>=2.5.3",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.3",
            "pytest-cov>=4.1.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "passw0rts=passw0rts.cli:main",
        ],
    },
    author="RiseofRice",
    description="A secure cross-platform password manager with CLI and web UI",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/RiseofRice/passw0rts",
    project_urls={
        "Homepage": "https://github.com/RiseofRice/passw0rts",
        "Repository": "https://github.com/RiseofRice/passw0rts",
        "Issues": "https://github.com/RiseofRice/passw0rts/issues",
        "Documentation": "https://github.com/RiseofRice/passw0rts#readme",
        "Changelog": "https://github.com/RiseofRice/passw0rts/blob/main/CHANGELOG.md",
    },
    keywords=[
        "password-manager",
        "security",
        "encryption",
        "cli",
        "2fa",
        "totp",
        "usb-key",
        "yubikey",
        "password-generator",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: End Users/Desktop",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Operating System :: OS Independent",
        "Topic :: Security",
        "Topic :: Security :: Cryptography",
        "Topic :: Utilities",
    ],
    python_requires=">=3.8",
)
