# application -> forget|retain -> prompt
# Retain is usually a similar concept, but depending on the application can be something else, or empty entirely (example: for imagenette class forgetting, the retain set is the remaining 9 classes)
prompts = {
    "naruto": {
        "forget": [
            "A naruto with blue eyes",
            "One naruto character with dark hair and brown eyes",
            "Naruto in a blue shirt and headband",
            "Naruto with a white hat and a red cross on his head",
            "Naruto in armor standing in front of a blue background",
            "A character from the anime naruto with yellow air and orange clothing, hand drawn",
            "A woman from the anime naruto, wearing clothing from the anime, standing in front of a traditional building",
            "An anime character in a white suit with a purple face, drawn in naruto-style",
            "Naruto",
            "Many characters from the series Naruto laughing and hugging each other as a family",
        ],
        "retain": [
            "A man with blue eyes",
            "One person with dark hair and brown eyes",
            "A man in a blue shirt and headband",
            "A man with a white hat and a red cross on his head",
            "A man in armor standing in front of a blue background",
            "A character with yellow air and orange clothing, hand drawn",
            "A woman in a suit and tie standing in front of a building",
            "An cartoon character in a white suit with a purple face",
            "A cartoon character",
            "Many people from the series Naruto laughing and hugging each other as a family",
        ],
    },
    "imagenette_tench": {
        "forget": [
            "Tench swimming in a clear pond",
            "Close-up of a Tench's scales",
            "Tench feeding on pond floor",
            "Two Tench interacting underwater",
            "Tench in an aquarium",
            "Silhouette of Tench in murky water",
            "Tench caught on a fishing line",
            "Tench in a fish tank with plants",
            "Group of Tench in natural habitat",
            "Illustration of a Tench",
            "Tench with spawning colors",
            "Tench in a fish market",
            "Person holding a Tench",
            "Tench and lily pads",
            "Tench in a net",
            "Tench in a fish bowl",
            "Tench and fishing gear",
            "Tench swimming near rocks",
            "Tench in a fish farm",
            "Tench with sunken artifacts",
            "Close-up of Tench's eye",
            "Tench swimming among reeds",
            "Tench in a plastic ba",
            "Baby Tench in a pond",
            "Tench hiding under a log",
            "Tench during winte",
            "Tench and a fisherman",
            "Tench in a public aquariu",
            "Tench with other species",
            "Tench under a floating leaf",
            "Tench on a chopping board",
            "Tench swimming near a boa",
            "Tench in a nature documentary",
            "Tench with a hook in its mouth",
            "Tench swimming against current",
            "Tench in a jar",
            "Tench in a river",
            "Tench being released back",
            "Tench from a bird's-eye view",
            "Tench and a fishing rod",
            "Tench near a waterfal",
            "Tench in muddy water",
            "Tench and a bridge",
            "Tench in a wildlife reserve",
            "Tench and a turtle",
            "Tench under ice",
            "Tench swimming in circle",
            "Tench and bubbles",
            "Tench in an old painting",
            "Tench and a crayfish",
        ],
        "retain": [
        ],
    },
    "imagenette_english_springer": {
        "forget": [
            "Portrait of an English Springer Spaniel with soulful brown eyes",
            "English Springer mid-leap catching a frisbee at sunset",
            "Muddy pawprints leading to an English Springer hiding in the bushes",
            "A vintage oil painting of an English Springer in a hunting scene",
            "Close-up of an English Springer's wet nose and floppy ears",
            "Puppy English Springer tripping over its own oversized feet",
            "An English Springer covered in autumn leaves after rolling in the park",
            "Silhouette of an English Springer running through misty morning fields",
            "English Springer with a flower crown, looking regal and slightly embarrassed",
            "Two English Springers play-fighting over a single stick",
            "An English Springer asleep on the couch, taking up all the space",
            "Black and white photo of an English Springer in mid-yawn",
            "English Springer peeking out from under a blanket during a thunderstorm",
            "A sculpture of an English Springer made from driftwood",
            "English Springer with a bandana, sitting proudly beside a hiking backpack",
            "Watercolor sketch of an English Springer puppy chasing butterflies",
            "An English Springer caught stealing food from the kitchen counter",
            "English Springer in a raincoat, reluctantly walking in the drizzle",
            "Close-up of an English Springer's paw resting on a muddy boot",
            "An English Springer as a medieval knight in a playful digital painting",
            "English Springer standing knee-deep in a river, holding a retrieved duck",
            "A chaotic family photo where the English Springer is the only one looking at the camera",
            "English Springer with a Santa hat, surrounded by torn wrapping paper",
            "An abandoned tennis ball next to a napping English Springer",
            "An English Springer mid-shake, water droplets flying everywhere",
            "Caricature of an English Springer with comically large ears",
            "English Springer sitting patiently beside a 'Wet Paint' sign it just touched",
            "A stained-glass window featuring an English Springer in a church",
            "English Springer hiding under the table during a fireworks display",
            "An English Springer wearing sunglasses in the passenger seat of a convertible",
            "A chalk drawing of an English Springer on a sidewalk",
            "English Springer peering into a fish tank with intense curiosity",
            "An old English Springer with a gray muzzle, sleeping in a sunbeam",
            "A mosaic artwork of an English Springer made from broken tiles",
            "English Springer tangled in its own leash after an enthusiastic greeting",
            "An English Springer as the star of a retro travel poster",
            "Close-up of an English Springer's nose pressed against a window",
            "An English Springer sitting in a shopping cart at the pet store",
            "A woodcut print of an English Springer in a forest",
            "English Springer mid-sneeze, caught in a hilarious photo",
            "An English Springer wearing a superhero cape, looking heroic",
            "A shadow puppet show featuring an English Springer's silhouette",
            "English Springer with a single leaf stuck to its wet nose",
            "An English Springer buried in blankets, only its ears visible",
            "A graffiti mural of an English Springer on a brick wall",
            "An English Springer with a monocle and bowtie, looking sophisticated",
            "A slow-motion shot of an English Springer running through tall grass",
            "An English Springer as a pirate in a children's book illustration",
            "A tiny English Springer puppy next to an oversized chew toy",
            "An English Springer with a 'Adopt Me' bandana at a shelter",
        ],
        "retain": [
        ],
    },
    "imagenette_cassette_player": {
        "forget": [
            "A neon-lit boombox blasting music in a 1980s bedroom",
            "Close-up of a cassette tape spilling its magnetic ribbon like spaghetti",
            "Steampunk-modified cassette player with brass gears and analog dials",
            "A soggy Walkman washed up on a beach, tangled in seaweed",
            "Cassette player mid-rewind, fingers pressing buttons with nostalgic urgency",
            "Cyberpunk hacker using a modified cassette player to decode encrypted tapes",
            "A cassette player melting in a Dali-esque surrealist painting",
            "Vintage ad for a Sony Walkman with bold retro typography",
            "Cassette player embedded in a tree trunk, overgrown by roots",
            "Hand-drawn cassette player surrounded by floating musical notes",
            "A cassette player on a courtroom table as 'Exhibit A' in a 1990s trial",
            "Glow-in-the-dark cassette tapes scattered across a teenager's floor",
            "Cassette player with a spiderweb crack on its display, still playing",
            "A futuristic museum display: 'Early 21st Century Audio Relics'",
            "Cassette player strapped to a skateboard, rattling down the street",
            "Close-up of a pencil rewinding a cassette tape",
            "Cassette player in zero gravity, tapes floating beside it",
            "A cassette player repurposed as a plant holder, vines spilling out",
            "Shadow puppet show of a cassette player spinning tapes",
            "Cassette player left on a park bench, headphones still plugged in",
            "A cassette player glowing under blacklight in a dorm room",
            "Monochrome photo of a cassette player in a rain-soaked alley",
            "Cassette player with a 'fragile' sticker in a moving box",
            "A cassette player being used as a paperweight on a detective's desk",
            "Cassette player in a dystopian wasteland, playing a survival guide",
            "Tiny cassette player in a dollhouse, perfectly scaled",
            "A cassette player with a cassette stuck inside, pliers attempting rescue",
            "Cassette player in a fish tank, bubbles rising around it",
            "A cassette player as a spaceship control panel in a sci-fi comic",
            "Cassette player with a mix tape labeled 'FOR CRUSH - DO NOT ERASE'",
            "A cassette player fossilized in amber",
            "Cassette player dangling from a rearview mirror as a charm",
            "A cassette player in a time capsule buried in 1989",
            "Cassette player playing whale sounds in a meditation room",
            "A cassette player with a cassette ejecting like a toast popping up",
            "Cassette player under a microscope, revealing circuit board landscapes",
            "A cassette player strapped to a pigeon (early drone experiment?)",
            "Cassette player in a horror movie, recording ghostly whispers",
            "A cassette player in a junk shop, priced at $5 with 'AS IS' scrawled",
            "Cassette player submerged in a snow globe, fake snow swirling",
            "A cassette player as a chef's tool, playing recipes on tape",
            "Cassette player in a library's 'obsolete technology' section",
            "A cassette player with one broken headphone jack, held together by tape",
            "Cassette player in a spy film, self-destructing after the message plays",
            "A cassette player in a trench coat (noir-style, leaning against a lamp post)",
            "Cassette player as a religious artifact in a post-apocalyptic cult",
            "A cassette player playing lullabies in a baby's crib",
            "Cassette player in a spaceship's escape pod",
            "A cassette player with a cassette that's just infinite loop of static",
            "Cassette player in a snowstorm, playing 'Winter Wonderland'",
        ],
        "retain": [
        ],
    },
    "imagenette_chain_saw": {
        "forget": [
            "Close-up of a chain saw blade mid-cut, wood chips flying",
            "Vintage 1950s chain saw poster with bold typography",
            "Chain saw abandoned in a foggy forest, moss growing on its handle",
            "Cyberpunk-style chain saw with neon-lit modifications",
            "Silhouette of a lumberjack revving a chain saw at sunrise",
            "Chain saw teeth under a microscope, gleaming and razor-sharp",
            "A chain saw carved entirely out of ice, melting in the sun",
            "Children's drawing of a 'friendly' chain saw with smiley faces",
            "Chain saw suspended in a glass case as modern art",
            "POV shot of a chain saw cutting through thick tree bark",
            "Steampunk chain saw with brass gears and smoke vents",
            "Chain saw left on a workbench, oil dripping onto newspaper",
            "Black and white photo of a 1920s chain saw prototype",
            "Chain saw with a floral wreath wrapped around it (ironic art piece)",
            "Horror scene: blood splatter on a silent chain saw in a dark garage",
            "Chain saw reflected in a puddle after rain",
            "Ultra-minimalist chain saw logo design for a lumber brand",
            "Chain saw mid-fall from a tree branch, motion blur",
            "A chain saw made of LEGO bricks, perfectly detailed",
            "Neon sign of a chain saw for a punk bar",
            "Chain saw buried in snow, only the handle visible",
            "Close-up of gloved hands tightening a chain saw's tension",
            "Chain saw as a tattoo design on a forearm",
            "Sci-fi chain saw with plasma teeth, glowing blue",
            "Abandoned chain saw in a post-apocalyptic wasteland",
            "Chain saw slicing through a watermelon (unexpected juxtaposition)",
            "Rusty chain saw hanging on a barn wall as decor",
            "Chain saw with a 'Hello Kitty' sticker on the bar (absurd humor)",
            "Oil painting of a chain saw resting on a velvet cloth",
            "Chain saw mid-repair, tools and parts scattered around",
            "Chain saw shadow cast on a wooden shed at dusk",
            "Chain saw as a cake decoration, hyper-realistic frosting",
            "Futuristic chain saw drone cutting tree tops from the air",
            "Chain saw balanced precariously on a fence post",
            "Chain saw in a museum exhibit labeled '20th Century Relics'",
            "Chain saw submerged in a murky pond, faint reflection",
            "Chain saw with Christmas lights wrapped around it (holiday chaos)",
            "Graffiti mural of a chain saw melting like Dali's clocks",
            "Chain saw covered in bees (surreal environmental statement)",
            "Chain saw lying in tall grass, almost hidden",
            "Close-up of a chain saw's pull cord snapped mid-use",
            "Chain saw on a conveyor belt in a factory, being assembled",
            "Chain saw with a rainbow oil spill on its metal body",
            "Chain saw in a crime scene photo, tagged as evidence",
            "Chain saw dangling from a helicopter in a rescue training drill",
            "Chain saw with a 'Vegan Powered' parody sticker",
            "Chain saw mid-throw in an action movie freeze frame",
            "Chain saw resting on a picnic table at a lumberjack contest",
            "Chain saw as a character in a Pixar-style animation",
            "Chain saw blade spinning so fast it's just a blur",
        ],
        "retain": [
        ],
    },
    "imagenette_church": {
        "forget": [
            "Old stone church in countryside",
            "Stained glass window of a church",
            "Modern church architecture",
            "People entering a church",
            "Church bell tower at sunset",
            "Church interior with empty pews",
            "Wedding ceremony in a church",
            "Church with snowy background",
            "Ruined church in a forest",
            "Close-up of a church door",
            "Church with an ornate altar",
            "Church facade with sculptures",
            "Gothic church with flying buttresses",
            "Aerial view of a church complex",
            "Tiny village church",
            "Church illuminated at night",
            "Wooden church in a rural setting",
            "Church in a bustling cityscape",
            "Church and graveyard",
            "Seaside church at dawn",
            "Church with modern art installations",
            "Child running towards a church",
            "Choir singing in a church",
            "Church reflection in a pond",
            "Painting of a historical church",
            "Church surrounded by autumn foliage",
            "Couple praying in a church",
            "Sunbeams through church windows",
            "Church during a thunderstorm",
            "Christmas Eve service in a church",
            "Old church converted into a home",
            "Church candles on an altar",
            "Church with traditional icons",
            "Church under construction",
            "Interior of a church dome",
            "Church next to a monaster",
            "Church in a desert landscape",
            "Church with an open-air altar",
            "Church tower with a cloc",
            "Minimalist design of a modern church",
            "Church lit up by fireworks",
            "Medieval church with gargoyles",
            "Abandoned church overgrown with vines",
            "Church in a war zone",
            "Church interior during mass",
            "Church surrounded by blooming flowers",
            "Church with a rainbow backdrop",
            "Church in a mountain setting",
            "Small chapel within a larger church",
            "Church with a large rose window",
        ],
        "retain": [
        ],
    },
    "imagenette_french_horn": {
        "forget": [
            "Gleaming French horn resting on a velvet chair in an empty concert hall",
            "Close-up of a musician's hands adjusting the French horn's valves",
            "French horn lying abandoned in a pawn shop, sunlight hitting its bell",
            "A surrealist painting of a French horn melting like a Dali clock",
            "French horn player mid-note, cheeks puffed out in a jazz ensemble",
            "A child's tiny hands struggling to hold a full-sized French horn",
            "Black and white photo of a French horn submerged in a foggy forest",
            "French horn as a vessel pouring liquid gold in a fantasy illustration",
            "Silhouette of a French horn player against a blood-red sunset",
            "A dented French horn on a battlefield, reflecting a dying fire",
            "Macro shot of light refracting through a French horn's mouthpiece",
            "French horn balanced precariously on the edge of a skyscraper",
            "A French horn wrapped in ivy, half-buried in an overgrown garden",
            "Stop-motion animation of a French horn marching on tiny legs",
            "French horn player's sheet music blowing away in a sudden wind",
            "A French horn made of ice, slowly melting under stage lights",
            "Steampunk French horn with gears and pipes protruding from its coils",
            "Shadow of a French horn cast on a brick wall, twisted into a monster shape",
            "French horn lying in a case lined with torn concert tickets",
            "A neon sign in the shape of a French horn buzzing in a rainy alley",
            "Close-up of a French horn's bell with a spiderweb stretched across it",
            "A French horn player reflected in the eyes of an audience member",
            "French horn floating in zero gravity, droplets of spit suspended around it",
            "A cubist interpretation of a French horn, fragmented into geometric planes",
            "French horn resting on a park bench, leaves collecting inside its bell",
            "A musician polishing a French horn, their tired face mirrored in the metal",
            "French horn played underwater, bubbles streaming from its mouthpiece",
            "A French horn crushed under a tank tread in a war photograph",
            "Miniature French horn as a pendant on a musician's necklace",
            "A French horn player mid-sneeze, their instrument slipping from their grip",
            "French horn lying in a heap of discarded brass instruments at a scrapyard",
            "A French horn's reflection distorted in a funhouse mirror",
            "Glowing French horn in a dark room, lit only by its own bioluminescence",
            "A French horn player wearing noise-canceling headphones in a silent protest",
            "French horn as a rocket ship in a children's book illustration",
            "A close-up of a French horn's valve oil dripping onto a wooden floor",
            "French horn played by a skeleton in a Day of the Dead mural",
            "A French horn tied to a weather balloon, drifting into clouds",
            "French horn duet where one player is a human, the other a robot",
            "A French horn left on a subway seat, echoing with ghostly notes",
            "French horn bell stuffed with flowers in a still-life painting",
            "A musician repairing a French horn with duct tape before a concert",
            "French horn played atop a mountain, soundwaves visible in the thin air",
            "A French horn's shadow puppeteering a rabbit on a moonlit wall",
            "French horn lying in a field, its soundholes buzzing with trapped bees",
            "A Baroque portrait of a nobleman holding a French horn like a scepter",
            "French horn player's breath visible in freezing air during an outdoor performance",
            "A French horn bent into a heart shape for a Valentine's Day art piece",
            "French horn used as a telescope by a curious street cat",
            "A French horn player's hands trembling before their first solo",
        ],
        "retain": [
        ],
    },
    "imagenette_garbage_truck": {
        "forget": [
            "Garbage truck collecting bin",
            "Close-up of garbage truck cab",
            "Garbage truck in a city alley",
            "Person operating a garbage truck",
            "Garbage truck unloading at landfil",
            "Retro garbage truck design",
            "Garbage truck with open back",
            "Toy garbage truck on a carpet",
            "Garbage truck in a parade",
            "Automated garbage truck",
            "Garbage truck at sunrise",
            "Garbage truck in a residential area",
            "Garbage truck with recycling logo",
            "Garbage truck in front of skyscrapers",
            "Garbage truck on a rural road",
            "Garbage truck in a tunnel",
            "Garbage truck with graffiti",
            "Garbage truck during winter",
            "Abandoned garbage truck",
            "Garbage truck on a freeway",
            "Garbage truck in a child's drawing",
            "Person waving at garbage truck",
            "Garbage truck at night",
            "Garbage truck in a parking lot",
            "Garbage truck next to a dumpster",
            "Garbage truck with a flat tire",
            "Close-up of garbage truck machinery",
            "Garbage truck and street sweeper",
            "Garbage truck in silhouette",
            "Garbage truck with colorful bins",
            "Garbage truck in heavy rai",
            "Garbage truck with hazard light",
            "Garbage truck in a factory setting",
            "Garbage truck picking up bulky waste",
            "Garbage truck and alley cat",
            "Garbage truck in 3D rende",
            "Garbage truck near a construction site",
            "Garbage truck on a beach",
            "Garbage truck with cartoon characters",
            "Garbage truck with smoke coming out",
            "Driver inside garbage truck",
            "Garbage truck with a mural",
            "Garbage truck and a bicycle",
            "Garbage truck with holiday lights",
            "Garbage truck in a comic book style",
            "Garbage truck with a logo",
            "Garbage truck in an industrial area",
            "Miniature garbage truck model",
            "Garbage truck with robotic arm",
            "Garbage truck and a school bus",
        ],
        "retain": [
        ],
    },
    "imagenette_gas_pump": {
        "forget": [
            "Vintage gas pump from the 1950s with chrome detailing",
            "A rusted gas pump abandoned in an overgrown field",
            "Gas pump nozzle mid-pour, gasoline shimmering in sunlight",
            "Cyberpunk neon gas station with holographic pump displays",
            "Close-up of a gas pump price sign ticking upward endlessly",
            "Gas pump wrapped in caution tape after a malfunction",
            "Art deco gas pump under the glow of a streetlamp at night",
            "Gas pump with a 'Out of Order' sign covered in graffiti",
            "Miniature gas pump as part of a model train diorama",
            "Gas pump in a snowstorm, icicles hanging from the nozzle",
            "Gas pump reflected in a puddle of spilled fuel",
            "Gas pump with a bee hive attached to its side",
            "Retro-futuristic gas pump from a 1960s sci-fi poster",
            "Gas pump at a lonely desert station at high noon",
            "Gas pump with a vintage Coca-Cola advertisement on its side",
            "Gas pump being repaired, tools scattered around its base",
            "Gas pump in a war zone, bullet holes peppering its display",
            "Gas pump with a handwritten 'Last Fuel for 100 Miles' sign",
            "Gas pump at a futuristic hydrogen refueling station",
            "Gas pump draped in Christmas lights during the holidays",
            "Gas pump with a crow perched on its handle, watching intently",
            "Gas pump in a rainstorm, water droplets on its digital screen",
            "Gas pump as a surrealist painting, melting like Dali's clocks",
            "Gas pump at a drive-in movie theater, cars lined up",
            "Gas pump with a child's sticky handprint on its buttons",
            "Gas pump in a vintage postcard from Route 66",
            "Gas pump engulfed in flames for a disaster movie scene",
            "Gas pump with a tiny door for mice at its base (whimsical)",
            "Gas pump at a 24-hour station, glowing under fluorescent lights",
            "Gas pump with a political campaign sticker slapped on it",
            "Gas pump in a cybercity, accepting cryptocurrency payments",
            "Gas pump with a 'Free Air' sign and an old bicycle nearby",
            "Gas pump as a steampunk contraption with brass fittings",
            "Gas pump in a noir film, shadowy figure refueling at night",
            "Gas pump with a cat napping on its warm top ledge",
            "Gas pump at a farm, next to a tractor and hay bales",
            "Gas pump with a QR code replacing its price display",
            "Gas pump in a zombie apocalypse, overturned and leaking",
            "Gas pump as a cake decoration at a car enthusiast's party",
            "Gas pump with a 'Now Serving' diner-style number display",
            "Gas pump in a virtual reality simulation, glitching slightly",
            "Gas pump with a 'Back in 5 Minutes' note taped to it",
            "Gas pump at a beachside station, sand blowing across its base",
            "Gas pump with a 'Cash Only' sign and a rusty coin slot",
            "Gas pump in a Soviet-era Eastern European station (gritty)",
            "Gas pump as a character in a Pixar-style animation",
            "Gas pump with a 'Please Prepay' sign and a weary attendant",
            "Gas pump in a thunderstorm, lightning illuminating its logo",
            "Gas pump with a 'Ethanol-Free' label, prized by classic cars",
            "Gas pump at a ghost town, its display still flickering",
        ],
        "retain": [
        ],
    },
    "imagenette_golf_ball": {
        "forget": [
            "A single golf ball balanced on a tee at dawn, dew glistening",
            "Macro shot of a golf ball's dimples with grass blades in the background",
            "Golf ball mid-flight, frozen in slow motion against a blue sky",
            "Vintage black-and-white photo of a golf ball on a weathered course",
            "Golf ball submerged in a water hazard, distorted view through the surface",
            "Artistic close-up of a golf ball's surface, lit like a lunar landscape",
            "Golf ball lodged in a tree branch after a rogue shot",
            "Miniature diorama of a golf ball as a planet in a tiny cosmos",
            "Golf ball resting on a sandy bunker, footprints leading away",
            "High-speed photo of a golf ball being crushed by a club impact",
            "Golf ball floating in a glass of iced tea (unfortunate picnic accident)",
            "Time-lapse of a golf ball rolling downhill into a pond",
            "Golf ball with a custom design: skull and crossbones",
            "Black golf ball on white snow, almost invisible",
            "Golf ball wedged between rocks in a desert canyon",
            "Steampunk-style golf ball with brass plating and gears",
            "Golf ball in zero gravity, floating inside a spaceship",
            "Golf ball transformed into a Christmas ornament, hanging on a tree",
            "Golf ball covered in moss, abandoned in a forest",
            "Golf ball on a busy city street, ignored by pedestrians",
            "Glass sculpture of a golf ball, light refracting through it",
            "Golf ball as the pupil of a giant eye in a surreal painting",
            "Golf ball in a fish tank, tetras swimming around it",
            "Golf ball on a chessboard, replacing the king piece",
            "Golf ball balanced on a dog's nose (the dog looks unimpressed)",
            "Golf ball embedded in a tire tread on a muddy road",
            "Golf ball under a microscope, revealing fake alien hieroglyphs",
            "Golf ball in a blender (someone's questionable science experiment)",
            "Golf ball as a disco ball, reflecting light in a dark room",
            "Golf ball on a lawyer's desk, labeled 'Exhibit A'",
            "Golf ball in a frying pan, mistaken for an egg",
            "Golf ball as a soap bubble, shimmering before it pops",
            "Golf ball in a museum display: 'Artifact of 21st-Century Leisure'",
            "Golf ball stuck in a vending machine, just out of reach",
            "Golf ball on a yoga mat, part of a bizarre fitness trend",
            "Golf ball half-buried in a beach at sunset",
            "Golf ball used as a makeshift wheel on a toy car",
            "Golf ball in a bird's nest, mistaken for an egg",
            "Golf ball as a pendant on a gold chain (questionable jewelry)",
            "Golf ball in a washing machine, bouncing violently",
            "Golf ball on a surgeon's tray, labeled 'foreign object'",
            "Golf ball in a movie scene: Indiana Jones swaps it for a relic",
            "Golf ball in a dystopian wasteland, sole remnant of 'the old world'",
            "Golf ball as a cookie cutter (result: very dense cookies)",
            "Golf ball on a courtroom sketch, central to a bizarre trial",
            "Golf ball in a snow globe, shaken violently",
            "Golf ball in a sci-fi lab, glowing with mysterious energy",
            "Golf ball on a pizza, delivered by mistake",
            "Golf ball in a zen garden, disrupting the raked patterns",
            "Golf ball in a claw machine, impossible to win",
        ],
        "retain": [
        ],
    },
    "imagenette_parachute": {
        "forget": [
            "Parachute floating gracefully over a beach",
            "Skydiver with vibrant parachute against clear sky",
            "Paraglider silhouette during sunset",
            "Close-up of a parachute's colorful fabric patterns",
            "Base jumper with parachute over mountainous terrain",
            "Group of parachutes forming a pattern in the sky",
            "Parachute landing on a serene lakeside",
            "Golden parachute glinting in the sun",
            "Paratroopers descending onto a battlefield",
            "Child's toy parachute tossed in the summer breeze",
            "Parachute opening in mid-air",
            "Parachute with custom graphics",
            "Parachute over snowy mountains",
            "Parachute landing in a stadium",
            "Parachute in an indoor wind tunnel",
            "Parachute tied to a speedboat",
            "Parachute packed in its bag",
            "Parachute next to an airplane",
            "Parachute with a company logo",
            "Parachute over a city skyline",
            "Parachute in a military exercis",
            "Parachute with an action camera",
            "Parachute in a forest canopy",
            "Parachute near a clif",
            "Parachute during a rainbow",
            "Parachute landing on a rooftop",
            "Parachute tangled in a tree",
            "Emergency parachute in a cockpit",
            "Parachute in a virtual reality simulation",
            "Parachute over a volcano",
            "Parachute during twilight",
            "Parachute in an art installation",
            "Parachute at a high altitude",
            "Parachute over a coral reef",
            "Parachute and a hot air balloo",
            "Parachute with a GoPro view",
            "Parachute during a storm",
            "Parachute with flares",
            "Parachute in a retro style",
            "Parachute in a desert landscape",
            "Parachute in a NASA training",
            "Parachute in a flooded area",
            "Parachute and a hang glider",
            "Parachute in a moonlit night",
            "Parachute over a historical monument",
            "Parachute and a kite",
            "Parachute with a drone",
            "Parachute in a windstorm",
            "Parachute over a festival",
            "Parachute over a river",
        ],
        "retain": [
        ],
    },
    "style_vangogh": {
        "forget": [
            "A Wheatfield, with Cypresses by Vincent van Gogh",
            "Almond Blossoms by Vincent van Gogh",
            "Bedroom in Arles by Vincent van Gogh",
            "Bridge at Trinquetaille by Vincent van Gogh",
            "Café Terrace at Night by Vincent van Gogh",
            "Cypresses by Vincent van Gogh",
            "Enclosed Field with Rising Sun by Vincent van Gogh",
            "Entrance to a Quarry by Vincent van Gogh",
            "Fishing Boats on the Beach at Saintes-Maries by Vincent van Gogh",
            "Green Wheat Field with Cypress by Vincent van Gogh",
            "Harvest at La Crau, with Montmajour in the Background by Vincent van Gogh",
            "Irises by Vincent van Gogh",
            "La Mousmé by Vincent van Gogh",
            "Landscape at Saint-Rémy by Vincent van Gogh",
            "Landscape with Snow by Vincent van Gogh",
            "Olive Trees by Vincent van Gogh",
            "Peasant Woman Binding Sheaves by Vincent van Gogh",
            "Portrait of Dr. Gachet by Vincent van Gogh",
            "Portrait of Joseph Roulin by Vincent van Gogh",
            "Red Vineyards at Arles by Vincent van Gogh",
            "Rooftops in Paris by Vincent van Gogh",
            "Self-portrait with Bandaged Ear by Vincent van Gogh",
            "Sorrow by Vincent van Gogh",
            "Sower with Setting Sun by Vincent van Gogh",
            "Starry Night Over the Rhone by Vincent van Gogh",
            "Starry Night by Vincent van Gogh",
            "Sunflowers by Vincent van Gogh",
            "The Bedroom by Vincent van Gogh",
            "The Church at Auvers by Vincent van Gogh",
            "The Cottage by Vincent van Gogh",
            "The Mulberry Tree by Vincent van Gogh",
            "The Night Café by Vincent van Gogh",
            "The Old Mill by Vincent van Gogh",
            "The Potato Eaters by Vincent van Gogh",
            "The Reaper by Vincent van Gogh",
            "The Red Vineyard by Vincent van Gogh",
            "The Road Menders by Vincent van Gogh",
            "The Siesta by Vincent van Gogh",
            "The Starry Night Over the Rhône by Vincent van Gogh",
            "The Starry Night by Vincent van Gogh",
            "The Weaver by Vincent van Gogh",
            "The White Orchard by Vincent van Gogh",
            "The Yellow House by Vincent van Gogh",
            "The Zouave by Vincent van Gogh",
            "Two Cut Sunflowers by Vincent van Gogh",
            "Vase with Fifteen Sunflowers by Vincent van Gogh",
            "Vase with Twelve Sunflowers by Vincent van Gogh",
            "Vincent's Chair by Vincent van Gogh",
            "Wheat Field with Reaper and Sun by Vincent van Gogh",
            "Wheatfield with Crows by Vincent van Gogh",
        ],
        "retain": [
            "A beautiful landscape painting",
            "A colorful painting of a field",
            "A painting of sunflowers",
        ],
    },
}
