SECRET_KEY="demo-secret-key"
BABEL_DEFAULT_LOCALE = "en"
BABEL_DEFAULT_TIMEZONE= "UTC"
SUPPORTED_LANGUAGES = {
  "en": "English",
  "ko": "한국어",
  "it": "Italiano",
  "nl": "Nederlands",
  "de": "Deutsch",
  "pt": "Português",
  "es": "Español",
  "fr": "Français",
  "hi": "हिन्दी",
  "vi": "Tiếng Việt",
  "ja": "日本語",
  "pl": "Polski",
  "ru": "Русский",
  "th": "ไทย",
  "tr": "Türkçe",
  "zh-hans": "简体中文",
  "zh-hant": "繁體中文",
  "id": "Bahasa Indonesia",
  "ar": "العربية",
  # "af": "Afrikaans",
  # "ar-dz": "العربية (الجزائر)",
  # "ast": "Asturianu",
  # "az": "Azərbaycanca",
  # "bg": "Български",
  # "be": "Беларуская",
  # "bn": "বাংলা",
  # "br": "Brezhoneg",
  # "bs": "Bosanski",
  # "ca": "Català",
  # "ckb": "کوردیی ناوەندی",
  # "cs": "Čeština",
  # "cy": "Cymraeg",
  # "da": "Dansk",
  # "dsb": "Dolnoserbšćina",
  # "el": "Ελληνικά",
  # "en-au": "Australian English",
  # "en-gb": "British English",
  # "eo": "Esperanto",
  # "es-ar": "Español de Argentina",
  # "es-co": "Español de Colombia",
  # "es-mx": "Español de México",
  # "es-ni": "Español de Nicaragua",
  # "es-ve": "Español de Venezuela",
  # "et": "Eesti",
  # "eu": "Euskara",
  # "fa": "فارسی",
  # "fi": "Suomi",
  # "fy": "Frysk",
  # "ga": "Gaeilge",
  # "gd": "Gàidhlig",
  # "gl": "Galego",
  # "he": "עברית",
  # "hr": "Hrvatski",
  # "hsb": "Hornjoserbšćina",
  # "hu": "Magyar",
  # "hy": "Հայերեն",
  # "ia": "Interlingua",
  # "ig": "Igbo",
  # "io": "Ido",
  # "is": "Íslenska",
  # "ka": "ქართული",
  # "kab": "Taqbaylit",
  # "kk": "Қазақ тілі",
  # "km": "ភាសាខ្មែរ",
  # "kn": "ಕನ್ನಡ",
  # "ky": "Кыргызча",
  # "lb": "Lëtzebuergesch",
  # "lt": "Lietuvių",
  # "lv": "Latviešu",
  # "mk": "Македонски",
  # "ml": "മലയാളം",
  # "mn": "Монгол",
  # "mr": "मराठी",
  # "ms": "Bahasa Melayu",
  # "my": "မြန်မာဘာသာ",
  # "nb": "Norsk bokmål",
  # "ne": "नेपाली",
  # "nn": "Norsk nynorsk",
  # "os": "Ирон",
  # "pa": "ਪੰਜਾਬੀ",
  # "pt-br": "Português do Brasil",
  # "ro": "Română",
  # "sk": "Slovenčina",
  # "sl": "Slovenščina",
  # "sq": "Shqip",
  # "sr": "Српски",
  # "sr-latn": "Srpski (latinica)",
  # "sv": "Svenska",
  # "sw": "Kiswahili",
  # "ta": "தமிழ்",
  # "te": "తెలుగు",
  # "tg": "Тоҷикӣ",
  # "tk": "Türkmençe",
  # "tt": "Татарча",
  # "udm": "Удмурт",
  # "uk": "Українська",
  # "ur": "اردو",
  # "uz": "O'zbek"
}

SUPPORTED_COUNTRIES = [
    'Afghanistan',
    'Åland',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bonaire, Sint Eustatius and Saba',
    'Bosnia and Herzegovina',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'British Indian Ocean Territory',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Cayman Islands',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos (Keeling) Islands',
    'Colombia',
    'Comoros',
    'Congo (Brazzaville)',
    'Congo (Kinshasa)',
    'Cook Islands',
    'Costa Rica',
    "Côte d'Ivoire",
    'Croatia',
    'Curaçao',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Falkland Islands',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Lands',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard and McDonald Islands',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, South',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macau',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'Northern Mariana Islands',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Pitcairn',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Reunion',
    'Romania',
    'Rwanda',
    'Saint Barthélemy',
    'Saint Helena',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin (French part)',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia and South Sandwich Islands',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Svalbard and Jan Mayen Islands',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Türkiye',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States Minor Outlying Islands',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Virgin Islands, British',
    'Virgin Islands, U.S.',
    'Wallis and Futuna Islands',
    'Yemen',
    'Zambia',
    'Zimbabwe',
]