from ._base_enum import BaseEnum


class SpecialUseCode(BaseEnum):
    ADMINISTRATIVE_SERVICES = "ADMINISTRATIVE SERVICES"
    GEOGRAPHIC_REFERENCE_POINT = "GEOGRAPHIC REFERENCE POINT"
    SPECIAL_USAGE = "SPECIAL USAGE"
    WEATHER_SERVICE_OFFICE = "WEATHER SERVICE OFFICE"
    WEATHER_STATION = "WEATHER STATION"
    NULL = None
