from ._base_enum import BaseEnum


class VGSICode(BaseEnum):
    SIMPLIFIED_VASI = "SAVASI"
    VASI = "VASI"
    PAPI = "PAPI"
    TRI_VASI = "TRI"
    PULSE_VASI = "PSI"
    PANELS = "PNI"
    SAVASI_2_LEFT = "S2L"
    SAVASI_2_RIGHT = "S2R"
    VASI_2_LEFT = "V2L"
    VASI_2_RIGHT = "V2R"
    VASI_4_LEFT = "V4L"
    VASI_4_RIGHT = "V4R"
    VASI_6_LEFT = "V6L"
    VASI_6_RIGHT = "V6R"
    VASI_12_BOTH = "V12"
    VASI_16_BOTH = "V16"
    PAPI_2_LEFT = "P2L"
    PAPI_2_RIGHT = "P2R"
    PAPI_4_LEFT = "P4L"
    PAPI_4_RIGHT = "P4R"
    NON_STANDARD_VASI = "NSTD"
    PRIVATE_USE = "PVT"
    NON_SPECIFIC_VASI = "VAS"
    NONE = "NONE"
    NO = "N"
    TRI_VASI_LEFT = "TRIL"
    TRI_VASI_RIGHT = "TRIR"
    PULSE_VASI_LEFT = "PSIL"
    PULSE_VASI_RIGHT = "PSIR"
    PANELS_LEFT = "PNIL"
    PANELS_RIGHT = "PNIR"
    NULL = None
