from ._base_enum import BaseEnum


class WeatherServiceCode(BaseEnum):
    SEVERE_WEATHER_OUTLOOK_NARRATIVE = "AC"
    SEVERE_WEATHER_FORECAST_ALERT = "AWW"
    CENTRAL_WEATHER_ADVISORY = "CWA"
    AREA_FORECAST = "FA"
    WIND_TEMPERATURE_ALOFT_FORECAST = "FD"
    AVIATION_TERMINAL_FORECAST = "FT"
    MISCELLANEOUS_FORECASTS = "FX"
    ROUTINE_AVIATION_WEATHER_REPORT = "METAR"
    METEOROLOGICAL_IMPACT_SUMMARY = "MIS"
    NOTICE_TO_AIRMEN = "NOTAM"
    SURFACE_OBSERVATION_REPORT = "SA"
    RADAR_WEATHER_REPORT = "SD"
    SPECIAL_AVIATION_WEATHER_REPORT = "SPECI"
    TRANSCRIBED_WEATHER_BROADCAST_SYNOPSIS = "SYNS"
    TERMINAL_AVIATION_FORECAST = "TAF"
    TRANSCRIBED_WEATHER_BROADCAST = "TWEB"
    PIREP = "UA"
    WEATHER_ADVISORY = "WA"
    ABBREVIATED_HURRICANE_ADVISORY = "WH"
    TROPICAL_DEPRESSIONS = "WO"
    FLIGHT_ADVISORY_SIGMET = "WS"
    CONVECTIVE_SIGMET = "WST"
    SEVERE_WEATHER = "WW"
    NULL = None
