import abc
from .config import AppleSSOConfig as AppleSSOConfig, GenericOAuth2SSOConfig as GenericOAuth2SSOConfig, GitHubSSOConfig as GitHubSSOConfig, GoogleSSOConfig as GoogleSSOConfig, MicrosoftSSOConfig as MicrosoftSSOConfig, SAMLSSOConfig as SAMLSSOConfig
from .exceptions import SSOAuthError as SSOAuthError, SSOConfigError as SSOConfigError, SSOInvalidResponseError as SSOInvalidResponseError, SSONetworkError as SSONetworkError, SSOProviderError as SSOProviderError, SSOUnsupportedProviderError as SSOUnsupportedProviderError
from .models import SSOAuthResult as SSOAuthResult, SSOAuthState as SSOAuthState, SSOUser as SSOUser, create_auth_state as create_auth_state
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from cryptography.hazmat.primitives import hashes as hashes
from cryptography.hazmat.primitives.asymmetric import rsa as rsa
from cryptography.hazmat.primitives.kdf import pbkdf2 as pbkdf2
from datetime import datetime as datetime, timedelta as timedelta
from typing import Any
from urllib.parse import urlparse as urlparse

class SSOProvider(ABC, metaclass=abc.ABCMeta):
    config: Incomplete
    provider_name: Incomplete
    http_client: Incomplete
    def __init__(self, config: dict[str, Any]) -> None: ...
    @abstractmethod
    def get_provider_name(self) -> str: ...
    @abstractmethod
    def get_authorization_url(self, state: str, **kwargs: Any) -> str: ...
    @abstractmethod
    async def exchange_code_for_token(self, code: str, state: str) -> dict[str, Any]: ...
    @abstractmethod
    async def get_user_info(self, access_token: str) -> dict[str, Any]: ...
    @abstractmethod
    def map_user_data(self, user_data: dict[str, Any]) -> SSOUser: ...
    async def authenticate(self, code: str, state: str) -> SSOAuthResult: ...
    async def close(self) -> None: ...

class GoogleSSOProvider(SSOProvider):
    google_config: Incomplete
    def __init__(self, config: GoogleSSOConfig) -> None: ...
    def get_provider_name(self) -> str: ...
    def get_authorization_url(self, state: str, **kwargs: Any) -> str: ...
    async def exchange_code_for_token(self, code: str, state: str) -> dict[str, Any]: ...
    async def get_user_info(self, access_token: str) -> dict[str, Any]: ...
    def map_user_data(self, user_data: dict[str, Any]) -> SSOUser: ...

class GitHubSSOProvider(SSOProvider):
    github_config: Incomplete
    def __init__(self, config: GitHubSSOConfig) -> None: ...
    def get_provider_name(self) -> str: ...
    def get_authorization_url(self, state: str, **kwargs: Any) -> str: ...
    async def exchange_code_for_token(self, code: str, state: str) -> dict[str, Any]: ...
    async def get_user_info(self, access_token: str) -> dict[str, Any]: ...
    def map_user_data(self, user_data: dict[str, Any]) -> SSOUser: ...

class MicrosoftSSOProvider(SSOProvider):
    microsoft_config: Incomplete
    def __init__(self, config: MicrosoftSSOConfig) -> None: ...
    def get_provider_name(self) -> str: ...
    def get_authorization_url(self, state: str, **kwargs: Any) -> str: ...
    async def exchange_code_for_token(self, code: str, state: str) -> dict[str, Any]: ...
    async def get_user_info(self, access_token: str) -> dict[str, Any]: ...
    def map_user_data(self, user_data: dict[str, Any]) -> SSOUser: ...

class AppleSSOProvider(SSOProvider):
    apple_config: Incomplete
    def __init__(self, config: AppleSSOConfig) -> None: ...
    def get_provider_name(self) -> str: ...
    def get_authorization_url(self, state: str, **kwargs: Any) -> str: ...
    async def exchange_code_for_token(self, code: str, state: str) -> dict[str, Any]: ...
    async def get_user_info(self, access_token: str) -> dict[str, Any]: ...
    def map_user_data(self, user_data: dict[str, Any]) -> SSOUser: ...

class SAMLSSOProvider(SSOProvider):
    saml_config: Incomplete
    def __init__(self, config: SAMLSSOConfig) -> None: ...
    def get_provider_name(self) -> str: ...
    def get_authorization_url(self, state: str, **kwargs: Any) -> str: ...
    async def exchange_code_for_token(self, code: str, state: str) -> dict[str, Any]: ...
    async def get_user_info(self, access_token: str) -> dict[str, Any]: ...
    def map_user_data(self, user_data: dict[str, Any]) -> SSOUser: ...

class GenericOAuth2SSOProvider(SSOProvider):
    oauth2_config: Incomplete
    def __init__(self, config: GenericOAuth2SSOConfig) -> None: ...
    def get_provider_name(self) -> str: ...
    def get_authorization_url(self, state: str, **kwargs: Any) -> str: ...
    async def exchange_code_for_token(self, code: str, state: str) -> dict[str, Any]: ...
    async def get_user_info(self, access_token: str) -> dict[str, Any]: ...
    def map_user_data(self, user_data: dict[str, Any]) -> SSOUser: ...

def create_sso_provider(provider_name: str, config: dict[str, Any]) -> SSOProvider: ...
